// ╔══════════════════════════════════════════════════════════════╗
// ║  PlAIncy — Borehamwood Plancy League                         ║
// ║  Generated by scripts/build-artifact.js — all data inlined  ║
// ║  Edit commissioner.template.jsx, then run build-artifact.js  ║
// ╚══════════════════════════════════════════════════════════════╝

// The current Claude.ai artifact runtime is an ESM sandbox — React is imported,
// not a script-tag global. (Older runtimes exposed a global `React`.)
import React, { useState, useEffect, useRef, useMemo } from "react";
const DEBUG = false; // set true to log system-prompt sizes to the console
// Single position→colour map (was duplicated as POSColors + POS_TINT).
const POS_COLORS = { QB: '#ff7a1a', RB: '#10b981', WR: '#60a5fa', TE: '#a855f7', K: '#94a3b8', DEF: '#f87171', FLEX: '#f59e0b' };

const ALIAS = { allyl900: 'AlastairL' };
function canonical(handle) {
  const c = String(handle || '').replace(/^@/, '').trim();
  return ALIAS[c] || c;
}
const NAMES = { AlastairL:'Alastair', dpol:'Dan', saulgoat:'Saul', sanfbe:'Benjy', joshjr11:'Josh', drjkay:'Jamie', GSac:'Gideon', benjlev:'Benjy' };
const DISAMBIG = { benjlev:'Lev', sanfbe:'Sanford' };
function displayName(h) { const c = canonical(h); return NAMES[c] || c; }
function distinctName(h) { const c = canonical(h); return DISAMBIG[c] || NAMES[c] || c; }
function teamLabel(k) {
  const m = String(k).match(/\(@([^)]+)\)/);
  const handle = m ? m[1] : null;
  const team = String(k).replace(/\s*\(@[^)]+\)\s*$/, '').trim();
  const nm = handle ? displayName(handle) : null;
  return (nm && nm !== handle) ? `${nm} · ${team}` : (team || k);
}

const BUILT_AT = __BUILT_AT__;

function fmtBuiltAt(iso) {
  try {
    const d = new Date(iso);
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return d.getDate() + ' ' + months[d.getMonth()] + ' ' + d.getFullYear();
  } catch(e) { return 'recently'; }
}

const HISTORY_DATA = __HISTORY__;
const STATS_DATA = __STATS__;
const ROSTERS_DATA = __ROSTERS__;
const TRADE_VALUES = __TRADES__;
const ALLTIME_DATA = __ALLTIME__;
const TRANSACTIONS_DATA = __TRANSACTIONS__;
const PLAYER_SCORES = __PLAYERS__;

const REPO = 'alastairlivingston-sudo/sleeper-league-app-3';
const PAGES_BASE = 'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1];

const DATA_SOURCES = [
  { history: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/history.json', stats: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/stats.json', rosters: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/rosters.json', trades: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/fc-values.json', alltime: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/alltime.json', transactions: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/transactions.json', players: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/player-scores.json' },
  { history: PAGES_BASE + '/data/history.json', stats: PAGES_BASE + '/data/stats.json', rosters: PAGES_BASE + '/data/rosters.json', trades: PAGES_BASE + '/data/fc-values.json', alltime: PAGES_BASE + '/data/alltime.json', transactions: PAGES_BASE + '/data/transactions.json', players: PAGES_BASE + '/data/player-scores.json' },
];

const LORE_SOURCES = [
  { master: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/master.json', archive: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/archive-index.json', quotes: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/quotes-index.json' },
  { master: PAGES_BASE + '/lore/master.json', archive: PAGES_BASE + '/lore/archive-index.json', quotes: PAGES_BASE + '/lore/quotes-index.json' },
];
// jsDelivr sets a 7-day browser cache; append a daily buster so a returning
// user pulls fresh data each calendar day (the Action publishes once daily).
const BUST = '?v=' + new Date().toISOString().slice(0, 10);

const T = {
  bg: '#090d18', panel: '#0f1625', panel2: '#141e32', raised: '#1a2640',
  border: '#24344e', borderHi: '#304260', text: '#e8f1ff', dim: '#6e8db0',
  faint: '#3d5470', indigo: '#6366f1', indigoDk: '#4f46e5',
  green: '#10b981', amber: '#f59e0b', blue: '#60a5fa', red: '#f87171',
};
const FF = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif";

// Calling the model from an artifact.
// The current Claude.ai artifact runtime is a sandboxed iframe (claudeusercontent.com)
// under a strict CSP: a raw fetch to api.anthropic.com is BLOCKED. The sanctioned
// bridge the host injects is window.claude.complete(promptString) -> string. It has
// no system/messages separation and no memory, so we flatten the whole exchange into
// one prompt string. (Older runtimes proxied the Messages API instead; that path is
// kept below as a fallback so the artifact works in both.)
const MODELS = ['claude-sonnet-5', 'claude-sonnet-4-5', 'claude-haiku-4-5'];
let modelIdx = 0;

function flattenPrompt(messages, systemPrompt) {
  const convo = (messages || [])
    .filter(function(m) { return m.role === 'user' || m.role === 'assistant'; })
    .map(function(m) { return (m.role === 'user' ? 'Human' : 'Assistant') + ': ' + m.content; })
    .join('\n\n');
  return systemPrompt + '\n\n' + convo + '\n\nAssistant:';
}

async function claudeCall(messages, systemPrompt) {
  // Primary: window.claude.complete (current artifact sandbox).
  if (typeof window !== 'undefined' && window.claude && typeof window.claude.complete === 'function') {
    const out = await window.claude.complete(flattenPrompt(messages, systemPrompt));
    if (!out) throw new Error('Empty response');
    return out;
  }
  // Fallback: older runtime that proxied the Messages API directly.
  return messagesApiCall(messages, systemPrompt);
}

async function messagesApiCall(messages, systemPrompt) {
  const body = (model) => JSON.stringify({
    model,
    max_tokens: 2000,
    system: systemPrompt,
    messages: messages
      .filter(function(m) { return m.role === 'user' || m.role === 'assistant'; })
      .map(function(m) { return { role: m.role, content: m.content }; }),
  });
  let lastErr = null;
  while (modelIdx < MODELS.length) {
    for (let attempt = 0; attempt < 3; attempt++) {
      const ctrl = new AbortController();
      const timer = setTimeout(function() { ctrl.abort(); }, 60000);
      try {
        const res = await fetch('https://api.anthropic.com/v1/messages', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: body(MODELS[modelIdx]),
          signal: ctrl.signal,
        });
        if (res.status === 404) { lastErr = new Error('MODEL_ERROR'); break; } // next model
        if (res.status === 429 || res.status >= 500) {
          lastErr = new Error('API ' + res.status);
          const ra = parseInt(res.headers.get('retry-after') || '0', 10);
          await new Promise(function(r) { setTimeout(r, ra > 0 ? ra * 1000 : (attempt + 1) * 2000); });
          continue; // retry same model
        }
        if (!res.ok) throw new Error('API ' + res.status);
        const data = await res.json();
        const text = (data.content || []).filter(function(b) { return b.type === 'text'; }).map(function(b) { return b.text; }).join('');
        if (!text) throw new Error('Empty response');
        return text;
      } catch (e) {
        if (e.message === 'MODEL_ERROR') break;
        lastErr = e;
        if (e.name === 'AbortError') continue; // timeout → retry
        throw e; // real network/4xx error — surface it
      } finally {
        clearTimeout(timer);
      }
    }
    if (lastErr && lastErr.message === 'MODEL_ERROR') { modelIdx++; lastErr = null; continue; }
    break; // retries exhausted on a live model
  }
  throw modelIdx >= MODELS.length ? new Error('MODEL_ERROR') : (lastErr || new Error('API failed'));
}

