// ╔══════════════════════════════════════════════════════════════╗
// ║  PlAIncy — Borehamwood Plancy League                         ║
// ║  Generated by scripts/build-artifact.js — all data inlined  ║
// ║  Edit commissioner.template.jsx, then run build-artifact.js  ║
// ╚══════════════════════════════════════════════════════════════╝

const { useState, useEffect, useRef, useMemo } = React;

const ALIAS = { allyl900: 'AlastairL' };
function canonical(handle) {
  const c = String(handle || '').replace(/^@/, '').trim();
  return ALIAS[c] || c;
}
const NAMES = { AlastairL:'Alastair', dpol:'Dan', saulgoat:'Saul', sanfbe:'Benjy', joshjr11:'Josh', drjkay:'Jamie', GSac:'Gideon', benjlev:'Benjy' };
const DISAMBIG = { benjlev:'Lev', sanfbe:'Sanford' };
function displayName(h) { const c = canonical(h); return NAMES[c] || c; }
function distinctName(h) { const c = canonical(h); return DISAMBIG[c] || NAMES[c] || c; }
function teamLabel(k) {
  const m = String(k).match(/\(@([^)]+)\)/);
  const handle = m ? m[1] : null;
  const team = String(k).replace(/\s*\(@[^)]+\)\s*$/, '').trim();
  const nm = handle ? displayName(handle) : null;
  return (nm && nm !== handle) ? `${nm} · ${team}` : (team || k);
}

const BUILT_AT = __BUILT_AT__;

function fmtBuiltAt(iso) {
  try {
    const d = new Date(iso);
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return 'Updated ' + d.getDate() + ' ' + months[d.getMonth()] + ' ' + d.getFullYear();
  } catch(e) { return 'Updated recently'; }
}

const HISTORY_DATA = __HISTORY__;
const STATS_DATA = __STATS__;
const ROSTERS_DATA = __ROSTERS__;
const TRADE_VALUES = __TRADES__;
const ALLTIME_DATA = __ALLTIME__;
const TRANSACTIONS_DATA = __TRANSACTIONS__;

const REPO = 'alastairlivingston-sudo/sleeper-league-app-3';
const PAGES_BASE = 'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1];

const DATA_SOURCES = [
  { history: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/history.json', stats: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/stats.json', rosters: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/rosters.json', trades: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/fc-values.json', alltime: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/alltime.json', transactions: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/data/transactions.json' },
  { history: PAGES_BASE + '/data/history.json', stats: PAGES_BASE + '/data/stats.json', rosters: PAGES_BASE + '/data/rosters.json', trades: PAGES_BASE + '/data/fc-values.json', alltime: PAGES_BASE + '/data/alltime.json', transactions: PAGES_BASE + '/data/transactions.json' },
];

const LORE_SOURCES = [
  { master: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/master.json', archive: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/archive-index.json', quotes: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/docs/lore/quotes-index.json' },
  { master: PAGES_BASE + '/lore/master.json', archive: PAGES_BASE + '/lore/archive-index.json', quotes: PAGES_BASE + '/lore/quotes-index.json' },
];
// jsDelivr sets a 7-day browser cache; append a daily buster so a returning
// user pulls fresh data each calendar day (the Action publishes once daily).
const BUST = '?v=' + new Date().toISOString().slice(0, 10);

const T = {
  bg: '#090d18', panel: '#0f1625', panel2: '#141e32', raised: '#1a2640',
  border: '#24344e', borderHi: '#304260', text: '#e8f1ff', dim: '#6e8db0',
  faint: '#3d5470', indigo: '#6366f1', indigoDk: '#4f46e5',
  green: '#10b981', amber: '#f59e0b', blue: '#60a5fa', red: '#f87171',
};
const FF = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif";

// In Claude.ai artifacts, fetch to the Anthropic API is proxied automatically —
// no API key required. Using the Messages API directly gives proper system/messages
// separation and avoids the hidden prompt-budget limits of window.claude.complete().
async function claudeCall(messages, systemPrompt) {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1000,
      system: systemPrompt,
      messages: messages
        .filter(function(m) { return m.role === 'user' || m.role === 'assistant'; })
        .map(function(m) { return { role: m.role, content: m.content }; }),
    }),
  });
  if (!res.ok) throw new Error('API ' + res.status);
  const data = await res.json();
  const text = (data.content || []).filter(function(b) { return b.type === 'text'; }).map(function(b) { return b.text; }).join('');
  if (!text) throw new Error('Empty response');
  return text;
}

function r1(n) { return Math.round(n * 10) / 10; }
function r2(n) { return Math.round(n * 100) / 100; }
function stdev(arr) {
  if (arr.length < 2) return 0;
  const m = arr.reduce(function(a, b) { return a + b; }, 0) / arr.length;
  return Math.sqrt(arr.reduce(function(a, b) { return a + (b - m) * (b - m); }, 0) / arr.length);
}
function blankRow(h) { return { handle: h, w: 0, l: 0, t: 0, pf: 0, pa: 0, scores: [], apW: 0, apL: 0, apT: 0 }; }
function finalizeRow(m) {
  const games = m.w + m.l + m.t;
  const apG = m.apW + m.apL + m.apT;
  const apPct = apG ? m.apW / apG : 0;
  const expW = apPct * games;
  const avg = m.scores.length ? m.scores.reduce(function(a,b){return a+b;},0) / m.scores.length : 0;
  return {
    name: displayName(m.handle), alias: distinctName(m.handle), handle: m.handle,
    record: m.w + '-' + m.l + (m.t ? '-' + m.t : ''),
    wins: m.w, losses: m.l, pf: r2(m.pf), pa: r2(m.pa),
    avgScore: r1(avg), consistencySD: r1(stdev(m.scores)),
    high: m.scores.length ? r2(Math.max.apply(null, m.scores)) : 0,
    low: m.scores.length ? r2(Math.min.apply(null, m.scores)) : 0,
    allPlay: m.apW + '-' + m.apL + (m.apT ? '-' + m.apT : ''),
    allPlayWinPct: r1(apPct * 100), expectedWins: r1(expW), luck: r1(m.w - expW),
  };
}
function computeAnalytics(history) {
  const seasons = (history && history.seasons) ? history.seasons : [];
  const perSeason = [];
  const allAcc = {};
  for (let si = 0; si < seasons.length; si++) {
    const s = seasons[si];
    const acc = {};
    const weeks = {};
    const games = s.games || [];
    for (let gi = 0; gi < games.length; gi++) {
      const g = games[gi];
      if (g.playoff || !(g.pa > 0 || g.pb > 0)) continue;
      if (!weeks[g.week]) weeks[g.week] = [];
      weeks[g.week].push(g);
    }
    const weekKeys = Object.keys(weeks);
    for (let wi = 0; wi < weekKeys.length; wi++) {
      const wgames = weeks[weekKeys[wi]];
      const board = [];
      for (let gi = 0; gi < wgames.length; gi++) {
        const g = wgames[gi];
        const ha = canonical(g.a), hb = canonical(g.b);
        if (!acc[ha]) acc[ha] = blankRow(ha);
        if (!acc[hb]) acc[hb] = blankRow(hb);
        const A = acc[ha], B = acc[hb];
        A.pf += g.pa; A.pa += g.pb; A.scores.push(g.pa);
        B.pf += g.pb; B.pa += g.pa; B.scores.push(g.pb);
        if (g.pa > g.pb) { A.w++; B.l++; } else if (g.pb > g.pa) { B.w++; A.l++; } else { A.t++; B.t++; }
        board.push([ha, g.pa], [hb, g.pb]);
      }
      for (let ai = 0; ai < board.length; ai++) {
        const h = board[ai][0], sc = board[ai][1];
        const a = acc[h];
        for (let bi = 0; bi < board.length; bi++) {
          const h2 = board[bi][0], sc2 = board[bi][1];
          if (h2 === h) continue;
          if (sc > sc2) a.apW++; else if (sc < sc2) a.apL++; else a.apT++;
        }
      }
    }
    const rows = Object.values(acc);
    if (rows.length) {
      perSeason.push({
        season: s.season,
        champion: s.champion ? displayName(s.champion) : null,
        managers: rows.map(finalizeRow).sort(function(a,b){ return b.wins - a.wins || b.pf - a.pf; }),
      });
    }
    for (let ri = 0; ri < rows.length; ri++) {
      const m = rows[ri];
      if (!allAcc[m.handle]) allAcc[m.handle] = blankRow(m.handle);
      const t = allAcc[m.handle];
      t.w += m.w; t.l += m.l; t.t += m.t; t.pf += m.pf; t.pa += m.pa;
      t.apW += m.apW; t.apL += m.apL; t.apT += m.apT;
      for (let si2 = 0; si2 < m.scores.length; si2++) t.scores.push(m.scores[si2]);
    }
  }
  const allTime = Object.values(allAcc).map(finalizeRow).sort(function(a,b){ return b.wins - a.wins || b.pf - a.pf; });
  return { perSeason: perSeason, allTime: allTime };
}

// ── Deterministic stats query engine ─────────────────────────────────────────
// Flattens every game (canonicalised handles) into one list the query engine
// reads from. Never lets the model do arithmetic — JS computes, model narrates.
function flattenGames(history) {
  const seasons = (history && history.seasons) ? history.seasons : [];
  const rows = [];
  for (const s of seasons) {
    for (const g of (s.games || [])) {
      if (!(g.pa > 0 || g.pb > 0)) continue; // skip unplayed
      rows.push({ season: s.season, week: g.week, playoff: !!g.playoff, a: canonical(g.a), b: canonical(g.b), pa: g.pa, pb: g.pb });
    }
  }
  return rows;
}

// Executes a constrained query spec against flattened games. Pure + deterministic.
function runStatQuery(spec, games) {
  if (!spec || spec.type === 'none') return null;
  const regOnly = spec.regularSeasonOnly !== false; // default true
  const seasonSet = Array.isArray(spec.seasons) && spec.seasons.length ? new Set(spec.seasons.map(String)) : null;
  const mgrSet = Array.isArray(spec.managers) && spec.managers.length ? new Set(spec.managers.map(canonical)) : null;

  let pool = games.filter(function(g) {
    if (regOnly && g.playoff) return false;
    if (seasonSet && !seasonSet.has(String(g.season))) return false;
    return true;
  });

  if (spec.type === 'headToHead') {
    // Build record between every ordered pair, then filter to requested managers.
    const rec = {};
    function cell(x, y) { const k = x + '|' + y; if (!rec[k]) rec[k] = { manager: x, opponent: y, wins: 0, losses: 0, ties: 0, pf: 0, pa: 0, games: 0 }; return rec[k]; }
    for (const g of pool) {
      const A = cell(g.a, g.b), B = cell(g.b, g.a);
      A.pf += g.pa; A.pa += g.pb; A.games++;
      B.pf += g.pb; B.pa += g.pa; B.games++;
      if (g.pa > g.pb) { A.wins++; B.losses++; }
      else if (g.pb > g.pa) { B.wins++; A.losses++; }
      else { A.ties++; B.ties++; }
    }
    let rows = Object.values(rec);
    if (mgrSet) {
      if (mgrSet.size === 2) {
        const [m1, m2] = Array.from(mgrSet);
        rows = rows.filter(function(r) { return (r.manager === m1 && r.opponent === m2) || (r.manager === m2 && r.opponent === m1); });
      } else {
        rows = rows.filter(function(r) { return mgrSet.has(r.manager); });
      }
    }
    rows.forEach(function(r) { r.pf = Math.round(r.pf * 100) / 100; r.pa = Math.round(r.pa * 100) / 100; r.winPct = r.games ? Math.round(r.wins / r.games * 1000) / 1000 : 0; });
    rows.sort(function(x, y) { return x.manager.localeCompare(y.manager) || y.games - x.games; });
    return { type: 'headToHead', rows: rows };
  }

  if (spec.type === 'totals') {
    const acc = {};
    function row(m) { if (!acc[m]) acc[m] = { manager: m, games: 0, wins: 0, losses: 0, ties: 0, pf: 0, pa: 0, high: 0, low: Infinity }; return acc[m]; }
    for (const g of pool) {
      if (mgrSet && !mgrSet.has(g.a) && !mgrSet.has(g.b)) continue;
      const A = row(g.a), B = row(g.b);
      A.games++; B.games++;
      A.pf += g.pa; A.pa += g.pb; B.pf += g.pb; B.pa += g.pa;
      A.high = Math.max(A.high, g.pa); A.low = Math.min(A.low, g.pa);
      B.high = Math.max(B.high, g.pb); B.low = Math.min(B.low, g.pb);
      if (g.pa > g.pb) { A.wins++; B.losses++; } else if (g.pb > g.pa) { B.wins++; A.losses++; } else { A.ties++; B.ties++; }
    }
    let rows = Object.values(acc);
    if (mgrSet) rows = rows.filter(function(r) { return mgrSet.has(r.manager); });
    rows.forEach(function(r) {
      r.pf = Math.round(r.pf * 100) / 100; r.pa = Math.round(r.pa * 100) / 100;
      r.avg = r.games ? Math.round(r.pf / r.games * 100) / 100 : 0;
      if (r.low === Infinity) r.low = 0;
      r.winPct = r.games ? Math.round(r.wins / r.games * 1000) / 1000 : 0;
    });
    rows.sort(function(x, y) { return y.wins - x.wins || y.pf - x.pf; });
    return { type: 'totals', rows: rows };
  }

  if (spec.type === 'gameList') {
    let rows = pool.slice();
    if (mgrSet) rows = rows.filter(function(g) { return mgrSet.has(g.a) || mgrSet.has(g.b); });
    const by = spec.sortBy || 'combined';
    function metric(g) {
      if (by === 'margin') return Math.abs(g.pa - g.pb);
      if (by === 'high') return Math.max(g.pa, g.pb);
      if (by === 'low') return Math.min(g.pa, g.pb);
      return g.pa + g.pb; // combined
    }
    const order = spec.order === 'asc' ? 1 : -1;
    rows.sort(function(x, y) { return (metric(x) - metric(y)) * order; });
    const limit = Math.min(spec.limit || 10, 25);
    return { type: 'gameList', rows: rows.slice(0, limit) };
  }

  return null;
}

// Asks the model to translate a question into a query spec (JSON only).
async function planStatQuery(query, messages) {
  const handles = Object.keys(NAMES);
  const nameLines = handles.map(function(h) { return h + '=' + distinctName(h); }).join(', ');
  const planner = [
    'You translate a fantasy-football question into a JSON query spec. Output ONLY valid JSON, nothing else.',
    'Manager handles (use these exact strings in "managers"): ' + nameLines + '. Note benjlev=Lev, sanfbe=Sanford, allyl900 maps to AlastairL.',
    'Schema:',
    '{ "type": "headToHead" | "totals" | "gameList" | "none",',
    '  "managers": [handle, ...]   // optional; for headToHead between two, list both',
    '  "seasons": ["2023", ...]    // optional; omit for all-time',
    '  "regularSeasonOnly": true,  // default true; set false to include playoffs',
    '  "sortBy": "margin"|"high"|"low"|"combined",  // gameList only',
    '  "order": "desc"|"asc",      // gameList only',
    '  "limit": 10 }               // gameList only',
    'Rules: head-to-head / nemesis / "who beats whom" -> headToHead. Records/standings/win totals/points -> totals. "biggest/closest/highest game" -> gameList. If the question is not a numeric data lookup (opinion, definition, lore) -> {"type":"none"}.',
  ].join('\n');
  try {
    const raw = await claudeCall(messages.slice(-3), planner);
    const m = raw.match(/\{[\s\S]*\}/);
    if (!m) return { type: 'none' };
    return JSON.parse(m[0]);
  } catch (e) {
    return { type: 'none' };
  }
}

// Renders a query result into a deterministic context block the narrator reads.
function formatQueryResult(spec, result) {
  if (!result || !result.rows || !result.rows.length) return '';
  function nm(h) { return distinctName(h); }
  const lines = [];
  if (result.type === 'headToHead') {
    lines.push('Head-to-head records (regular season unless stated):');
    result.rows.forEach(function(r) { lines.push('- ' + nm(r.manager) + ' vs ' + nm(r.opponent) + ': ' + r.wins + '-' + r.losses + (r.ties ? '-' + r.ties : '') + ', PF ' + r.pf + ' / PA ' + r.pa + ' (' + r.games + ' games)'); });
  } else if (result.type === 'totals') {
    lines.push('Aggregate records:');
    result.rows.forEach(function(r) { lines.push('- ' + nm(r.manager) + ': ' + r.wins + '-' + r.losses + (r.ties ? '-' + r.ties : '') + ', PF ' + r.pf + ', avg ' + r.avg + ', high ' + r.high + ', low ' + r.low + ' (' + r.games + ' games)'); });
  } else if (result.type === 'gameList') {
    lines.push('Matching games:');
    result.rows.forEach(function(g) { lines.push('- ' + g.season + ' wk' + g.week + (g.playoff ? ' (playoff)' : '') + ': ' + nm(g.a) + ' ' + g.pa + ' – ' + g.pb + ' ' + nm(g.b)); });
  }
  return '══ DETERMINISTIC QUERY RESULT (authoritative — narrate ONLY these numbers, do not recompute) ══\n' + lines.join('\n');
}

function useLeagueData() {
  const [data, setData] = useState({ history: HISTORY_DATA, stats: STATS_DATA, rosters: ROSTERS_DATA, trades: TRADE_VALUES, alltime: ALLTIME_DATA, transactions: TRANSACTIONS_DATA, live: false });
  useEffect(function() {
    let cancelled = false;
    (async function() {
      for (let i = 0; i < DATA_SOURCES.length; i++) {
        try {
          const urls = DATA_SOURCES[i];
          const keys = Object.keys(urls);
          const fetched = await Promise.all(keys.map(function(k) {
            return fetch(urls[k] + BUST).then(function(r) { if (!r.ok) throw new Error(r.status); return r.json(); });
          }));
          const result = { live: true };
          keys.forEach(function(k, idx) { result[k] = fetched[idx]; });
          if (!cancelled) setData(result);
          return;
        } catch (e) { /* try next */ }
      }
    })();
    return function() { cancelled = true; };
  }, []);
  return data;
}

function useLore(active) {
  const [lore, setLore] = useState({ master: '', archive: [], quotes: [], ready: false });
  const fetchedRef = useRef(false);
  useEffect(function() {
    if (!active || fetchedRef.current) return;
    fetchedRef.current = true;
    let cancelled = false;
    (async function() {
      for (let i = 0; i < LORE_SOURCES.length; i++) {
        try {
          const urls = LORE_SOURCES[i];
          const [mData, aData, qData] = await Promise.all([
            fetch(urls.master + BUST).then(function(r) { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch(urls.archive + BUST).then(function(r) { if (!r.ok) throw new Error(r.status); return r.json(); }),
            fetch(urls.quotes + BUST).then(function(r) { if (!r.ok) throw new Error(r.status); return r.json(); }),
          ]);
          if (!cancelled) setLore({ master: mData.text || '', archive: aData || [], quotes: qData || [], ready: true });
          return;
        } catch(e) { /* try next source */ }
      }
    })();
    return function() { cancelled = true; };
  }, [active]);
  return lore;
}

function retrieveLore(query, archive, quotes) {
  const MAX = 3500;
  if (!query || (!archive.length && !quotes.length)) return '';
  const STOP = new Set(['the','a','an','is','are','was','were','be','been','have','has','had','do','does','did','will','would','could','should','may','might','can','and','but','or','not','so','yet','no','only','than','too','very','just','now','for','with','about','from','into','before','after','out','over','under','then','once','in','on','at','by','of','to','up','down','off','me','my','we','our','you','your','he','his','she','her','it','its','they','them','their','what','which','who','this','that','these','those','some','any','all','when','where','how','why']);
  const tokens = query.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').split(/\s+/).filter(function(t) { return t.length > 2 && !STOP.has(t); });
  if (!tokens.length) return '';

  const PMAP = {
    dan:'Daniel Polak', daniel:'Daniel Polak', polak:'Daniel Polak', commissioner:'Daniel Polak',
    saul:'Saul Freedman', freedman:'Saul Freedman', goat:'Saul Freedman',
    alastair:'Alastair Livingston', ally:'Alastair Livingston', livingston:'Alastair Livingston',
    gideon:'Gideon Sakofsky', sac:'Gideon Sakofsky', sakofsky:'Gideon Sakofsky',
    josh:'Josh Gaon', gaon:'Josh Gaon', trader:'Josh Gaon',
    jamie:'Jamie Kay', kay:'Jamie Kay', doctor:'Jamie Kay',
    lev:'Benjy Levey', levey:'Benjy Levey', autodraft:'Benjy Levey',
    sanford:'Benjy Sanford', snaff:'Benjy Sanford', darkwa:'Benjy Sanford',
  };
  const mentioned = new Set();
  tokens.forEach(function(t) { if (PMAP[t]) mentioned.add(PMAP[t]); });

  const parts = [];

  // Matching quote lines for mentioned people
  if (quotes.length && mentioned.size) {
    quotes.forEach(function(chunk) {
      if (mentioned.has(chunk.person)) {
        const sample = (chunk.lines || []).slice(0, 10).join('\n');
        if (sample) parts.push('QUOTES — ' + chunk.person + ':\n' + sample);
      }
    });
  }

  // Score archive chunks
  if (archive.length) {
    const yearMatch = query.match(/\b(201[7-9]|202[0-6])\b/);
    const scored = archive.map(function(chunk) {
      const haystack = (chunk.title + ' ' + chunk.text).toLowerCase();
      let score = tokens.reduce(function(s, t) { return s + (haystack.split(t).length - 1); }, 0);
      if (yearMatch && String(chunk.year) === yearMatch[1]) score += 8;
      mentioned.forEach(function(nm) {
        score += (haystack.split(nm.split(' ')[0].toLowerCase()).length - 1) * 2;
      });
      return { chunk: chunk, score: score };
    });
    scored.sort(function(a, b) { return b.score - a.score; });
    scored.slice(0, 2).forEach(function(x) {
      if (x.score > 1) parts.push('ARCHIVE — ' + x.chunk.title + ':\n' + x.chunk.text.slice(0, 1800));
    });
  }

  return parts.join('\n\n---\n\n').slice(0, MAX);
}

function useViewport() {
  const [keyboardOpen, setKb] = useState(false);
  useEffect(function() {
    const vv = window.visualViewport;
    function apply() {
      const h = vv ? vv.height : window.innerHeight;
      document.documentElement.style.setProperty('--app-h', h + 'px');
      setKb((window.innerHeight - h) > 120);
    }
    apply();
    if (vv) { vv.addEventListener('resize', apply); vv.addEventListener('scroll', apply); }
    window.addEventListener('resize', apply);
    window.addEventListener('orientationchange', apply);
    return function() {
      if (vv) { vv.removeEventListener('resize', apply); vv.removeEventListener('scroll', apply); }
      window.removeEventListener('resize', apply);
      window.removeEventListener('orientationchange', apply);
    };
  }, []);
  return { keyboardOpen: keyboardOpen };
}

function renderInline(str, kb) {
  return str.split(/(\*\*[^*]+\*\*)/g).map(function(p, i) {
    if (/^\*\*[^*]+\*\*$/.test(p)) return React.createElement('strong', { key: kb + '-' + i }, p.slice(2, -2));
    return React.createElement('span', { key: kb + '-' + i }, p);
  });
}
function splitRow(line) {
  return line.replace(/^\s*\|/, '').replace(/\|\s*$/, '').split('|').map(function(c) { return c.trim(); });
}
function MarkdownMessage(props) {
  const lines = String(props.text || '').split('\n');
  const out = [];
  let i = 0, key = 0;
  function isRow(l) { return /^\s*\|.*\|\s*$/.test(l); }
  function isSep(l) { return /^\s*\|[\s:|-]+\|\s*$/.test(l); }
  while (i < lines.length) {
    const line = lines[i];
    if (isRow(line) && i + 1 < lines.length && isSep(lines[i + 1])) {
      const header = splitRow(line);
      i += 2;
      const rows = [];
      while (i < lines.length && isRow(lines[i]) && !isSep(lines[i])) { rows.push(splitRow(lines[i])); i++; }
      const tbl = React.createElement('div', { key: key++, style: { overflowX: 'auto', margin: '8px 0' } },
        React.createElement('table', { className: 'md-table' },
          React.createElement('thead', null, React.createElement('tr', null, header.map(function(h, j) { return React.createElement('th', { key: j }, renderInline(h, 'h' + j)); }))),
          React.createElement('tbody', null, rows.map(function(r, ri) { return React.createElement('tr', { key: ri }, r.map(function(c, ci) { return React.createElement('td', { key: ci }, renderInline(c, ri + '-' + ci)); })); }))
        )
      );
      out.push(tbl);
      continue;
    }
    if (line.trim() === '') { i++; continue; }
    const para = [];
    while (i < lines.length && lines[i].trim() !== '' && !(isRow(lines[i]) && i + 1 < lines.length && isSep(lines[i + 1]))) { para.push(lines[i]); i++; }
    const children = [];
    for (let li = 0; li < para.length; li++) {
      const inlined = renderInline(para[li], key + '-' + li);
      inlined.forEach(function(el) { children.push(el); });
      if (li < para.length - 1) children.push(React.createElement('br', { key: 'br-' + li }));
    }
    out.push(React.createElement('p', { key: key++, style: { margin: '0 0 7px', lineHeight: 1.55 } }, children));
  }
  return React.createElement(React.Fragment, null, out);
}

function ChatTab(props) {
  const { systemPrompt, chips, placeholder, errorMsg, intro, buildContext } = props;
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);
  const taRef = useRef(null);

  useEffect(function() { if (bottomRef.current) bottomRef.current.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);

  function autoResize() {
    const ta = taRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = Math.min(ta.scrollHeight, 120) + 'px';
  }

  async function send(text) {
    const t = (text || input).trim();
    if (!t || loading) return;
    const next = messages.concat([{ role: 'user', content: t }]);
    setMessages(next); setInput(''); setLoading(true);
    if (taRef.current) taRef.current.style.height = 'auto';
    try {
      const extra = buildContext ? await buildContext(t, next) : '';
      const fullPrompt = extra ? systemPrompt + '\n\n' + extra : systemPrompt;
      const raw = await claudeCall(next.filter(function(m) { return m.role === 'user' || m.role === 'assistant'; }), fullPrompt);
      const reply = raw.replace(/\[(FACT|MYTH|REAL|EVENT)\]/g, '').replace(/  +/g, ' ').trim();
      setMessages(function(p) { return p.concat([{ role: 'assistant', content: reply }]); });
    } catch (e) {
      const txt = (e && e.message === 'MODEL_ERROR') ? 'Model hiccup — try again.' : errorMsg;
      setMessages(function(p) { return p.concat([{ role: 'error', content: txt }]); });
    } finally { setLoading(false); }
  }

  const bubUser = { alignSelf: 'flex-end', background: 'linear-gradient(135deg,#6366f1,#4f46e5)', color: '#fff', borderRadius: '18px 18px 4px 18px', padding: '11px 15px', maxWidth: '82%', fontSize: 15, lineHeight: 1.5, whiteSpace: 'pre-wrap', boxShadow: '0 3px 14px rgba(99,102,241,0.3)' };
  const bubAsst = { alignSelf: 'flex-start', background: '#141e32', color: '#e8f1ff', border: '1px solid #24344e', borderLeft: '3px solid #6366f1', borderRadius: '4px 18px 18px 18px', padding: '12px 15px', maxWidth: '88%', fontSize: 15, lineHeight: 1.6 };
  const bubErr  = { alignSelf: 'flex-start', background: '#141e32', color: '#f59e0b', border: '1px solid #24344e', borderLeft: '3px solid #f59e0b', borderRadius: '4px 18px 18px 18px', padding: '12px 15px', maxWidth: '88%', fontSize: 15, whiteSpace: 'pre-wrap' };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: T.bg }}>
      <div style={{ display: 'flex', gap: 8, padding: '10px 14px', borderBottom: '1px solid ' + T.border, overflowX: 'auto', flexShrink: 0, background: T.panel }}>
        {chips.map(function(c, i) {
          return <button key={i} className="chip" onClick={function() { send(c); }} disabled={loading}>{c}</button>;
        })}
      </div>
      <div style={{ flexGrow: 1, overflowY: 'auto', padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
        {messages.length === 0 && !loading && (
          <div style={{ margin: 'auto', textAlign: 'center', color: T.faint, fontSize: 14, maxWidth: 300, lineHeight: 1.7, padding: '20px 8px' }}>{intro}</div>
        )}
        {messages.map(function(m, i) {
          if (m.role === 'assistant') return <div key={i} style={bubAsst}><MarkdownMessage text={m.content} /></div>;
          if (m.role === 'error') return <div key={i} style={bubErr}>{m.content}</div>;
          return <div key={i} style={bubUser}>{m.content}</div>;
        })}
        {loading && (
          <div style={bubAsst}>
            <span className="ld" /><span className="ld" /><span className="ld" />
          </div>
        )}
        <div ref={bottomRef} />
      </div>
      <div style={{ display: 'flex', gap: 8, padding: '10px 12px', borderTop: '1px solid ' + T.border, background: T.panel, flexShrink: 0 }}>
        <textarea ref={taRef} rows={1} value={input}
          onChange={function(e) { setInput(e.target.value); }}
          onInput={autoResize}
          onKeyDown={function(e) { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
          placeholder={placeholder}
          style={{ flex: 1, background: T.raised, color: T.text, border: '1px solid ' + T.borderHi, borderRadius: 11, padding: '12px 13px', fontSize: 16, resize: 'none', outline: 'none', lineHeight: 1.4 }}
        />
        <button onClick={function() { send(); }} disabled={loading || !input.trim()} className="send-btn" style={{ opacity: (loading || !input.trim()) ? 0.4 : 1 }}>SEND</button>
      </div>
    </div>
  );
}

function slimAlltime(d) {
  if (!d) return d;
  // weeklyScores (raw per-game scores) and h2hBySeason (covered by deterministic query layer)
  // are excluded to keep the system prompt within the artifact runtime's prompt budget.
  // records games have player-name arrays stripped — scores and teams are sufficient for narration.
  function stripGame(g) {
    if (!g || typeof g !== 'object') return g;
    const { as, bs, ab, bb, ...rest } = g;
    return rest;
  }
  const records = {};
  for (const [k, v] of Object.entries(d.records || {})) {
    records[k] = Array.isArray(v) ? v.map(stripGame) : stripGame(v);
  }
  const { weeklyScores, h2hBySeason, records: _r, ...rest } = d;
  return { ...rest, records };
}

function StatsTab(props) {
  const { historyData, statsData, alltimeData, transactionsData, loreMaster } = props;
  const analytics = useMemo(function() { return computeAnalytics(historyData); }, [historyData]);
  const games = useMemo(function() { return flattenGames(historyData); }, [historyData]);
  const loreCtx = loreMaster
    ? '\n\nLEAGUE CONTEXT (names, champions, glossary — for resolving names only, NOT for inventing stats):\n' + loreMaster.slice(0, 2500)
    : '';
  // Narration prompt: deterministic pre-computed tables ONLY — no raw game dump,
  // so the model cannot do its own (error-prone) win/loss arithmetic. Anything
  // not in the tables arrives via the DETERMINISTIC QUERY RESULT block (buildContext).
  const sp = 'You are the statistician for the Borehamwood Plancy League. Answer ONLY from the data below — NEVER compute or invent numbers yourself.\n\n'
    + 'CRITICAL: All win/loss/points figures must be read verbatim from the pre-computed tables or the DETERMINISTIC QUERY RESULT block. Do NOT add up games or derive records yourself — if a number is not given to you, say you do not have it rather than estimate.\n\n'
    + 'NAMES: always use real NAME not Sleeper handle. TWO BENJYS: benjlev=Lev, sanfbe=Sanford when both appear. Alastair\'s allyl900 account is the same person.\n\n'
    + 'ANSWER FORMAT: 1) ONE short sentence on method. 2) GitHub Markdown table for any ranking. 3) At most ONE closing sentence. No preamble.\n\n'
    + 'METRICS: allPlay, allPlayWinPct, expectedWins, luck (positive=lucky, negative=unlucky), consistencySD, avgScore, high, low, pf, pa, record. nemesis=worst H2H opponent, bunny=best H2H opponent (both pre-computed, symmetric — trust them).\n\n'
    + 'EXTENDED TABLES IN alltime.json — use these for deeper questions:\n'
    + '  consistencyStats[manager].allTime: {avg, stdDev, high, low, games} — all-time scoring consistency\n'
    + '  consistencyStats[manager].perSeason[year]: same breakdown per season\n'
    + '  personalRecords[manager]: {highWeek, lowWeek, biggestWin, biggestLoss} — personal scoring milestones\n'
    + '  playoffRecords[manager]: {wins, losses, pf, pa, appearances} — playoff-only record\n'
    + '  seasonalTrends[manager]: [{season, pf, wins, losses, ppg, rank}] — season-by-season performance\n'
    + '  luckScores[manager]: [{season, actualWins, expectedWins, luckScore}] — luck per season\n'
    + '  positionalStrengths[manager][season]: {QB, RB, WR, TE, K, DEF, games} — avg pts by position per game\n'
    + '  benchWasteTop: top 20 games with most bench pts left on field\n'
    + '  h2hBySeason: use the deterministic query layer (ask with "H2H in 2023" etc.) — not included in prompt to save space\n\n'
    + 'TRADE DATA: transactions array has every completed trade: {season, week, managerA, managerB, aReceives[], bReceives[]}. Use for trade history questions.'
    + loreCtx
    + '\n\nANALYTICS (all-play, luck, consistency — pre-computed):\n' + JSON.stringify(analytics)
    + '\n\nALL-TIME RECORDS, H2H MATRIX, NEMESIS/BUNNY (pre-computed, authoritative):\n' + JSON.stringify(slimAlltime(alltimeData))
    + '\n\nTRADE HISTORY:\n' + JSON.stringify(transactionsData)
    + '\n\nCURRENT SEASON SUMMARY:\n' + JSON.stringify({ league: statsData && statsData.league, season: statsData && statsData.season, standings: statsData && statsData.standings, headToHead: statsData && statsData.headToHead, extremes: statsData && statsData.extremes });

  // buildContext: deterministic query layer. Plan → execute in JS → inject result.
  async function buildContext(query) {
    try {
      const spec = await planStatQuery(query, [{ role: 'user', content: query }]);
      const result = runStatQuery(spec, games);
      return formatQueryResult(spec, result);
    } catch (e) { return ''; }
  }

  return <ChatTab systemPrompt={sp} buildContext={buildContext} chips={['Unluckiest manager?', 'Best playoff record?', 'Most consistent scorer?', 'Biggest bench disasters?']} placeholder="Message…" errorMsg="Something went wrong — try again." intro="The record book — career records, luck ratings, playoff history, consistency. Ask about personal bests, positional strengths, or any head-to-head." />;
}

function BanterTab(props) {
  const { historyData, statsData, alltimeData, lore } = props;

  const banterPrompt = useMemo(function() {
    const rule = [
      '══ PRIME DIRECTIVE ══',
      'You are the resident wind-up merchant of the Borehamwood Plancy League.',
      'STYLE: ESPN mock-grandeur, bone-dry British wit, mock gravity. Punchy 3-5 sentences. Lean on Jewish/Borehamwood texture. Sign off big beats with "a hearty hearty mazel tov."',
      'Never be cruel — mockery is the love language. Never invent statistics.',
      '',
      'CRITICAL OUTPUT RULE: NEVER print tag labels like [FACT], [MYTH], [REAL], or [EVENT] in your response. These are internal reasoning cues only — your output must read as natural chat, no square-bracket annotations of any kind.',
      '',
      'VERIFICATION RULE: Before stating any league result, score, record, or season outcome, verify it against RAW HISTORY and CURRENT SEASON below. If the event predates our data (pre-2023), you may reference it but must treat it as unverified lore rather than confirmed fact. Never contradict the data.',
      '',
      '══ LORE MASTER ══',
    ].join('\n');

    const dataSection = '\n\n══ VERIFIED DATA (check all facts here first) ══'
      + '\n\nRAW HISTORY:\n' + JSON.stringify(historyData)
      + '\n\nCURRENT SEASON:\n' + JSON.stringify(statsData)
      + '\n\nALL-TIME RECORDS:\n' + JSON.stringify(alltimeData);

    if (lore.master) return rule + '\n' + lore.master + dataSection;

    // Fallback when lore files haven't loaded yet
    return rule + '\nChampions (most recent first): Alastair Livingston 2025 (first legit Plancey — beat Polak in final), Saul Freedman 2024+2023+2021+2017 (4 belts, the GOAT), Benjy Levey 2022, Jamie Kay 2020, Josh Gaon 2019, Gideon Sakofsky 2018, Alastair Livingston inaugural (asterisked).'
      + '\nThe Miriam = wooden spoon. Sanford = king of the Miriam. Lev = autodraft legend ("Does it auto-draft automatically?"). Dan = Commissioner/narrator. Gideon lives in Israel (4am watches). The Plancey = championship belt named after Rabbi Alan Plancey.'
      + '\nTWO BENJYS: benjlev=Lev, sanfbe=Sanford. allyl900=Alastair.'
      + '\nNAME MAP: ' + JSON.stringify(NAMES)
      + dataSection;
  }, [lore.master, historyData, statsData, alltimeData]);

  function buildContext(query) {
    if (!lore.ready) return '';
    const lore_ctx = retrieveLore(query, lore.archive, lore.quotes);
    return lore_ctx ? '--- RETRIEVED LORE ---\n' + lore_ctx : '';
  }

  return <ChatTab
    systemPrompt={banterPrompt}
    buildContext={buildContext}
    chips={['Roast the 2025 champion', 'Most cursed manager?', "This week's smack bulletin", 'Roast Lev']}
    placeholder="Message…"
    errorMsg="Blimey — give it another go."
    intro="Pull up a chair. Ask for a roast, a smack-talk bulletin, or just stir the pot."
  />;
}

function normalizeName(str) { return str.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim(); }

function TradeGrader(props) {
  const { rostersData, tradeValues } = props;
  const teamKeys = useMemo(function() { return Object.keys(rostersData || {}); }, [rostersData]);
  const [teamA, setTeamA] = useState(teamKeys[0] || '');
  const [teamB, setTeamB] = useState(teamKeys[1] || '');
  const [sideAText, setSideAText] = useState('');
  const [sideBText, setSideBText] = useState('');
  const [result, setResult] = useState(null);
  const [verdict, setVerdict] = useState(null);
  const [vLoading, setVL] = useState(false);
  const [vError, setVE] = useState(false);
  const [showWaiver, setShowWaiver] = useState(true);

  useEffect(function() {
    if (document.getElementById('tg-spin')) return;
    const s = document.createElement('style');
    s.id = 'tg-spin';
    s.textContent = '@keyframes tg-spin{to{transform:rotate(360deg)}}';
    document.head.appendChild(s);
  }, []);

  const { idMap, nameMap } = useMemo(function() {
    const id = new Map(), nm = new Map();
    (tradeValues || []).forEach(function(item) {
      const p = item.player, val = item.redraftValue || 0;
      if (p.sleeperId) id.set(p.sleeperId, { value: val, officialName: p.name, position: p.position });
      nm.set(normalizeName(p.name), { value: val, sleeperId: p.sleeperId, officialName: p.name, position: p.position });
    });
    return { idMap: id, nameMap: nm };
  }, [tradeValues]);

  const waiverByPos = useMemo(function() {
    const rostered = new Set(Object.values(rostersData || {}).reduce(function(acc, team) { return acc.concat(team.map(function(p) { return p.id; })); }, []));
    const avail = (tradeValues || []).filter(function(x) { return x.player.sleeperId && !rostered.has(x.player.sleeperId); });
    const byPos = {};
    avail.forEach(function(p) {
      const pos = p.player.position;
      if (!byPos[pos]) byPos[pos] = [];
      if (byPos[pos].length < 5) byPos[pos].push(p);
    });
    return byPos;
  }, [rostersData, tradeValues]);

  function lookupPlayer(txt) {
    const n = normalizeName(txt);
    if (nameMap.has(n)) { const e = nameMap.get(n); return { found: true, value: e.value, officialName: e.officialName, position: e.position }; }
    for (const [k, e] of nameMap) { if (k.includes(n) || n.includes(k)) return { found: true, value: e.value, officialName: e.officialName, position: e.position }; }
    return { found: false, value: 0, officialName: txt, position: null };
  }

  function gradeTrade() {
    function parse(txt) { return txt.split('\n').map(function(l) { return l.trim(); }).filter(Boolean).map(function(line) { return Object.assign({ input: line }, lookupPlayer(line)); }); }
    const sA = parse(sideAText), sB = parse(sideBText);
    const tA = sA.reduce(function(s, p) { return s + p.value; }, 0);
    const tB = sB.reduce(function(s, p) { return s + p.value; }, 0);
    const gap = Math.abs(tA - tB), gapPct = (gap / Math.max(tA, tB, 1)) * 100;
    const winner = gapPct < 5 ? 'even' : tA > tB ? 'A' : 'B';
    const tier = gapPct < 5 ? 'DEAD EVEN' : gapPct < 12 ? 'SLIGHT EDGE' : gapPct < 25 ? 'CLEAR WINNER' : 'LOPSIDED';
    const icon = gapPct < 5 ? '⚖️' : gapPct < 12 ? '📊' : gapPct < 25 ? '🏆' : '🚨';
    let addOns = [];
    if (winner !== 'even') {
      const wTeam = winner === 'A' ? teamA : teamB;
      const wSide = winner === 'A' ? sA : sB;
      const exclude = new Set(wSide.map(function(p) { return p.officialName; }));
      addOns = ((rostersData || {})[wTeam] || [])
        .map(function(rp) { return { name: idMap.has(rp.id) ? idMap.get(rp.id).officialName : rp.name, value: idMap.has(rp.id) ? idMap.get(rp.id).value : 0 }; })
        .filter(function(rp) { return !exclude.has(rp.name) && rp.value > 0; })
        .sort(function(a, b) { return Math.abs(a.value - gap) - Math.abs(b.value - gap); })
        .slice(0, 3);
    }
    const positions = new Set(sA.concat(sB).map(function(p) { return p.position; }).filter(Boolean));
    const waiverContext = {};
    positions.forEach(function(pos) { waiverContext[pos] = (waiverByPos[pos] || []).slice(0, 3); });
    setResult({ sA: sA, sB: sB, tA: tA, tB: tB, winner: winner, tier: tier, icon: icon, gap: gap, gapPct: gapPct, addOns: addOns, waiverContext: waiverContext });
    setVerdict(null); setVE(false);
  }

  async function getVerdict() {
    if (!result) return;
    setVL(true); setVE(false); setVerdict(null);
    const sys = "You are the wind-up merchant of the Borehamwood Plancy League. Quick funny verdict in 2-4 sentences. Bone-dry British banter. Use real names not team names. Numbers are computed — do NOT recalculate.";
    const margin = result.winner === 'even' ? 'Even.' : ('Side ' + result.winner + ' wins by ' + result.gap.toFixed(0) + ' (' + result.gapPct.toFixed(0) + '%)');
    const addOnStr = result.addOns.length ? ' Suggested add-on: ' + result.addOns.map(function(a) { return a.name; }).join(' or ') + '.' : '';
    const sAStr = result.sA.map(function(p) { return p.officialName + '(' + p.value + ')'; }).join(', ');
    const sBStr = result.sB.map(function(p) { return p.officialName + '(' + p.value + ')'; }).join(', ');
    const msg = 'Trade:\nSide A (' + teamLabel(teamA) + ') gives: ' + sAStr + ' — Total ' + result.tA + '\nSide B (' + teamLabel(teamB) + ') gives: ' + sBStr + ' — Total ' + result.tB + '\nVerdict: ' + result.tier + '. ' + margin + addOnStr;
    try {
      const r = await claudeCall([{ role: 'user', content: msg }], sys);
      setVerdict(r);
    } catch (e) { setVE(true); }
    finally { setVL(false); }
  }

  const teamOpts = teamKeys.map(function(k) { return <option key={k} value={k}>{teamLabel(k)}</option>; });
  const winA = result && result.winner === 'A';
  const winB = result && result.winner === 'B';
  const POSColors = { QB: '#ff7a1a', RB: '#10b981', WR: '#60a5fa', TE: '#a855f7', K: '#888', DEF: '#c44' };
  const spin = { width: 14, height: 14, border: '2px solid ' + T.amber, borderTopColor: 'transparent', borderRadius: '50%', display: 'inline-block', animation: 'tg-spin 0.8s linear infinite' };

  return (
    <div style={{ background: T.bg, color: T.text, overflowY: 'auto', height: '100%', boxSizing: 'border-box' }}>
      <div style={{ borderBottom: '1px solid ' + T.border, background: T.panel }}>
        <button onClick={function() { setShowWaiver(function(v) { return !v; }); }} style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '11px 15px', background: 'none', border: 'none', color: T.dim, cursor: 'pointer', fontSize: 12.5, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase' }}>
          <span>Waiver Wire <span style={{ color: T.faint, fontSize: 11, fontWeight: 400 }}>(top available by position)</span></span>
          <span style={{ fontSize: 10, color: T.faint }}>{showWaiver ? '▲ hide' : '▼ show'}</span>
        </button>
        {showWaiver && (
          <div style={{ padding: '0 13px 13px', display: 'flex', flexWrap: 'wrap', gap: 8 }}>
            {['QB', 'RB', 'WR', 'TE'].map(function(pos) {
              const players = waiverByPos[pos] || [];
              if (!players.length) return null;
              return (
                <div key={pos} style={{ background: T.raised, border: '1px solid ' + T.border, borderTop: '2px solid ' + (POSColors[pos] || T.border), borderRadius: '3px 3px 9px 9px', padding: '9px 11px', minWidth: 120, flex: '1 1 120px', maxWidth: 170 }}>
                  <div style={{ color: POSColors[pos] || T.dim, fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', marginBottom: 6 }}>{pos}</div>
                  {players.map(function(p, i) {
                    return (
                      <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12.5, padding: '3px 0', borderBottom: i < players.length - 1 ? '1px solid ' + T.border : 'none' }}>
                        <span style={{ color: T.text }}>{p.player.name}</span>
                        <span style={{ color: T.dim, fontSize: 11.5 }}>{p.redraftValue.toLocaleString()}</span>
                      </div>
                    );
                  })}
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div style={{ padding: 15 }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 11 }}>
          {[{ side: 'A', team: teamA, setTeam: setTeamA, text: sideAText, setText: setSideAText, accent: T.blue },
            { side: 'B', team: teamB, setTeam: setTeamB, text: sideBText, setText: setSideBText, accent: T.indigo }].map(function(cfg) {
            return (
              <div key={cfg.side} style={{ background: T.panel, border: '1px solid ' + T.border, borderTop: '3px solid ' + cfg.accent, borderRadius: '4px 4px 12px 12px', padding: 13, flex: 1, minWidth: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 9 }}>
                  <span style={{ background: cfg.accent, color: '#fff', fontWeight: 700, fontSize: 12, width: 20, height: 20, borderRadius: 5, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{cfg.side}</span>
                  <span style={{ color: T.dim, fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em' }}>{'Side ' + cfg.side + ' gives up'}</span>
                </div>
                <select value={cfg.team} onChange={function(e) { cfg.setTeam(e.target.value); }} style={{ background: T.raised, color: T.text, border: '1px solid ' + T.borderHi, borderRadius: 8, padding: 10, width: '100%', marginBottom: 8, fontSize: 16 }}>
                  {teamOpts}
                </select>
                <textarea value={cfg.text} onChange={function(e) { cfg.setText(e.target.value); }} placeholder={"One player per line\ne.g. Ja'Marr Chase"} style={{ background: T.raised, color: T.text, border: '1px solid ' + T.borderHi, borderRadius: 8, padding: 11, width: '100%', minHeight: 92, fontSize: 16, resize: 'vertical', boxSizing: 'border-box', lineHeight: 1.5 }} />
              </div>
            );
          })}
        </div>

        <button onClick={gradeTrade} disabled={!sideAText.trim() && !sideBText.trim()} style={{ width: '100%', background: (!sideAText.trim() && !sideBText.trim()) ? T.raised : 'linear-gradient(135deg,' + T.indigo + ',' + T.indigoDk + ')', color: (!sideAText.trim() && !sideBText.trim()) ? T.faint : '#fff', border: 'none', borderRadius: 12, padding: 15, fontSize: 15, fontWeight: 700, letterSpacing: '1.5px', textTransform: 'uppercase', cursor: 'pointer', marginTop: 12 }}>
          Grade This Trade
        </button>

        {result && (
          <div style={{ marginTop: 16 }}>
            <div style={{ background: T.panel, border: '1px solid ' + T.border, borderRadius: 14, overflow: 'hidden', marginBottom: 12 }}>
              <div style={{ display: 'flex' }}>
                <div style={{ flex: 1, padding: '15px 10px', textAlign: 'center', background: winA ? 'rgba(16,185,129,0.08)' : 'transparent', borderRight: '1px solid ' + T.border }}>
                  <div style={{ fontSize: 10, color: T.faint, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 4 }}>SIDE A</div>
                  <div style={{ fontWeight: 700, fontSize: 32, color: winA ? T.green : T.text, lineHeight: 1 }}>{result.tA.toLocaleString()}</div>
                  {winA && <div style={{ fontSize: 10, color: T.green, fontWeight: 700, marginTop: 3, textTransform: 'uppercase' }}>▲ WINS</div>}
                </div>
                <div style={{ flex: 1, padding: '15px 10px', textAlign: 'center', background: winB ? 'rgba(16,185,129,0.08)' : 'transparent', borderLeft: '1px solid ' + T.border }}>
                  <div style={{ fontSize: 10, color: T.faint, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 4 }}>SIDE B</div>
                  <div style={{ fontWeight: 700, fontSize: 32, color: winB ? T.green : T.text, lineHeight: 1 }}>{result.tB.toLocaleString()}</div>
                  {winB && <div style={{ fontSize: 10, color: T.green, fontWeight: 700, marginTop: 3, textTransform: 'uppercase' }}>▲ WINS</div>}
                </div>
              </div>
              <div style={{ textAlign: 'center', padding: '10px 0', borderTop: '1px solid ' + T.border, background: T.panel2 }}>
                <span style={{ fontSize: 20 }}>{result.icon}</span>
                <span style={{ fontWeight: 800, fontSize: 12.5, color: T.amber, letterSpacing: '0.04em', marginLeft: 8 }}>{result.tier}</span>
                {result.winner !== 'even' && <span style={{ fontSize: 10.5, color: T.dim, marginLeft: 8 }}>{'by ' + result.gap.toLocaleString() + ' (' + result.gapPct.toFixed(0) + '%)'}</span>}
              </div>
            </div>

            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 11, marginBottom: 12 }}>
              {[{ side: 'A', players: result.sA, team: teamA, accent: T.blue }, { side: 'B', players: result.sB, team: teamB, accent: T.indigo }].map(function(cfg) {
                return (
                  <div key={cfg.side} style={{ flex: 1, minWidth: 140, background: T.panel, border: '1px solid ' + T.border, borderRadius: 11, padding: '11px 13px' }}>
                    <div style={{ color: cfg.accent, fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>{teamLabel(cfg.team) + ' gives'}</div>
                    {cfg.players.length ? cfg.players.map(function(p, i) {
                      return (
                        <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '5px 0', borderBottom: '1px solid ' + T.border, fontSize: 13.5 }}>
                          <span style={{ color: p.found ? T.text : T.amber }}>{p.found ? p.officialName : p.input + ' ⚠'}</span>
                          <span style={{ color: p.found ? T.dim : T.amber, fontSize: 12.5, marginLeft: 8, fontWeight: 700 }}>{p.found ? p.value.toLocaleString() : 'no match'}</span>
                        </div>
                      );
                    }) : <div style={{ color: T.faint, fontSize: 12 }}>—</div>}
                  </div>
                );
              })}
            </div>

            {result.winner !== 'even' && result.addOns.length > 0 && (
              <div style={{ background: T.panel, border: '1px solid ' + T.border, borderLeft: '3px solid ' + T.amber, borderRadius: '4px 11px 11px 4px', padding: '11px 13px', marginBottom: 12 }}>
                <div style={{ color: T.amber, fontSize: 11, marginBottom: 6, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{'To balance, ' + teamLabel(result.winner === 'A' ? teamA : teamB) + ' could add'}</div>
                {result.addOns.map(function(a, i) {
                  return <div key={i} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13.5, padding: '3px 0' }}><span>{a.name}</span><span style={{ color: T.dim }}>{a.value.toLocaleString()}</span></div>;
                })}
              </div>
            )}

            {Object.keys(result.waiverContext).length > 0 && (
              <div style={{ background: T.panel, border: '1px solid ' + T.border, borderRadius: 11, padding: '11px 13px', marginBottom: 12 }}>
                <div style={{ color: T.dim, fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 8 }}>Waiver alternatives for traded positions</div>
                {Object.keys(result.waiverContext).map(function(pos) {
                  const players = result.waiverContext[pos];
                  return (
                    <div key={pos} style={{ marginBottom: 8 }}>
                      <span style={{ color: POSColors[pos] || T.dim, fontSize: 11, fontWeight: 700, textTransform: 'uppercase' }}>{pos + ': '}</span>
                      {players.map(function(p, i) {
                        return <span key={i} style={{ fontSize: 13, color: T.text }}>{p.player.name + ' '}<span style={{ color: T.dim, fontSize: 12 }}>{'(' + p.redraftValue.toLocaleString() + ')'}</span>{i < players.length - 1 ? <span style={{ color: T.faint }}> · </span> : ''}</span>;
                      })}
                    </div>
                  );
                })}
              </div>
            )}

            <button onClick={getVerdict} disabled={vLoading} style={{ width: '100%', background: T.panel, border: '1px solid ' + T.amber, color: T.amber, borderRadius: 11, padding: '13px 20px', fontSize: 13.5, fontWeight: 700, letterSpacing: '0.5px', textTransform: 'uppercase', cursor: vLoading ? 'default' : 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 9, opacity: vLoading ? 0.7 : 1 }}>
              {vLoading ? <span style={spin} /> : "🎙"} The Commissioner's Verdict
            </button>

            {(verdict || vError) && (
              <div style={{ background: T.panel2, border: '1px solid ' + (vError ? T.amber : T.border), borderLeft: '3px solid ' + (vError ? T.amber : T.indigo), borderRadius: '4px 12px 12px 4px', padding: 14, color: vError ? T.amber : T.text, marginTop: 10, fontSize: 14, lineHeight: 1.6 }}>
                {vError ? 'The Commissioner is unavailable — give it another go.' : <MarkdownMessage text={verdict} />}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Live Scores (spoiler-safe) ───────────────────────────────────────────────
// Calls the Sleeper API live from the browser. Sleeper now returns
// access-control-allow-origin:* so there is no CORS problem (the old claude.md
// rule against browser calls is stale). Pick an NFL week; NOTHING is revealed
// by default — you tap each player whose real-life game you've already watched,
// and only then does that player's fantasy score appear. The matchup totals are
// running sums of what YOU have revealed, never the true team total, so the
// games you haven't watched yet are never spoiled.
const SLEEPER_BASE = 'https://api.sleeper.app/v1';
const LIVE_USERNAME = 'AlastairL';
const NFL_WEEKS = Array.from({ length: 18 }, function(_, i) { return i + 1; });

// Flatten rosters.json ("Team (@handle)" -> [{id,name,pos}]) into id -> {name,pos}.
function buildPlayerIndex(rostersData) {
  const idx = {};
  Object.values(rostersData || {}).forEach(function(arr) {
    (arr || []).forEach(function(p) { if (p && p.id != null) idx[String(p.id)] = { name: p.name, pos: p.pos }; });
  });
  return idx;
}

async function sget(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error('Sleeper ' + r.status);
  return r.json();
}

function fmtPts(n) { return (Math.round((n || 0) * 100) / 100).toFixed(2); }

const POS_TINT = { QB: '#ff7a1a', RB: '#10b981', WR: '#60a5fa', TE: '#a855f7', K: '#94a3b8', DEF: '#f87171', FLEX: '#f59e0b' };

function LiveTab(props) {
  const { rostersData } = props;
  const playerIdx = useMemo(function() { return buildPlayerIndex(rostersData); }, [rostersData]);

  const [base, setBase] = useState(null);     // { leagueId, leagueName, season, slots, teamByRoster, myRosterId, liveWeek }
  const [baseErr, setBaseErr] = useState(false);
  const [week, setWeek] = useState(null);
  const [pairs, setPairs] = useState(null);   // [{ mid, entries:[entry,...] }]
  const [loadingM, setLoadingM] = useState(false);
  const [matchErr, setMatchErr] = useState(false);
  const [viewMid, setViewMid] = useState(null);
  const [revealed, setRevealed] = useState({}); // `${rosterId}:${slotIdx}` -> true

  useEffect(function() {
    if (document.getElementById('live-spin')) return;
    const s = document.createElement('style');
    s.id = 'live-spin';
    s.textContent = '@keyframes live-spin{to{transform:rotate(360deg)}}';
    document.head.appendChild(s);
  }, []);

  // 1) one-time: NFL state + active Plancy league + users + rosters
  useEffect(function() {
    let cancelled = false;
    (async function() {
      try {
        const state = await sget(SLEEPER_BASE + '/state/nfl');
        const user = await sget(SLEEPER_BASE + '/user/' + LIVE_USERNAME);
        let league = null, usedSeason = null;
        const years = [String(state.season), String(+state.season - 1), String(+state.season - 2)];
        for (let i = 0; i < years.length; i++) {
          const leagues = await sget(SLEEPER_BASE + '/user/' + user.user_id + '/leagues/nfl/' + years[i]);
          const lg = (leagues || []).find(function(l) { return /borehamwood|plancy/i.test(l.name); });
          if (lg) { league = lg; usedSeason = years[i]; break; }
        }
        if (!league) throw new Error('No Plancy league found');
        const [users, rosters] = await Promise.all([
          sget(SLEEPER_BASE + '/league/' + league.league_id + '/users'),
          sget(SLEEPER_BASE + '/league/' + league.league_id + '/rosters'),
        ]);
        const userByUid = {};
        users.forEach(function(u) { userByUid[u.user_id] = { handle: u.display_name, team: (u.metadata && u.metadata.team_name) || u.display_name }; });
        const teamByRoster = {};
        let myRosterId = null;
        rosters.forEach(function(r) {
          const u = userByUid[r.owner_id] || {};
          teamByRoster[r.roster_id] = {
            handle: u.handle || null,
            name: u.handle ? displayName(u.handle) : ('Roster ' + r.roster_id),
            team: u.team || '',
            isMe: r.owner_id === user.user_id,
          };
          if (r.owner_id === user.user_id) myRosterId = r.roster_id;
        });
        const slots = (league.roster_positions || []).filter(function(p) { return p !== 'BN'; });
        const isLive = String(state.season) === String(usedSeason) && state.week > 0;
        if (cancelled) return;
        setBase({ leagueId: league.league_id, leagueName: league.name, season: usedSeason, slots: slots, teamByRoster: teamByRoster, myRosterId: myRosterId, liveWeek: isLive ? state.week : null });
        setWeek(isLive ? state.week : 1);
      } catch (e) { if (!cancelled) setBaseErr(true); }
    })();
    return function() { cancelled = true; };
  }, []);

  // 2) (re)load matchups for the selected week — resets reveals so a new week starts hidden
  function loadMatchups(b, wk) {
    if (!b || !wk) return;
    setLoadingM(true); setMatchErr(false);
    sget(SLEEPER_BASE + '/league/' + b.leagueId + '/matchups/' + wk).then(function(raw) {
      const byMid = {};
      (raw || []).forEach(function(e) { if (e.matchup_id == null) return; (byMid[e.matchup_id] = byMid[e.matchup_id] || []).push(e); });
      const list = Object.keys(byMid).map(function(mid) { return { mid: mid, entries: byMid[mid] }; });
      let mine = null;
      list.forEach(function(p) { if (p.entries.some(function(e) { return e.roster_id === b.myRosterId; })) mine = p.mid; });
      setPairs(list);
      setViewMid(mine || (list[0] && list[0].mid) || null);
      setRevealed({});
      setLoadingM(false);
    }).catch(function() { setMatchErr(true); setLoadingM(false); });
  }

  useEffect(function() { if (base && week) loadMatchups(base, week); }, [base, week]);

  function startersOf(entry, b) {
    return b.slots.map(function(slot, i) {
      const pid = entry.starters && entry.starters[i];
      const empty = !pid || pid === '0';
      const info = !empty ? playerIdx[String(pid)] : null;
      const pts = (entry.starters_points && entry.starters_points[i] != null)
        ? entry.starters_points[i]
        : (entry.players_points && entry.players_points[pid]) || 0;
      return { slot: slot, i: i, pid: pid, empty: empty, name: info ? info.name : (empty ? null : 'Player ' + pid), pos: info ? info.pos : null, pts: pts };
    });
  }

  function revealedTotal(entry, rows) {
    return rows.reduce(function(s, row) { return revealed[entry.roster_id + ':' + row.i] && !row.empty ? s + row.pts : s; }, 0);
  }
  function revealedCount(entry, rows) {
    return rows.reduce(function(n, row) { return revealed[entry.roster_id + ':' + row.i] && !row.empty ? n + 1 : n; }, 0);
  }

  function toggle(key) {
    setRevealed(function(r) { const n = Object.assign({}, r); if (n[key]) delete n[key]; else n[key] = true; return n; });
  }
  function setAll(entry, rows, on) {
    setRevealed(function(r) {
      const n = Object.assign({}, r);
      rows.forEach(function(row) { if (row.empty) return; const k = entry.roster_id + ':' + row.i; if (on) n[k] = true; else delete n[k]; });
      return n;
    });
  }

  const spin = { width: 16, height: 16, border: '2px solid ' + T.amber, borderTopColor: 'transparent', borderRadius: '50%', display: 'inline-block', animation: 'live-spin 0.8s linear infinite' };

  // ── error / loading shells ──
  if (baseErr) {
    return (
      <div style={{ background: T.bg, color: T.text, height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, textAlign: 'center' }}>
        <div>
          <div style={{ fontSize: 30, marginBottom: 10 }}>📡</div>
          <div style={{ color: T.amber, fontWeight: 700, marginBottom: 6 }}>Couldn't reach Sleeper</div>
          <div style={{ color: T.dim, fontSize: 13 }}>Live scores need the Sleeper API. Check your connection and reopen this tab.</div>
        </div>
      </div>
    );
  }
  if (!base) {
    return (
      <div style={{ background: T.bg, color: T.text, height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 11 }}>
        <span style={spin} /><span style={{ color: T.dim, fontSize: 14 }}>Connecting to Sleeper…</span>
      </div>
    );
  }

  const pair = (pairs || []).find(function(p) { return p.mid === viewMid; });
  let entries = pair ? pair.entries.slice() : [];
  entries.sort(function(a, b) { return (a.roster_id === base.myRosterId ? -1 : 0) - (b.roster_id === base.myRosterId ? -1 : 0); });

  function teamLabelOf(rid) { const t = base.teamByRoster[rid] || {}; return t.team ? (t.name + ' · ' + t.team) : t.name; }

  return (
    <div style={{ background: T.bg, color: T.text, overflowY: 'auto', height: '100%', boxSizing: 'border-box' }}>
      {/* controls */}
      <div style={{ position: 'sticky', top: 0, zIndex: 2, background: T.panel, borderBottom: '1px solid ' + T.border, padding: '11px 14px' }}>
        <div style={{ display: 'flex', gap: 9, alignItems: 'center' }}>
          <div style={{ flex: '0 0 auto' }}>
            <div style={{ fontSize: 9.5, color: T.faint, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 3, fontWeight: 700 }}>Week</div>
            <select value={week} onChange={function(e) { setWeek(+e.target.value); }} style={{ background: T.raised, color: T.text, border: '1px solid ' + T.borderHi, borderRadius: 8, padding: '8px 10px', fontSize: 15 }}>
              {NFL_WEEKS.map(function(w) { return <option key={w} value={w}>{'Week ' + w + (w === base.liveWeek ? ' • now' : '')}</option>; })}
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 9.5, color: T.faint, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 3, fontWeight: 700 }}>Matchup</div>
            <select value={viewMid || ''} onChange={function(e) { setViewMid(e.target.value); }} style={{ background: T.raised, color: T.text, border: '1px solid ' + T.borderHi, borderRadius: 8, padding: '8px 10px', fontSize: 15, width: '100%' }}>
              {(pairs || []).map(function(p) {
                const nm = p.entries.map(function(e) { const t = base.teamByRoster[e.roster_id] || {}; return t.name + (t.isMe ? ' (you)' : ''); }).join('  vs  ');
                return <option key={p.mid} value={p.mid}>{nm}</option>;
              })}
            </select>
          </div>
          <button onClick={function() { loadMatchups(base, week); }} title="Refresh live points" style={{ flex: '0 0 auto', alignSelf: 'flex-end', background: T.raised, border: '1px solid ' + T.borderHi, color: T.dim, borderRadius: 8, padding: '8px 11px', fontSize: 14, cursor: 'pointer' }}>↻</button>
        </div>
        <div style={{ fontSize: 11, color: T.faint, marginTop: 8, lineHeight: 1.45 }}>
          Tap a player whose game you've <em>already watched</em> to reveal their score. Nothing is shown otherwise — unwatched games stay unspoiled.
        </div>
      </div>

      {loadingM && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 11, padding: 40 }}>
          <span style={spin} /><span style={{ color: T.dim, fontSize: 14 }}>{'Loading week ' + week + '…'}</span>
        </div>
      )}

      {!loadingM && matchErr && (
        <div style={{ padding: 30, textAlign: 'center', color: T.amber, fontSize: 14 }}>Couldn't load this week's matchups — try ↻.</div>
      )}

      {!loadingM && !matchErr && (!pairs || !pairs.length) && (
        <div style={{ padding: 30, textAlign: 'center', color: T.dim, fontSize: 14 }}>{'No matchups posted for week ' + week + ' yet.'}</div>
      )}

      {!loadingM && !matchErr && pair && (
        <div style={{ padding: 14 }}>
          {/* running scoreboard — revealed totals only */}
          <div style={{ display: 'flex', background: T.panel, border: '1px solid ' + T.border, borderRadius: 14, overflow: 'hidden', marginBottom: 14 }}>
            {entries.map(function(entry, idx) {
              const rows = startersOf(entry, base);
              const tot = revealedTotal(entry, rows);
              const cnt = revealedCount(entry, rows);
              const playable = rows.filter(function(r) { return !r.empty; }).length;
              const t = base.teamByRoster[entry.roster_id] || {};
              return (
                <div key={entry.roster_id} style={{ flex: 1, padding: '13px 10px', textAlign: 'center', borderRight: idx === 0 ? '1px solid ' + T.border : 'none', background: t.isMe ? 'rgba(99,102,241,0.07)' : 'transparent' }}>
                  <div style={{ fontSize: 10.5, color: t.isMe ? T.indigo : T.faint, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 4, fontWeight: 700, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{t.name}{t.isMe ? ' (you)' : ''}</div>
                  <div style={{ fontWeight: 800, fontSize: 30, color: cnt ? T.text : T.faint, lineHeight: 1 }}>{fmtPts(tot)}</div>
                  <div style={{ fontSize: 10.5, color: T.dim, marginTop: 4 }}>{cnt + '/' + playable + ' revealed'}</div>
                </div>
              );
            })}
          </div>

          {/* per-team starter lists */}
          {entries.map(function(entry) {
            const rows = startersOf(entry, base);
            const t = base.teamByRoster[entry.roster_id] || {};
            const cnt = revealedCount(entry, rows);
            const playable = rows.filter(function(r) { return !r.empty; }).length;
            const allOn = cnt === playable && playable > 0;
            return (
              <div key={entry.roster_id} style={{ background: T.panel, border: '1px solid ' + T.border, borderTop: '3px solid ' + (t.isMe ? T.indigo : T.border), borderRadius: '4px 4px 12px 12px', padding: '12px 13px', marginBottom: 12 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 9 }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontWeight: 700, fontSize: 14, color: T.text, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{teamLabelOf(entry.roster_id)}{t.isMe ? <span style={{ color: T.indigo, fontSize: 10.5, fontWeight: 800, marginLeft: 6 }}>YOU</span> : null}</div>
                  </div>
                  <button onClick={function() { setAll(entry, rows, !allOn); }} style={{ flex: '0 0 auto', background: 'none', border: '1px solid ' + T.borderHi, color: T.dim, borderRadius: 7, padding: '5px 9px', fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', cursor: 'pointer' }}>{allOn ? 'Hide all' : 'Reveal all'}</button>
                </div>
                {rows.map(function(row) {
                  const key = entry.roster_id + ':' + row.i;
                  const isOpen = !!revealed[key];
                  const tint = POS_TINT[row.slot] || T.dim;
                  if (row.empty) {
                    return (
                      <div key={row.i} style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '7px 0', borderBottom: '1px solid ' + T.border }}>
                        <span style={{ flex: '0 0 38px', fontSize: 10, fontWeight: 800, color: T.faint, textTransform: 'uppercase' }}>{row.slot}</span>
                        <span style={{ flex: 1, color: T.faint, fontSize: 13, fontStyle: 'italic' }}>Empty</span>
                      </div>
                    );
                  }
                  return (
                    <div key={row.i} onClick={function() { toggle(key); }} style={{ display: 'flex', alignItems: 'center', gap: 9, padding: '7px 0', borderBottom: '1px solid ' + T.border, cursor: 'pointer' }}>
                      <span style={{ flex: '0 0 38px', fontSize: 10, fontWeight: 800, color: tint, textTransform: 'uppercase' }}>{row.slot}</span>
                      <span style={{ flex: 1, minWidth: 0, color: isOpen ? T.text : T.dim, fontSize: 13.5, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {row.name}{row.pos ? <span style={{ color: T.faint, fontSize: 11, marginLeft: 6 }}>{row.pos}</span> : null}
                      </span>
                      {isOpen
                        ? <span style={{ flex: '0 0 auto', fontWeight: 800, fontSize: 14.5, color: row.pts > 0 ? T.green : T.faint, minWidth: 48, textAlign: 'right' }}>{fmtPts(row.pts)}</span>
                        : <span style={{ flex: '0 0 auto', fontSize: 10.5, fontWeight: 700, color: T.indigo, border: '1px solid ' + T.borderHi, borderRadius: 20, padding: '4px 11px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Reveal</span>}
                    </div>
                  );
                })}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

const CSS = `
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
  html,body{height:100%;}
  body{background:#090d18;-webkit-font-smoothing:antialiased;overflow:hidden;}
  ::-webkit-scrollbar{width:5px;height:5px;}
  ::-webkit-scrollbar-thumb{background:#24344e;border-radius:3px;}
  @keyframes ld-pulse{0%,80%,100%{opacity:.2;transform:scale(.7)}40%{opacity:1;transform:scale(1)}}
  .ld{display:inline-block;width:7px;height:7px;background:#6366f1;border-radius:50%;margin:0 2px;animation:ld-pulse 1.4s infinite ease-in-out both;}
  .ld:nth-child(2){animation-delay:.2s}.ld:nth-child(3){animation-delay:.4s}
  .md-table{border-collapse:collapse;width:100%;font-size:13px;background:#0f1625;border-radius:10px;overflow:hidden;}
  .md-table th{text-align:left;padding:9px 12px;background:#090d18;color:#f59e0b;font-weight:800;text-transform:uppercase;font-size:10.5px;letter-spacing:0.07em;border-bottom:1px solid #24344e;white-space:nowrap;}
  .md-table td{padding:8px 12px;border-bottom:1px solid #1a2640;color:#e8f1ff;}
  .md-table td:first-child{font-weight:600;}
  .md-table tr:last-child td{border-bottom:none;}
  .md-table tbody tr:nth-child(even) td{background:rgba(99,102,241,0.04);}
  .chip{background:#1a2640;border:1px solid #304260;color:#e8f1ff;border-radius:20px;padding:8px 15px;font-size:13px;font-weight:600;cursor:pointer;white-space:nowrap;flex-shrink:0;transition:border-color .15s,background .15s;}
  .chip:hover:not(:disabled){border-color:#6366f1;background:#232e50;}
  .chip:disabled{opacity:0.4;cursor:default;}
  .send-btn{background:linear-gradient(135deg,#6366f1,#4f46e5);color:#fff;border:none;border-radius:12px;padding:0 18px;font-weight:700;font-size:12.5px;letter-spacing:0.8px;text-transform:uppercase;cursor:pointer;align-self:stretch;flex-shrink:0;}
  .send-btn:disabled{background:#1a2640;color:#3d5470;cursor:default;}
  .nav-btn{flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;padding:10px 4px;background:transparent;border:none;cursor:pointer;position:relative;}
  .nav-btn .nav-ico{font-size:20px;}
  .nav-btn:not(.active) .nav-ico{filter:grayscale(0.7) opacity(0.5);}
  .nav-lab{font-size:10px;font-weight:800;letter-spacing:0.1em;text-transform:uppercase;}
  .plaincy-app{display:flex;flex-direction:column;height:var(--app-h,100dvh);width:100%;max-width:560px;margin:0 auto;background:#090d18;overflow:hidden;}
  @media(min-width:640px){.plaincy-app{max-width:780px;}}
  button{font-family:inherit;}
  textarea,select{font-family:inherit;font-size:16px;}
  textarea:focus,select:focus{outline:none;}
  select option{background:#141e32;color:#e8f1ff;}
`;

const TABS = [
  { id: 'stats', icon: '📊', label: 'STATS' },
  { id: 'banter', icon: '🎙', label: 'BANTER' },
  { id: 'trade', icon: '⚖️', label: 'TRADES' },
  { id: 'live', icon: '🏈', label: 'SCORES' },
];

export default function App() {
  const [tab, setTab] = useState('stats');
  const { history, stats, rosters, trades, alltime, transactions, live } = useLeagueData();
  const { keyboardOpen } = useViewport();
  const lore = useLore(tab === 'banter');

  useEffect(function() {
    if (document.getElementById('plaincy-css')) return;
    const el = document.createElement('style');
    el.id = 'plaincy-css';
    el.textContent = CSS;
    document.head.appendChild(el);
  }, []);

  return (
    <div className="plaincy-app">
      <div style={{ height: 3, background: 'linear-gradient(90deg,#6366f1 0%,#f59e0b 60%,#6366f1 100%)', flexShrink: 0 }} />
      <div style={{ display: 'flex', alignItems: 'center', gap: 13, padding: '12px 16px', background: T.panel, borderBottom: '1px solid ' + T.border, flexShrink: 0 }}>
        <div style={{ width: 40, height: 40, borderRadius: 12, background: 'linear-gradient(135deg,#6366f1,#4f46e5)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 900, fontSize: 22, color: '#fff', flexShrink: 0 }}>P</div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 900, fontSize: 22, color: T.text, letterSpacing: '-0.5px', lineHeight: 1 }}>Pl<span style={{ color: T.indigo }}>AI</span>ncy</div>
          <div style={{ fontSize: 11, color: T.dim, marginTop: 2, letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 600 }}>Borehamwood Plancy League</div>
        </div>
        <div style={{ fontSize: 10.5, color: T.dim, border: '1px solid ' + T.border, borderRadius: 6, padding: '4px 9px', whiteSpace: 'nowrap', flexShrink: 0, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 5 }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: live ? T.green : T.faint, display: 'inline-block' }} />
          {fmtBuiltAt(BUILT_AT)}
        </div>
      </div>

      <div style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        {tab === 'stats' && <StatsTab historyData={history} statsData={stats} alltimeData={alltime} transactionsData={transactions} loreMaster={lore.master} />}
        {tab === 'banter' && <BanterTab historyData={history} statsData={stats} alltimeData={alltime} lore={lore} />}
        {tab === 'trade' && <TradeGrader rostersData={rosters} tradeValues={trades} />}
        {tab === 'live' && <LiveTab rostersData={rosters} />}
      </div>

      {!keyboardOpen && (
        <nav style={{ display: 'flex', background: T.panel, borderTop: '1px solid ' + T.border, flexShrink: 0, paddingBottom: 'env(safe-area-inset-bottom)' }}>
          {TABS.map(function(t) {
            const active = tab === t.id;
            return (
              <button key={t.id} onClick={function() { setTab(t.id); }} className={'nav-btn' + (active ? ' active' : '')} style={{ color: active ? T.text : T.faint }}>
                {active && <span style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: 36, height: 3, borderRadius: '0 0 4px 4px', background: T.indigo }} />}
                <span className="nav-ico">{t.icon}</span>
                <span className="nav-lab">{t.label}</span>
              </button>
            );
          })}
        </nav>
      )}
    </div>
  );
}
