// ╔══════════════════════════════════════════════════════════════╗
// ║           THE COMMISSIONER — Borehamwood Plancy League        ║
// ║   Self-contained artifact: all data inlined, no network I/O   ║
// ╚══════════════════════════════════════════════════════════════╝

const { useState, useEffect, useRef, useMemo } = React;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// LORE ← FILL THIS IN BEFORE SHARING
// Everything here is fed directly to the Banter tab.
// Add nicknames, running jokes, feuds, draft disasters, etc.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const LORE = `
(Replace this block with your league lore before publishing.)

Suggestions:
- AlastairL won the 2025 title despite being AlastairL's bogey team sanfbe beating him twice in the regular season.
- dpol won a game in Week 3 by 0.02 points and never lets anyone forget it. Also lost the final by 25 points and hasn't recovered.
- GSac put up 202.36 in Week 12 2025 — the highest score in league history — and still didn't make the final. Cosmically unjust.
- benjlev went 0-14 in 2024. A perfect record of futility. The Borehamwood Spiral.
- Add your own: nicknames, draft regrets, waiver crimes, feuds, superstitions...
`;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// INLINED DATA  (the artifact sandbox blocks external fetch — CORS —
// so all four data sources are baked in at build time)
// History / Stats / Rosters: regenerated by the GitHub Actions pipeline.
// Trade values: a snapshot of FantasyCalc half-PPR 1QB redraft values.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const HISTORY_DATA = {"seasons":[{"season":"2023","name":"Borehamwood","champion":"saulgoat","standings":[{"manager":"drjkay","team":"Obi-Quan Kenobi","wins":10,"losses":4,"pf":1805.28,"high":154.7},{"manager":"joshjr11","team":"Denver Brochos","wins":10,"losses":4,"pf":1795.48,"high":179.48},{"manager":"saulgoat","team":"Saul","wins":7,"losses":7,"pf":1855.7,"high":189.76},{"manager":"sanfbe","team":"sanfbe","wins":7,"losses":7,"pf":1726.64,"high":180.98},{"manager":"allyl900","team":"allyl900","wins":6,"losses":8,"pf":1756.06,"high":151.4},{"manager":"dpol","team":"dpol","wins":6,"losses":8,"pf":1718.68,"high":173.18},{"manager":"GSac","team":"GSac","wins":6,"losses":8,"pf":1582.04,"high":146.14},{"manager":"benjlev","team":"benjlev","wins":4,"losses":10,"pf":1571.92,"high":144.1}],"games":[{"week":1,"playoff":false,"a":"dpol","b":"allyl900","pa":69,"pb":120.54},{"week":1,"playoff":false,"a":"benjlev","b":"saulgoat","pa":116.34,"pb":146.08},{"week":1,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":97.86,"pb":92.34},{"week":1,"playoff":false,"a":"drjkay","b":"GSac","pa":138.16,"pb":103.54},{"week":2,"playoff":false,"a":"benjlev","b":"sanfbe","pa":144.1,"pb":110.76},{"week":2,"playoff":false,"a":"dpol","b":"saulgoat","pa":111.02,"pb":82.48},{"week":2,"playoff":false,"a":"allyl900","b":"GSac","pa":105.66,"pb":110.14},{"week":2,"playoff":false,"a":"joshjr11","b":"drjkay","pa":179.48,"pb":138},{"week":3,"playoff":false,"a":"dpol","b":"sanfbe","pa":173.18,"pb":151.32},{"week":3,"playoff":false,"a":"drjkay","b":"allyl900","pa":136.46,"pb":147.26},{"week":3,"playoff":false,"a":"saulgoat","b":"GSac","pa":125.18,"pb":111.26},{"week":3,"playoff":false,"a":"joshjr11","b":"benjlev","pa":109.28,"pb":130.88},{"week":4,"playoff":false,"a":"benjlev","b":"drjkay","pa":105.6,"pb":132.88},{"week":4,"playoff":false,"a":"joshjr11","b":"allyl900","pa":141.94,"pb":113.88},{"week":4,"playoff":false,"a":"dpol","b":"GSac","pa":99.36,"pb":123.6},{"week":4,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":97.56,"pb":168.6},{"week":5,"playoff":false,"a":"joshjr11","b":"dpol","pa":54.84,"pb":159.32},{"week":5,"playoff":false,"a":"saulgoat","b":"drjkay","pa":189.76,"pb":76},{"week":5,"playoff":false,"a":"GSac","b":"sanfbe","pa":101.78,"pb":130.36},{"week":5,"playoff":false,"a":"benjlev","b":"allyl900","pa":89.84,"pb":113.32},{"week":6,"playoff":false,"a":"benjlev","b":"GSac","pa":130.94,"pb":102.12},{"week":6,"playoff":false,"a":"dpol","b":"drjkay","pa":120.3,"pb":128.18},{"week":6,"playoff":false,"a":"allyl900","b":"sanfbe","pa":102.98,"pb":114.96},{"week":6,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":101.02,"pb":152.3},{"week":7,"playoff":false,"a":"saulgoat","b":"allyl900","pa":121.44,"pb":145.34},{"week":7,"playoff":false,"a":"benjlev","b":"dpol","pa":86.46,"pb":87.56},{"week":7,"playoff":false,"a":"joshjr11","b":"GSac","pa":128.98,"pb":94.18},{"week":7,"playoff":false,"a":"drjkay","b":"sanfbe","pa":132.66,"pb":94.3},{"week":8,"playoff":false,"a":"dpol","b":"sanfbe","pa":121.16,"pb":126.56},{"week":8,"playoff":false,"a":"benjlev","b":"drjkay","pa":86.6,"pb":122.92},{"week":8,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":110.1,"pb":132.68},{"week":8,"playoff":false,"a":"allyl900","b":"GSac","pa":127.96,"pb":134.48},{"week":9,"playoff":false,"a":"benjlev","b":"dpol","pa":117,"pb":114.18},{"week":9,"playoff":false,"a":"saulgoat","b":"GSac","pa":127.82,"pb":123.48},{"week":9,"playoff":false,"a":"allyl900","b":"sanfbe","pa":92.52,"pb":100.12},{"week":9,"playoff":false,"a":"joshjr11","b":"drjkay","pa":120.66,"pb":89.54},{"week":10,"playoff":false,"a":"saulgoat","b":"allyl900","pa":134.18,"pb":142.86},{"week":10,"playoff":false,"a":"dpol","b":"drjkay","pa":131.34,"pb":146.02},{"week":10,"playoff":false,"a":"GSac","b":"sanfbe","pa":135.02,"pb":69.88},{"week":10,"playoff":false,"a":"joshjr11","b":"benjlev","pa":138.46,"pb":113.82},{"week":11,"playoff":false,"a":"benjlev","b":"allyl900","pa":78.68,"pb":130},{"week":11,"playoff":false,"a":"joshjr11","b":"dpol","pa":105.56,"pb":122.74},{"week":11,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":116.54,"pb":126.7},{"week":11,"playoff":false,"a":"drjkay","b":"GSac","pa":154.7,"pb":109.56},{"week":12,"playoff":false,"a":"joshjr11","b":"GSac","pa":150.74,"pb":97.08},{"week":12,"playoff":false,"a":"saulgoat","b":"drjkay","pa":132.28,"pb":132.66},{"week":12,"playoff":false,"a":"dpol","b":"allyl900","pa":144.3,"pb":129.74},{"week":12,"playoff":false,"a":"benjlev","b":"sanfbe","pa":124.52,"pb":133.86},{"week":13,"playoff":false,"a":"benjlev","b":"GSac","pa":87,"pb":98.56},{"week":13,"playoff":false,"a":"dpol","b":"saulgoat","pa":106.04,"pb":137.18},{"week":13,"playoff":false,"a":"drjkay","b":"sanfbe","pa":125.18,"pb":118.36},{"week":13,"playoff":false,"a":"joshjr11","b":"allyl900","pa":168.56,"pb":151.4},{"week":14,"playoff":false,"a":"dpol","b":"GSac","pa":109.08,"pb":106.54},{"week":14,"playoff":false,"a":"benjlev","b":"saulgoat","pa":124.64,"pb":128.12},{"week":14,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":140.74,"pb":125.42},{"week":14,"playoff":false,"a":"drjkay","b":"allyl900","pa":114.94,"pb":118.2},{"week":15,"playoff":true,"a":"allyl900","b":"sanfbe","pa":130.26,"pb":81.66},{"week":15,"playoff":true,"a":"dpol","b":"saulgoat","pa":88.12,"pb":113.32},{"week":15,"playoff":true,"a":"benjlev","b":"GSac","pa":91.1,"pb":107.24},{"week":16,"playoff":true,"a":"drjkay","b":"allyl900","pa":119.24,"pb":127.12},{"week":16,"playoff":true,"a":"joshjr11","b":"saulgoat","pa":97.42,"pb":118.3},{"week":16,"playoff":true,"a":"dpol","b":"sanfbe","pa":91.44,"pb":180.98},{"week":17,"playoff":true,"a":"saulgoat","b":"allyl900","pa":163.68,"pb":85.72},{"week":17,"playoff":true,"a":"joshjr11","b":"drjkay","pa":106.5,"pb":114.56}]},{"season":"2024","name":"Borehamwood","champion":"saulgoat","standings":[{"manager":"saulgoat","team":"Chase waddle waddle ","wins":11,"losses":3,"pf":1903.3,"high":196.9},{"manager":"AlastairL","team":"Fourth and Goalda Meir","wins":10,"losses":4,"pf":1968.96,"high":178.94},{"manager":"dpol","team":"Plancey Neutral","wins":9,"losses":5,"pf":1732.22,"high":189},{"manager":"joshjr11","team":"Denver Brochos","wins":8,"losses":6,"pf":1713.02,"high":181.32},{"manager":"GSac","team":"War & Childbirth","wins":7,"losses":7,"pf":1758.44,"high":159.22},{"manager":"drjkay","team":"To infinity and Bijan","wins":6,"losses":8,"pf":1767.8,"high":213.46},{"manager":"sanfbe","team":"The Twinder Swindler","wins":5,"losses":9,"pf":1504.7,"high":144.4},{"manager":"benjlev","team":"benjlev","wins":0,"losses":14,"pf":1522.48,"high":142.9}],"games":[{"week":1,"playoff":false,"a":"dpol","b":"drjkay","pa":127.86,"pb":119.98},{"week":1,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":115.76,"pb":108.38},{"week":1,"playoff":false,"a":"benjlev","b":"AlastairL","pa":108.34,"pb":138.28},{"week":1,"playoff":false,"a":"joshjr11","b":"GSac","pa":102.32,"pb":99.52},{"week":2,"playoff":false,"a":"dpol","b":"saulgoat","pa":146.7,"pb":113.1},{"week":2,"playoff":false,"a":"drjkay","b":"sanfbe","pa":153.24,"pb":88.96},{"week":2,"playoff":false,"a":"joshjr11","b":"AlastairL","pa":181.32,"pb":104.26},{"week":2,"playoff":false,"a":"benjlev","b":"GSac","pa":97.84,"pb":115.88},{"week":3,"playoff":false,"a":"dpol","b":"sanfbe","pa":92.36,"pb":126.04},{"week":3,"playoff":false,"a":"saulgoat","b":"drjkay","pa":121.02,"pb":109.58},{"week":3,"playoff":false,"a":"AlastairL","b":"GSac","pa":116.88,"pb":108.68},{"week":3,"playoff":false,"a":"joshjr11","b":"benjlev","pa":137.14,"pb":106.28},{"week":4,"playoff":false,"a":"dpol","b":"AlastairL","pa":142.08,"pb":138.32},{"week":4,"playoff":false,"a":"benjlev","b":"drjkay","pa":125,"pb":129.48},{"week":4,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":109.32,"pb":118.9},{"week":4,"playoff":false,"a":"GSac","b":"sanfbe","pa":129.72,"pb":84.1},{"week":5,"playoff":false,"a":"benjlev","b":"dpol","pa":104.34,"pb":144.96},{"week":5,"playoff":false,"a":"drjkay","b":"AlastairL","pa":101.46,"pb":159.62},{"week":5,"playoff":false,"a":"saulgoat","b":"GSac","pa":137.24,"pb":159.22},{"week":5,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":77.04,"pb":97.24},{"week":6,"playoff":false,"a":"joshjr11","b":"dpol","pa":109.86,"pb":118.3},{"week":6,"playoff":false,"a":"drjkay","b":"GSac","pa":160.76,"pb":135.62},{"week":6,"playoff":false,"a":"saulgoat","b":"AlastairL","pa":145.72,"pb":120.06},{"week":6,"playoff":false,"a":"benjlev","b":"sanfbe","pa":83.22,"pb":112.7},{"week":7,"playoff":false,"a":"dpol","b":"GSac","pa":98.66,"pb":145.04},{"week":7,"playoff":false,"a":"joshjr11","b":"drjkay","pa":119.66,"pb":116.9},{"week":7,"playoff":false,"a":"benjlev","b":"saulgoat","pa":109.06,"pb":119.3},{"week":7,"playoff":false,"a":"AlastairL","b":"sanfbe","pa":121.94,"pb":110.12},{"week":8,"playoff":false,"a":"dpol","b":"drjkay","pa":108.64,"pb":124.9},{"week":8,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":135.44,"pb":98.42},{"week":8,"playoff":false,"a":"benjlev","b":"AlastairL","pa":104.38,"pb":163.96},{"week":8,"playoff":false,"a":"joshjr11","b":"GSac","pa":153.34,"pb":115.86},{"week":9,"playoff":false,"a":"dpol","b":"saulgoat","pa":128.4,"pb":101.22},{"week":9,"playoff":false,"a":"drjkay","b":"sanfbe","pa":142.5,"pb":144.4},{"week":9,"playoff":false,"a":"joshjr11","b":"AlastairL","pa":123,"pb":150.76},{"week":9,"playoff":false,"a":"benjlev","b":"GSac","pa":114.34,"pb":141.68},{"week":10,"playoff":false,"a":"dpol","b":"sanfbe","pa":107.4,"pb":91.5},{"week":10,"playoff":false,"a":"saulgoat","b":"drjkay","pa":134.44,"pb":130.24},{"week":10,"playoff":false,"a":"AlastairL","b":"GSac","pa":128.02,"pb":127.42},{"week":10,"playoff":false,"a":"joshjr11","b":"benjlev","pa":124.08,"pb":123.44},{"week":11,"playoff":false,"a":"dpol","b":"AlastairL","pa":86.38,"pb":178.94},{"week":11,"playoff":false,"a":"benjlev","b":"drjkay","pa":88.64,"pb":104.8},{"week":11,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":150.34,"pb":196.9},{"week":11,"playoff":false,"a":"GSac","b":"sanfbe","pa":128.26,"pb":93.18},{"week":12,"playoff":false,"a":"benjlev","b":"dpol","pa":116.96,"pb":133.08},{"week":12,"playoff":false,"a":"drjkay","b":"AlastairL","pa":116.16,"pb":175.4},{"week":12,"playoff":false,"a":"saulgoat","b":"GSac","pa":162.92,"pb":106.62},{"week":12,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":91.76,"pb":85.06},{"week":13,"playoff":false,"a":"joshjr11","b":"dpol","pa":112.52,"pb":170.18},{"week":13,"playoff":false,"a":"drjkay","b":"GSac","pa":152.2,"pb":110.78},{"week":13,"playoff":false,"a":"saulgoat","b":"AlastairL","pa":132.66,"pb":111.96},{"week":13,"playoff":false,"a":"benjlev","b":"sanfbe","pa":117.14,"pb":122.32},{"week":14,"playoff":false,"a":"dpol","b":"GSac","pa":127.22,"pb":134.14},{"week":14,"playoff":false,"a":"joshjr11","b":"drjkay","pa":121.32,"pb":105.6},{"week":14,"playoff":false,"a":"benjlev","b":"saulgoat","pa":123.5,"pb":168.68},{"week":14,"playoff":false,"a":"AlastairL","b":"sanfbe","pa":160.56,"pb":142.28},{"week":15,"playoff":true,"a":"joshjr11","b":"GSac","pa":130.3,"pb":127.04},{"week":15,"playoff":true,"a":"dpol","b":"drjkay","pa":189,"pb":116.68},{"week":15,"playoff":true,"a":"benjlev","b":"sanfbe","pa":119.76,"pb":137.78},{"week":16,"playoff":true,"a":"joshjr11","b":"saulgoat","pa":94.24,"pb":124.94},{"week":16,"playoff":true,"a":"dpol","b":"AlastairL","pa":141.88,"pb":176.68},{"week":16,"playoff":true,"a":"drjkay","b":"GSac","pa":192.72,"pb":111.9},{"week":17,"playoff":true,"a":"saulgoat","b":"AlastairL","pa":149.16,"pb":143.08},{"week":17,"playoff":true,"a":"benjlev","b":"sanfbe","pa":131.44,"pb":108.78}]},{"season":"2025","name":"Borehamwood","champion":"AlastairL","standings":[{"manager":"dpol","team":"Plancey Neutral","wins":11,"losses":3,"pf":1878.92,"high":186.44},{"manager":"AlastairL","team":"Fourth and Goalda Meir","wins":9,"losses":5,"pf":1828.36,"high":156.58},{"manager":"sanfbe","team":"J’Allen Plancey z’l","wins":8,"losses":6,"pf":1778.06,"high":163.6},{"manager":"saulgoat","team":"Love Thy Naber","wins":8,"losses":6,"pf":1689.66,"high":172.42},{"manager":"joshjr11","team":"Denver Brochos","wins":6,"losses":8,"pf":1818.96,"high":173.36},{"manager":"drjkay","team":"A rookie error","wins":6,"losses":8,"pf":1770.74,"high":169.02},{"manager":"GSac","team":"This One Really Hurts","wins":5,"losses":9,"pf":1786.8,"high":202.36},{"manager":"benjlev","team":"benjlev","wins":3,"losses":11,"pf":1562.56,"high":163.26}],"games":[{"week":1,"playoff":false,"a":"dpol","b":"drjkay","pa":107.02,"pb":99.74},{"week":1,"playoff":false,"a":"saulgoat","b":"AlastairL","pa":88.72,"pb":95.08},{"week":1,"playoff":false,"a":"joshjr11","b":"benjlev","pa":91.32,"pb":163.26},{"week":1,"playoff":false,"a":"GSac","b":"sanfbe","pa":112.08,"pb":155.26},{"week":2,"playoff":false,"a":"dpol","b":"saulgoat","pa":138.08,"pb":137.6},{"week":2,"playoff":false,"a":"drjkay","b":"AlastairL","pa":126.08,"pb":133.88},{"week":2,"playoff":false,"a":"joshjr11","b":"GSac","pa":127.64,"pb":101.44},{"week":2,"playoff":false,"a":"benjlev","b":"sanfbe","pa":109.9,"pb":111.72},{"week":3,"playoff":false,"a":"dpol","b":"AlastairL","pa":131.86,"pb":131.84},{"week":3,"playoff":false,"a":"saulgoat","b":"drjkay","pa":137.62,"pb":113.4},{"week":3,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":90.18,"pb":135.02},{"week":3,"playoff":false,"a":"benjlev","b":"GSac","pa":96.92,"pb":115.04},{"week":4,"playoff":false,"a":"joshjr11","b":"dpol","pa":141.88,"pb":154.2},{"week":4,"playoff":false,"a":"benjlev","b":"drjkay","pa":88.98,"pb":169.02},{"week":4,"playoff":false,"a":"saulgoat","b":"GSac","pa":131.28,"pb":121.2},{"week":4,"playoff":false,"a":"AlastairL","b":"sanfbe","pa":140.52,"pb":151.26},{"week":5,"playoff":false,"a":"benjlev","b":"dpol","pa":135.16,"pb":136.42},{"week":5,"playoff":false,"a":"joshjr11","b":"drjkay","pa":145.72,"pb":102.04},{"week":5,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":140.54,"pb":138.42},{"week":5,"playoff":false,"a":"AlastairL","b":"GSac","pa":127.72,"pb":121.5},{"week":6,"playoff":false,"a":"dpol","b":"GSac","pa":128.38,"pb":118.42},{"week":6,"playoff":false,"a":"drjkay","b":"sanfbe","pa":108.74,"pb":163.6},{"week":6,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":137.16,"pb":106.96},{"week":6,"playoff":false,"a":"benjlev","b":"AlastairL","pa":103.54,"pb":115.04},{"week":7,"playoff":false,"a":"dpol","b":"sanfbe","pa":186.44,"pb":77.44},{"week":7,"playoff":false,"a":"drjkay","b":"GSac","pa":118.16,"pb":192.04},{"week":7,"playoff":false,"a":"benjlev","b":"saulgoat","pa":79.32,"pb":86.94},{"week":7,"playoff":false,"a":"joshjr11","b":"AlastairL","pa":119.98,"pb":156.58},{"week":8,"playoff":false,"a":"dpol","b":"drjkay","pa":147.16,"pb":118.52},{"week":8,"playoff":false,"a":"saulgoat","b":"AlastairL","pa":108.88,"pb":123.88},{"week":8,"playoff":false,"a":"joshjr11","b":"benjlev","pa":146.48,"pb":154.34},{"week":8,"playoff":false,"a":"GSac","b":"sanfbe","pa":145.66,"pb":116.62},{"week":9,"playoff":false,"a":"dpol","b":"saulgoat","pa":79.9,"pb":120.92},{"week":9,"playoff":false,"a":"drjkay","b":"AlastairL","pa":119.1,"pb":154.96},{"week":9,"playoff":false,"a":"joshjr11","b":"GSac","pa":165.3,"pb":123.54},{"week":9,"playoff":false,"a":"benjlev","b":"sanfbe","pa":124.56,"pb":125.42},{"week":10,"playoff":false,"a":"dpol","b":"AlastairL","pa":127.7,"pb":148.7},{"week":10,"playoff":false,"a":"saulgoat","b":"drjkay","pa":145.5,"pb":146.6},{"week":10,"playoff":false,"a":"joshjr11","b":"sanfbe","pa":162.8,"pb":103.44},{"week":10,"playoff":false,"a":"benjlev","b":"GSac","pa":99.74,"pb":157.52},{"week":11,"playoff":false,"a":"joshjr11","b":"dpol","pa":114.54,"pb":116.44},{"week":11,"playoff":false,"a":"benjlev","b":"drjkay","pa":98.02,"pb":131.72},{"week":11,"playoff":false,"a":"saulgoat","b":"GSac","pa":128.96,"pb":67.9},{"week":11,"playoff":false,"a":"AlastairL","b":"sanfbe","pa":140.74,"pb":160.48},{"week":12,"playoff":false,"a":"benjlev","b":"dpol","pa":96.02,"pb":121.48},{"week":12,"playoff":false,"a":"joshjr11","b":"drjkay","pa":113.46,"pb":130.08},{"week":12,"playoff":false,"a":"saulgoat","b":"sanfbe","pa":105.12,"pb":95.82},{"week":12,"playoff":false,"a":"AlastairL","b":"GSac","pa":133.56,"pb":202.36},{"week":13,"playoff":false,"a":"dpol","b":"GSac","pa":157.44,"pb":100.2},{"week":13,"playoff":false,"a":"drjkay","b":"sanfbe","pa":141,"pb":88.52},{"week":13,"playoff":false,"a":"joshjr11","b":"saulgoat","pa":148.64,"pb":114.16},{"week":13,"playoff":false,"a":"benjlev","b":"AlastairL","pa":110.14,"pb":95.02},{"week":14,"playoff":false,"a":"dpol","b":"sanfbe","pa":146.4,"pb":155.04},{"week":14,"playoff":false,"a":"drjkay","b":"GSac","pa":146.54,"pb":107.9},{"week":14,"playoff":false,"a":"benjlev","b":"saulgoat","pa":102.66,"pb":136.46},{"week":14,"playoff":false,"a":"joshjr11","b":"AlastairL","pa":113.86,"pb":130.84},{"week":15,"playoff":true,"a":"joshjr11","b":"saulgoat","pa":143.2,"pb":172.42},{"week":15,"playoff":true,"a":"drjkay","b":"sanfbe","pa":94.94,"pb":160.82},{"week":15,"playoff":true,"a":"benjlev","b":"GSac","pa":98.9,"pb":107.4},{"week":16,"playoff":true,"a":"dpol","b":"sanfbe","pa":161.02,"pb":108.9},{"week":16,"playoff":true,"a":"saulgoat","b":"AlastairL","pa":113.46,"pb":130.5},{"week":16,"playoff":true,"a":"joshjr11","b":"drjkay","pa":173.36,"pb":116.02},{"week":17,"playoff":true,"a":"dpol","b":"AlastairL","pa":118.58,"pb":143.96},{"week":17,"playoff":true,"a":"saulgoat","b":"sanfbe","pa":76.78,"pb":143.58}]}]};
const STATS_DATA   = {"league":"Borehamwood","season":"2025","standings":[{"manager":"dpol","team":"Plancey Neutral","wins":11,"losses":3,"ties":0,"pf":1878.92,"pa":1696.02,"streak":0},{"manager":"AlastairL","team":"Fourth and Goalda Meir","wins":9,"losses":5,"ties":0,"pf":1828.36,"pa":1785.46,"streak":0},{"manager":"sanfbe","team":"J’Allen Plancey z’l","wins":8,"losses":6,"ties":0,"pf":1778.06,"pa":1854.68,"streak":0},{"manager":"saulgoat","team":"Love Thy Naber","wins":8,"losses":6,"ties":0,"pf":1689.66,"pa":1588.06,"streak":0},{"manager":"joshjr11","team":"Denver Brochos","wins":6,"losses":8,"ties":0,"pf":1818.96,"pa":1792.34,"streak":0},{"manager":"drjkay","team":"A rookie error","wins":6,"losses":8,"ties":0,"pf":1770.74,"pa":1824.38,"streak":0},{"manager":"GSac","team":"This One Really Hurts","wins":5,"losses":9,"ties":0,"pf":1786.8,"pa":1833.52,"streak":0},{"manager":"benjlev","team":"benjlev","wins":3,"losses":11,"ties":0,"pf":1562.56,"pa":1739.6,"streak":0}],"headToHead":{"dpol":{"drjkay":{"wins":2,"losses":0,"pf":254.18,"pa":218.26},"saulgoat":{"wins":1,"losses":1,"pf":217.98,"pa":258.52},"AlastairL":{"wins":1,"losses":1,"pf":259.56,"pa":280.54},"joshjr11":{"wins":2,"losses":0,"pf":270.64,"pa":256.42},"benjlev":{"wins":2,"losses":0,"pf":257.9,"pa":231.18},"GSac":{"wins":2,"losses":0,"pf":285.82,"pa":218.62},"sanfbe":{"wins":1,"losses":1,"pf":332.84,"pa":232.48}},"drjkay":{"dpol":{"wins":0,"losses":2,"pf":218.26,"pa":254.18},"AlastairL":{"wins":0,"losses":2,"pf":245.18,"pa":288.84},"saulgoat":{"wins":1,"losses":1,"pf":260,"pa":283.12},"benjlev":{"wins":2,"losses":0,"pf":300.74,"pa":187},"joshjr11":{"wins":1,"losses":1,"pf":232.12,"pa":259.18},"sanfbe":{"wins":1,"losses":1,"pf":249.74,"pa":252.12},"GSac":{"wins":1,"losses":1,"pf":264.7,"pa":299.94}},"saulgoat":{"AlastairL":{"wins":0,"losses":2,"pf":197.6,"pa":218.96},"dpol":{"wins":1,"losses":1,"pf":258.52,"pa":217.98},"drjkay":{"wins":1,"losses":1,"pf":283.12,"pa":260},"GSac":{"wins":2,"losses":0,"pf":260.24,"pa":189.1},"sanfbe":{"wins":2,"losses":0,"pf":245.66,"pa":234.24},"joshjr11":{"wins":0,"losses":2,"pf":221.12,"pa":285.8},"benjlev":{"wins":2,"losses":0,"pf":223.4,"pa":181.98}},"AlastairL":{"saulgoat":{"wins":2,"losses":0,"pf":218.96,"pa":197.6},"drjkay":{"wins":2,"losses":0,"pf":288.84,"pa":245.18},"dpol":{"wins":1,"losses":1,"pf":280.54,"pa":259.56},"sanfbe":{"wins":0,"losses":2,"pf":281.26,"pa":311.74},"GSac":{"wins":1,"losses":1,"pf":261.28,"pa":323.86},"benjlev":{"wins":1,"losses":1,"pf":210.06,"pa":213.68},"joshjr11":{"wins":2,"losses":0,"pf":287.42,"pa":233.84}},"joshjr11":{"benjlev":{"wins":0,"losses":2,"pf":237.8,"pa":317.6},"GSac":{"wins":2,"losses":0,"pf":292.94,"pa":224.98},"sanfbe":{"wins":1,"losses":1,"pf":252.98,"pa":238.46},"dpol":{"wins":0,"losses":2,"pf":256.42,"pa":270.64},"drjkay":{"wins":1,"losses":1,"pf":259.18,"pa":232.12},"saulgoat":{"wins":2,"losses":0,"pf":285.8,"pa":221.12},"AlastairL":{"wins":0,"losses":2,"pf":233.84,"pa":287.42}},"benjlev":{"joshjr11":{"wins":2,"losses":0,"pf":317.6,"pa":237.8},"sanfbe":{"wins":0,"losses":2,"pf":234.46,"pa":237.14},"GSac":{"wins":0,"losses":2,"pf":196.66,"pa":272.56},"drjkay":{"wins":0,"losses":2,"pf":187,"pa":300.74},"dpol":{"wins":0,"losses":2,"pf":231.18,"pa":257.9},"AlastairL":{"wins":1,"losses":1,"pf":213.68,"pa":210.06},"saulgoat":{"wins":0,"losses":2,"pf":181.98,"pa":223.4}},"GSac":{"sanfbe":{"wins":1,"losses":1,"pf":257.74,"pa":271.88},"joshjr11":{"wins":0,"losses":2,"pf":224.98,"pa":292.94},"benjlev":{"wins":2,"losses":0,"pf":272.56,"pa":196.66},"saulgoat":{"wins":0,"losses":2,"pf":189.1,"pa":260.24},"AlastairL":{"wins":1,"losses":1,"pf":323.86,"pa":261.28},"dpol":{"wins":0,"losses":2,"pf":218.62,"pa":285.82},"drjkay":{"wins":1,"losses":1,"pf":299.94,"pa":264.7}},"sanfbe":{"GSac":{"wins":1,"losses":1,"pf":271.88,"pa":257.74},"benjlev":{"wins":2,"losses":0,"pf":237.14,"pa":234.46},"joshjr11":{"wins":1,"losses":1,"pf":238.46,"pa":252.98},"AlastairL":{"wins":2,"losses":0,"pf":311.74,"pa":281.26},"saulgoat":{"wins":0,"losses":2,"pf":234.24,"pa":245.66},"drjkay":{"wins":1,"losses":1,"pf":252.12,"pa":249.74},"dpol":{"wins":1,"losses":1,"pf":232.48,"pa":332.84}}},"extremes":{"closestGame":{"week":3,"playoff":false,"a":"dpol","b":"AlastairL","pa":131.86,"pb":131.84},"biggestBlowout":{"week":7,"playoff":false,"a":"dpol","b":"sanfbe","pa":186.44,"pb":77.44},"highestScoringGame":{"week":12,"playoff":false,"a":"AlastairL","b":"GSac","pa":133.56,"pb":202.36}}};
const ROSTERS_DATA = {"Denver Brochos (@joshjr11)":[{"id":"10229","name":"Rashee Rice"},{"id":"11631","name":"Brian Thomas"},{"id":"12474","name":"Woody Marks"},{"id":"3451","name":"Ka'imi Fairbairn"},{"id":"4137","name":"James Conner"},{"id":"6770","name":"Joe Burrow"},{"id":"6794","name":"Justin Jefferson"},{"id":"7564","name":"Ja'Marr Chase"},{"id":"7594","name":"Chuba Hubbard"},{"id":"8112","name":"Drake London"},{"id":"8130","name":"Trey McBride"},{"id":"8144","name":"Chris Olave"},{"id":"8183","name":"Brock Purdy"},{"id":"9224","name":"Chase Brown"},{"id":"9226","name":"De'Von Achane"},{"id":"CHI","name":"Chicago Bears"},{"id":"DEN","name":"Denver Broncos"}],"benjlev (@benjlev)":[{"id":"10213","name":"Tre Tucker"},{"id":"11635","name":"Ladd McConkey"},{"id":"11638","name":"Ricky Pearsall"},{"id":"1466","name":"Travis Kelce"},{"id":"2747","name":"Jason Myers"},{"id":"3198","name":"Derrick Henry"},{"id":"3321","name":"Tyreek Hill"},{"id":"4199","name":"Aaron Jones"},{"id":"4866","name":"Saquon Barkley"},{"id":"4881","name":"Lamar Jackson"},{"id":"4983","name":"DJ Moore"},{"id":"7523","name":"Trevor Lawrence"},{"id":"7611","name":"Rhamondre Stevenson"},{"id":"8142","name":"Alec Pierce"},{"id":"8155","name":"Breece Hall"},{"id":"9756","name":"Jordan Addison"},{"id":"NYG","name":"New York Giants"}],"Plancey Neutral (@dpol)":[{"id":"11584","name":"Bucky Irving"},{"id":"11655","name":"Tyrone Tracy"},{"id":"12481","name":"Cam Skattebo"},{"id":"12507","name":"Omarion Hampton"},{"id":"2216","name":"Mike Evans"},{"id":"3214","name":"Hunter Henry"},{"id":"3257","name":"Jacoby Brissett"},{"id":"4217","name":"George Kittle"},{"id":"4381","name":"Taysom Hill"},{"id":"5859","name":"A.J. Brown"},{"id":"5947","name":"Jakobi Meyers"},{"id":"6786","name":"CeeDee Lamb"},{"id":"6813","name":"Jonathan Taylor"},{"id":"7839","name":"Evan McPherson"},{"id":"8126","name":"Wan'Dale Robinson"},{"id":"9493","name":"Puka Nacua"},{"id":"NE","name":"New England Patriots"}],"Love Thy Naber (@saulgoat)":[{"id":"11539","name":"Jake Bates"},{"id":"11586","name":"Blake Corum"},{"id":"11589","name":"Trey Benson"},{"id":"11632","name":"Malik Nabers"},{"id":"11643","name":"Jaylen Wright"},{"id":"12506","name":"Harold Fannin"},{"id":"12529","name":"TreVeyon Henderson"},{"id":"2505","name":"Darren Waller"},{"id":"3163","name":"Jared Goff"},{"id":"5045","name":"Courtland Sutton"},{"id":"6801","name":"Tee Higgins"},{"id":"7526","name":"Jaylen Waddle"},{"id":"7543","name":"Travis Etienne"},{"id":"7569","name":"Nico Collins"},{"id":"7588","name":"Javonte Williams"},{"id":"7607","name":"Michael Carter"},{"id":"8408","name":"Jordan Mason"},{"id":"BUF","name":"Buffalo Bills"}],"A rookie error (@drjkay)":[{"id":"10236","name":"Dalton Kincaid"},{"id":"12489","name":"RJ Harvey"},{"id":"12508","name":"Jaxson Dart"},{"id":"12512","name":"Quinshon Judkins"},{"id":"12514","name":"Emeka Egbuka"},{"id":"12526","name":"Tetairoa McMillan"},{"id":"12711","name":"Tyler Loop"},{"id":"3294","name":"Dak Prescott"},{"id":"4098","name":"Kareem Hunt"},{"id":"6806","name":"J.K. Dobbins"},{"id":"6819","name":"Michael Pittman"},{"id":"7567","name":"Kenneth Gainwell"},{"id":"8137","name":"George Pickens"},{"id":"8228","name":"Jaylen Warren"},{"id":"9480","name":"Brenton Strange"},{"id":"9488","name":"Jaxon Smith-Njigba"},{"id":"SEA","name":"Seattle Seahawks"}],"Fourth and Goalda Meir (@AlastairL)":[{"id":"11533","name":"Brandon Aubrey"},{"id":"11564","name":"Drake Maye"},{"id":"11604","name":"Brock Bowers"},{"id":"12519","name":"Luther Burden"},{"id":"2449","name":"Stefon Diggs"},{"id":"4034","name":"Christian McCaffrey"},{"id":"421","name":"Matthew Stafford"},{"id":"6790","name":"D'Andre Swift"},{"id":"7002","name":"Juwan Johnson"},{"id":"7547","name":"Amon-Ra St. Brown"},{"id":"7553","name":"Kyle Pitts"},{"id":"8132","name":"Tyler Allgeier"},{"id":"8148","name":"Jameson Williams"},{"id":"8150","name":"Kyren Williams"},{"id":"8151","name":"Kenneth Walker"},{"id":"8154","name":"Brian Robinson"},{"id":"PIT","name":"Pittsburgh Steelers"}],"This One Really Hurts (@GSac)":[{"id":"11579","name":"Audric Estime"},{"id":"11620","name":"Rome Odunze"},{"id":"11786","name":"Cam Little"},{"id":"12476","name":"Devin Neal"},{"id":"12527","name":"Ashton Jeanty"},{"id":"12530","name":"Travis Hunter"},{"id":"2133","name":"Davante Adams"},{"id":"6904","name":"Jalen Hurts"},{"id":"7049","name":"Jauan Jennings"},{"id":"7525","name":"DeVonta Smith"},{"id":"8110","name":"Jake Ferguson"},{"id":"8134","name":"Khalil Shakir"},{"id":"8138","name":"James Cook"},{"id":"8167","name":"Christian Watson"},{"id":"9221","name":"Jahmyr Gibbs"},{"id":"9504","name":"Kayshon Boutte"},{"id":"9508","name":"Tyjae Spears"},{"id":"JAX","name":"Jacksonville Jaguars"}],"J’Allen Plancey z’l (@sanfbe)":[{"id":"10222","name":"Jayden Reed"},{"id":"10232","name":"Michael Wilson"},{"id":"10859","name":"Sam LaPorta"},{"id":"11627","name":"Troy Franklin"},{"id":"12534","name":"Kyle Monangai"},{"id":"4984","name":"Josh Allen"},{"id":"5022","name":"Dallas Goedert"},{"id":"5189","name":"Eddy Pineiro"},{"id":"5846","name":"DK Metcalf"},{"id":"5850","name":"Josh Jacobs"},{"id":"5872","name":"Deebo Samuel"},{"id":"6865","name":"Colby Parkinson"},{"id":"7021","name":"Rico Dowdle"},{"id":"8146","name":"Garrett Wilson"},{"id":"9509","name":"Bijan Robinson"},{"id":"9753","name":"Zach Charbonnet"},{"id":"9997","name":"Zay Flowers"},{"id":"TB","name":"Tampa Bay Buccaneers"}]};
const TRADE_VALUES = [{"player":{"name":"Bijan Robinson","sleeperId":"9509","position":"RB"},"redraftValue":10485},{"player":{"name":"Jahmyr Gibbs","sleeperId":"9221","position":"RB"},"redraftValue":10378},{"player":{"name":"Ja'Marr Chase","sleeperId":"7564","position":"WR"},"redraftValue":9864},{"player":{"name":"Jaxon Smith-Njigba","sleeperId":"9488","position":"WR"},"redraftValue":8962},{"player":{"name":"Jonathan Taylor","sleeperId":"6813","position":"RB"},"redraftValue":8636},{"player":{"name":"Puka Nacua","sleeperId":"9493","position":"WR"},"redraftValue":8857},{"player":{"name":"Justin Jefferson","sleeperId":"6794","position":"WR"},"redraftValue":8678},{"player":{"name":"De'Von Achane","sleeperId":"9226","position":"RB"},"redraftValue":8168},{"player":{"name":"Amon-Ra St. Brown","sleeperId":"7547","position":"WR"},"redraftValue":8391},{"player":{"name":"Ashton Jeanty","sleeperId":"12527","position":"RB"},"redraftValue":7926},{"player":{"name":"Christian McCaffrey","sleeperId":"4034","position":"RB"},"redraftValue":7893},{"player":{"name":"James Cook","sleeperId":"8138","position":"RB"},"redraftValue":7705},{"player":{"name":"CeeDee Lamb","sleeperId":"6786","position":"WR"},"redraftValue":7592},{"player":{"name":"Saquon Barkley","sleeperId":"4866","position":"RB"},"redraftValue":6923},{"player":{"name":"Omarion Hampton","sleeperId":"12507","position":"RB"},"redraftValue":6921},{"player":{"name":"Jeremiyah Love","sleeperId":"13287","position":"RB"},"redraftValue":6718},{"player":{"name":"Trey McBride","sleeperId":"8130","position":"TE"},"redraftValue":6928},{"player":{"name":"Brock Bowers","sleeperId":"11604","position":"TE"},"redraftValue":6269},{"player":{"name":"Derrick Henry","sleeperId":"3198","position":"RB"},"redraftValue":5954},{"player":{"name":"Kenneth Walker","sleeperId":"8151","position":"RB"},"redraftValue":5743},{"player":{"name":"Josh Allen","sleeperId":"4984","position":"QB"},"redraftValue":6070},{"player":{"name":"Drake London","sleeperId":"8112","position":"WR"},"redraftValue":5877},{"player":{"name":"Breece Hall","sleeperId":"8155","position":"RB"},"redraftValue":5639},{"player":{"name":"Malik Nabers","sleeperId":"11632","position":"WR"},"redraftValue":5749},{"player":{"name":"Chase Brown","sleeperId":"9224","position":"RB"},"redraftValue":5512},{"player":{"name":"Nico Collins","sleeperId":"7569","position":"WR"},"redraftValue":4942},{"player":{"name":"Kyren Williams","sleeperId":"8150","position":"RB"},"redraftValue":4673},{"player":{"name":"A.J. Brown","sleeperId":"5859","position":"WR"},"redraftValue":4521},{"player":{"name":"Travis Etienne","sleeperId":"7543","position":"RB"},"redraftValue":4352},{"player":{"name":"George Pickens","sleeperId":"8137","position":"WR"},"redraftValue":4465},{"player":{"name":"Josh Jacobs","sleeperId":"5850","position":"RB"},"redraftValue":4257},{"player":{"name":"TreVeyon Henderson","sleeperId":"12529","position":"RB"},"redraftValue":4224},{"player":{"name":"Tetairoa McMillan","sleeperId":"12526","position":"WR"},"redraftValue":4380},{"player":{"name":"Javonte Williams","sleeperId":"7588","position":"RB"},"redraftValue":4083},{"player":{"name":"Quinshon Judkins","sleeperId":"12512","position":"RB"},"redraftValue":3979},{"player":{"name":"Garrett Wilson","sleeperId":"8146","position":"WR"},"redraftValue":4112},{"player":{"name":"Chris Olave","sleeperId":"8144","position":"WR"},"redraftValue":3801},{"player":{"name":"Cam Skattebo","sleeperId":"12481","position":"RB"},"redraftValue":3574},{"player":{"name":"Emeka Egbuka","sleeperId":"12514","position":"WR"},"redraftValue":3702},{"player":{"name":"DeVonta Smith","sleeperId":"7525","position":"WR"},"redraftValue":3633},{"player":{"name":"Lamar Jackson","sleeperId":"4881","position":"QB"},"redraftValue":3663},{"player":{"name":"Bucky Irving","sleeperId":"11584","position":"RB"},"redraftValue":3406},{"player":{"name":"Jadarian Price","sleeperId":"13286","position":"RB"},"redraftValue":3262},{"player":{"name":"Tee Higgins","sleeperId":"6801","position":"WR"},"redraftValue":3348},{"player":{"name":"Ladd McConkey","sleeperId":"11635","position":"WR"},"redraftValue":3346},{"player":{"name":"Drake Maye","sleeperId":"11564","position":"QB"},"redraftValue":3337},{"player":{"name":"Tyler Warren","sleeperId":"12518","position":"TE"},"redraftValue":3261},{"player":{"name":"Joe Burrow","sleeperId":"6770","position":"QB"},"redraftValue":3289},{"player":{"name":"Jaylen Waddle","sleeperId":"7526","position":"WR"},"redraftValue":3143},{"player":{"name":"Rashee Rice","sleeperId":"10229","position":"WR"},"redraftValue":3099},{"player":{"name":"David Montgomery","sleeperId":"5892","position":"RB"},"redraftValue":2959},{"player":{"name":"Zay Flowers","sleeperId":"9997","position":"WR"},"redraftValue":2944},{"player":{"name":"Colston Loveland","sleeperId":"12517","position":"TE"},"redraftValue":2776},{"player":{"name":"D'Andre Swift","sleeperId":"6790","position":"RB"},"redraftValue":2635},{"player":{"name":"Jayden Daniels","sleeperId":"11566","position":"QB"},"redraftValue":2738},{"player":{"name":"Rome Odunze","sleeperId":"11620","position":"WR"},"redraftValue":2560},{"player":{"name":"Patrick Mahomes","sleeperId":"4046","position":"QB"},"redraftValue":2460},{"player":{"name":"Davante Adams","sleeperId":"2133","position":"WR"},"redraftValue":2389},{"player":{"name":"Carnell Tate","sleeperId":"13279","position":"WR"},"redraftValue":2343},{"player":{"name":"Caleb Williams","sleeperId":"11560","position":"QB"},"redraftValue":2379},{"player":{"name":"Mike Evans","sleeperId":"2216","position":"WR"},"redraftValue":2222},{"player":{"name":"Marvin Harrison Jr","sleeperId":"11628","position":"WR"},"redraftValue":2099},{"player":{"name":"DJ Moore","sleeperId":"4983","position":"WR"},"redraftValue":2090},{"player":{"name":"Justin Herbert","sleeperId":"6797","position":"QB"},"redraftValue":2089},{"player":{"name":"Terry McLaurin","sleeperId":"5927","position":"WR"},"redraftValue":2037},{"player":{"name":"Jameson Williams","sleeperId":"8148","position":"WR"},"redraftValue":2034},{"player":{"name":"Luther Burden","sleeperId":"12519","position":"WR"},"redraftValue":1945},{"player":{"name":"Tucker Kraft","sleeperId":"9484","position":"TE"},"redraftValue":1914},{"player":{"name":"Jordyn Tyson","sleeperId":"13281","position":"WR"},"redraftValue":1881},{"player":{"name":"Chuba Hubbard","sleeperId":"7594","position":"RB"},"redraftValue":1802},{"player":{"name":"Tony Pollard","sleeperId":"5967","position":"RB"},"redraftValue":1706},{"player":{"name":"Jalen Hurts","sleeperId":"6904","position":"QB"},"redraftValue":1790},{"player":{"name":"Brian Thomas","sleeperId":"11631","position":"WR"},"redraftValue":1691},{"player":{"name":"Jaylen Warren","sleeperId":"8228","position":"RB"},"redraftValue":1604},{"player":{"name":"George Kittle","sleeperId":"4217","position":"TE"},"redraftValue":1669},{"player":{"name":"RJ Harvey","sleeperId":"12489","position":"RB"},"redraftValue":1591},{"player":{"name":"Makai Lemon","sleeperId":"13294","position":"WR"},"redraftValue":1535},{"player":{"name":"Rico Dowdle","sleeperId":"7021","position":"RB"},"redraftValue":1451},{"player":{"name":"Bhayshul Tuten","sleeperId":"12490","position":"RB"},"redraftValue":1444},{"player":{"name":"DK Metcalf","sleeperId":"5846","position":"WR"},"redraftValue":1453},{"player":{"name":"Kyle Pitts","sleeperId":"7553","position":"TE"},"redraftValue":1446},{"player":{"name":"Aaron Jones","sleeperId":"4199","position":"RB"},"redraftValue":1382},{"player":{"name":"Rhamondre Stevenson","sleeperId":"7611","position":"RB"},"redraftValue":1351},{"player":{"name":"Kenneth Gainwell","sleeperId":"7567","position":"RB"},"redraftValue":1318},{"player":{"name":"Dak Prescott","sleeperId":"3294","position":"QB"},"redraftValue":1337},{"player":{"name":"Sam LaPorta","sleeperId":"10859","position":"TE"},"redraftValue":1306},{"player":{"name":"Alvin Kamara","sleeperId":"4035","position":"RB"},"redraftValue":1249},{"player":{"name":"Travis Kelce","sleeperId":"1466","position":"TE"},"redraftValue":1266},{"player":{"name":"Trevor Lawrence","sleeperId":"7523","position":"QB"},"redraftValue":1286},{"player":{"name":"Bo Nix","sleeperId":"11563","position":"QB"},"redraftValue":1193},{"player":{"name":"Christian Watson","sleeperId":"8167","position":"WR"},"redraftValue":1121},{"player":{"name":"Zach Charbonnet","sleeperId":"9753","position":"RB"},"redraftValue":1057},{"player":{"name":"J.K. Dobbins","sleeperId":"6806","position":"RB"},"redraftValue":1044},{"player":{"name":"Michael Pittman","sleeperId":"6819","position":"WR"},"redraftValue":1081},{"player":{"name":"Courtland Sutton","sleeperId":"5045","position":"WR"},"redraftValue":1057},{"player":{"name":"Rachaad White","sleeperId":"8136","position":"RB"},"redraftValue":965},{"player":{"name":"Alec Pierce","sleeperId":"8142","position":"WR"},"redraftValue":990},{"player":{"name":"Kyle Monangai","sleeperId":"12534","position":"RB"},"redraftValue":937},{"player":{"name":"Jonah Coleman","sleeperId":"13345","position":"RB"},"redraftValue":933},{"player":{"name":"Jaxson Dart","sleeperId":"12508","position":"QB"},"redraftValue":935},{"player":{"name":"Blake Corum","sleeperId":"11586","position":"RB"},"redraftValue":835},{"player":{"name":"Jakobi Meyers","sleeperId":"5947","position":"WR"},"redraftValue":775},{"player":{"name":"Harold Fannin","sleeperId":"12506","position":"TE"},"redraftValue":755},{"player":{"name":"Jordan Addison","sleeperId":"9756","position":"WR"},"redraftValue":746},{"player":{"name":"KC Concepcion","sleeperId":"13298","position":"WR"},"redraftValue":735},{"player":{"name":"Brock Purdy","sleeperId":"8183","position":"QB"},"redraftValue":746},{"player":{"name":"Jacory Croskey-Merritt","sleeperId":"12533","position":"RB"},"redraftValue":685},{"player":{"name":"Jordan Mason","sleeperId":"8408","position":"RB"},"redraftValue":681},{"player":{"name":"Chris Godwin","sleeperId":"4037","position":"WR"},"redraftValue":681},{"player":{"name":"Michael Wilson","sleeperId":"10232","position":"WR"},"redraftValue":641},{"player":{"name":"Jayden Reed","sleeperId":"10222","position":"WR"},"redraftValue":621},{"player":{"name":"Ricky Pearsall","sleeperId":"11638","position":"WR"},"redraftValue":618},{"player":{"name":"Tyrone Tracy","sleeperId":"11655","position":"RB"},"redraftValue":563},{"player":{"name":"Jordan Love","sleeperId":"6804","position":"QB"},"redraftValue":590},{"player":{"name":"Omar Cooper","sleeperId":"13276","position":"WR"},"redraftValue":572},{"player":{"name":"Jonathon Brooks","sleeperId":"11583","position":"RB"},"redraftValue":545},{"player":{"name":"Tyler Allgeier","sleeperId":"8132","position":"RB"},"redraftValue":542},{"player":{"name":"Stefon Diggs","sleeperId":"2449","position":"WR"},"redraftValue":561},{"player":{"name":"Isiah Pacheco","sleeperId":"8205","position":"RB"},"redraftValue":515},{"player":{"name":"Nicholas Singleton","sleeperId":"13288","position":"RB"},"redraftValue":511},{"player":{"name":"Brian Robinson","sleeperId":"8154","position":"RB"},"redraftValue":508},{"player":{"name":"Wan'Dale Robinson","sleeperId":"8126","position":"WR"},"redraftValue":482},{"player":{"name":"Baker Mayfield","sleeperId":"4892","position":"QB"},"redraftValue":490},{"player":{"name":"Jake Ferguson","sleeperId":"8110","position":"TE"},"redraftValue":480},{"player":{"name":"Josh Downs","sleeperId":"9500","position":"WR"},"redraftValue":467},{"player":{"name":"Jared Goff","sleeperId":"3163","position":"QB"},"redraftValue":476},{"player":{"name":"Chris Rodriguez","sleeperId":"10219","position":"RB"},"redraftValue":444},{"player":{"name":"Parker Washington","sleeperId":"9487","position":"WR"},"redraftValue":458},{"player":{"name":"Woody Marks","sleeperId":"12474","position":"RB"},"redraftValue":420},{"player":{"name":"Matthew Stafford","sleeperId":"421","position":"QB"},"redraftValue":437},{"player":{"name":"Denzel Boston","sleeperId":"13346","position":"WR"},"redraftValue":401},{"player":{"name":"Kenyon Sadiq","sleeperId":"13330","position":"TE"},"redraftValue":402},{"player":{"name":"Romeo Doubs","sleeperId":"8121","position":"WR"},"redraftValue":390},{"player":{"name":"Isaiah Likely","sleeperId":"8131","position":"TE"},"redraftValue":378},{"player":{"name":"Dalton Kincaid","sleeperId":"10236","position":"TE"},"redraftValue":373},{"player":{"name":"Emmett Johnson","sleeperId":"13337","position":"RB"},"redraftValue":355},{"player":{"name":"Eli Stowers","sleeperId":"13349","position":"TE"},"redraftValue":355},{"player":{"name":"Quentin Johnston","sleeperId":"9754","position":"WR"},"redraftValue":327},{"player":{"name":"Travis Hunter","sleeperId":"12530","position":"WR"},"redraftValue":315},{"player":{"name":"Kaytron Allen","sleeperId":"13405","position":"RB"},"redraftValue":295},{"player":{"name":"Fernando Mendoza","sleeperId":"13269","position":"QB"},"redraftValue":310},{"player":{"name":"Mark Andrews","sleeperId":"5012","position":"TE"},"redraftValue":305},{"player":{"name":"Matthew Golden","sleeperId":"12501","position":"WR"},"redraftValue":296},{"player":{"name":"Tyler Shough","sleeperId":"12545","position":"QB"},"redraftValue":292},{"player":{"name":"MarShawn Lloyd","sleeperId":"11581","position":"RB"},"redraftValue":275},{"player":{"name":"Cam Ward","sleeperId":"12522","position":"QB"},"redraftValue":270},{"player":{"name":"T.J. Hockenson","sleeperId":"5844","position":"TE"},"redraftValue":257},{"player":{"name":"Dallas Goedert","sleeperId":"5022","position":"TE"},"redraftValue":239},{"player":{"name":"Xavier Worthy","sleeperId":"11624","position":"WR"},"redraftValue":224},{"player":{"name":"C.J. Stroud","sleeperId":"9758","position":"QB"},"redraftValue":222},{"player":{"name":"Kyler Murray","sleeperId":"5849","position":"QB"},"redraftValue":217},{"player":{"name":"Khalil Shakir","sleeperId":"8134","position":"WR"},"redraftValue":207},{"player":{"name":"Hunter Henry","sleeperId":"3214","position":"TE"},"redraftValue":202},{"player":{"name":"Tyjae Spears","sleeperId":"9508","position":"RB"},"redraftValue":183},{"player":{"name":"Sam Darnold","sleeperId":"4943","position":"QB"},"redraftValue":191},{"player":{"name":"Mike Washington","sleeperId":"13305","position":"RB"},"redraftValue":163},{"player":{"name":"Jayden Higgins","sleeperId":"12484","position":"WR"},"redraftValue":162},{"player":{"name":"Keaton Mitchell","sleeperId":"9511","position":"RB"},"redraftValue":156},{"player":{"name":"Rashid Shaheed","sleeperId":"8676","position":"WR"},"redraftValue":161},{"player":{"name":"Chig Okonkwo","sleeperId":"8210","position":"TE"},"redraftValue":151},{"player":{"name":"Kaelon Black","sleeperId":"13414","position":"RB"},"redraftValue":141},{"player":{"name":"Jauan Jennings","sleeperId":"7049","position":"WR"},"redraftValue":134},{"player":{"name":"Germie Bernard","sleeperId":"13274","position":"WR"},"redraftValue":128},{"player":{"name":"Brandon Aiyuk","sleeperId":"6803","position":"WR"},"redraftValue":126},{"player":{"name":"Antonio Williams","sleeperId":"13301","position":"WR"},"redraftValue":125},{"player":{"name":"Oronde Gadsden","sleeperId":"12493","position":"TE"},"redraftValue":126},{"player":{"name":"Juwan Johnson","sleeperId":"7002","position":"TE"},"redraftValue":123},{"player":{"name":"Jalen Coker","sleeperId":"11646","position":"WR"},"redraftValue":120},{"player":{"name":"Jerry Jeudy","sleeperId":"6783","position":"WR"},"redraftValue":117},{"player":{"name":"Tank Bigsby","sleeperId":"9225","position":"RB"},"redraftValue":106},{"player":{"name":"Chris Bell","sleeperId":"13311","position":"WR"},"redraftValue":108},{"player":{"name":"Jalen Nailor","sleeperId":"8180","position":"WR"},"redraftValue":108},{"player":{"name":"Brenton Strange","sleeperId":"9480","position":"TE"},"redraftValue":107},{"player":{"name":"Jalen McMillan","sleeperId":"11618","position":"WR"},"redraftValue":102},{"player":{"name":"Daniel Jones","sleeperId":"5870","position":"QB"},"redraftValue":87},{"player":{"name":"Elijah Sarratt","sleeperId":"13268","position":"WR"},"redraftValue":78},{"player":{"name":"Tyreek Hill","sleeperId":"3321","position":"WR"},"redraftValue":73},{"player":{"name":"De'Zhaun Stribling","sleeperId":"13417","position":"WR"},"redraftValue":69},{"player":{"name":"David Njoku","sleeperId":"4033","position":"TE"},"redraftValue":69},{"player":{"name":"Kaleb Johnson","sleeperId":"12504","position":"RB"},"redraftValue":65},{"player":{"name":"Demond Claiborne","sleeperId":"13347","position":"RB"},"redraftValue":61},{"player":{"name":"Dylan Sampson","sleeperId":"12469","position":"RB"},"redraftValue":60},{"player":{"name":"Bryce Young","sleeperId":"9228","position":"QB"},"redraftValue":62},{"player":{"name":"James Conner","sleeperId":"4137","position":"RB"},"redraftValue":54},{"player":{"name":"Malachi Fields","sleeperId":"13285","position":"WR"},"redraftValue":47},{"player":{"name":"Zachariah Branch","sleeperId":"13320","position":"WR"},"redraftValue":44},{"player":{"name":"Braelon Allen","sleeperId":"11576","position":"RB"},"redraftValue":42},{"player":{"name":"Malik Willis","sleeperId":"8161","position":"QB"},"redraftValue":40},{"player":{"name":"Trey Benson","sleeperId":"11589","position":"RB"},"redraftValue":35},{"player":{"name":"Dalton Schultz","sleeperId":"5001","position":"TE"},"redraftValue":31},{"player":{"name":"Tank Dell","sleeperId":"9502","position":"WR"},"redraftValue":26},{"player":{"name":"Skyler Bell","sleeperId":"13402","position":"WR"},"redraftValue":24},{"player":{"name":"Chris Brazzell","sleeperId":"13353","position":"WR"},"redraftValue":23},{"player":{"name":"Isaac TeSlaa","sleeperId":"12535","position":"WR"},"redraftValue":19},{"player":{"name":"Tre' Harris","sleeperId":"12509","position":"WR"},"redraftValue":19},{"player":{"name":"Ted Hurst","sleeperId":"13317","position":"WR"},"redraftValue":6},{"player":{"name":"Ty Simpson","sleeperId":"13275","position":"QB"},"redraftValue":2},{"player":{"name":"Emanuel Wilson","sleeperId":"11435","position":"RB"},"redraftValue":1}];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// THEME — NFL broadcast aesthetic: deep navy, steel, with red energy,
// gold for prestige (champions/winners), green for the good side.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const T = {
  bg:       '#080b11',
  panel:    '#10161f',
  panel2:   '#161e2a',
  raised:   '#1c2632',
  border:   '#26313f',
  borderHi: '#36465a',
  text:     '#eef3f9',
  dim:      '#8493a6',
  faint:    '#54606f',
  red:      '#e8112d',
  redDk:    '#a60a1f',
  green:    '#28d07b',
  gold:     '#ffc233',
  blue:     '#41a6ff',
};
const FONT_HEAD = "'Oswald', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
const FONT_BODY = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CLAUDE CALL — uses the Claude.ai artifact runtime (window.claude).
// complete() takes a STRING prompt and resolves to a STRING. We flatten
// system + conversation into one prompt and parse defensively. No API key.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async function claudeCall(messages, systemPrompt) {
  const runtime = (typeof window !== 'undefined') ? window.claude : null;
  if (!runtime || typeof runtime.complete !== 'function') {
    throw new Error('Open this on Claude.ai to use the AI features.');
  }
  const trimmed = messages.slice(-20);
  const convo = trimmed
    .map(m => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.content}`)
    .join('\n\n');
  const prompt = `${systemPrompt}\n\n${convo}\n\nAssistant:`;
  try {
    const res = await runtime.complete(prompt);
    if (typeof res === 'string') return res;
    if (res?.content?.[0]?.text) return res.content[0].text;
    if (typeof res?.completion === 'string') return res.completion;
    if (typeof res?.text === 'string') return res.text;
    return String(res);
  } catch (e) {
    const msg = String(e?.message || e);
    if (/model/i.test(msg) || /404/.test(msg) || e?.status === 404) throw new Error('MODEL_ERROR');
    throw e;
  }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SHARED CHAT COMPONENT (used by Stats and Banter tabs)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function ChatTab({ systemPrompt, chips, placeholder, errorMsg, intro }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const bottomRef = useRef(null);
  const taRef = useRef(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);

  const autoResize = () => {
    const ta = taRef.current; if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = Math.min(ta.scrollHeight, 120) + 'px';
  };

  const send = async (text) => {
    const t = (text || input).trim();
    if (!t || loading) return;
    const next = [...messages, { role: 'user', content: t }];
    setMessages(next); setInput(''); setLoading(true);
    if (taRef.current) taRef.current.style.height = 'auto';
    try {
      const apiMsgs = next.slice(-20)
        .filter(m => m.role === 'user' || m.role === 'assistant')
        .map(m => ({ role: m.role, content: m.content }));
      const reply = await claudeCall(apiMsgs, systemPrompt);
      setMessages(p => [...p, { role: 'assistant', content: reply }]);
    } catch (e) {
      const txt = e?.message === 'MODEL_ERROR' ? 'Model hiccup — give it another go.' : errorMsg;
      setMessages(p => [...p, { role: 'error', content: txt }]);
    } finally { setLoading(false); }
  };

  const bubbleUser = { alignSelf:'flex-end', background:`linear-gradient(135deg, ${T.red}, ${T.redDk})`, color:'#fff', borderRadius:'14px 14px 3px 14px', padding:'10px 14px', maxWidth:'82%', fontSize:14.5, lineHeight:1.5, boxShadow:'0 2px 10px rgba(232,17,45,0.25)', whiteSpace:'pre-wrap' };
  const bubbleBot  = { alignSelf:'flex-start', background:T.panel2, color:T.text, borderLeft:`3px solid ${T.red}`, borderRadius:'4px 14px 14px 14px', padding:'10px 14px', maxWidth:'82%', fontSize:14.5, lineHeight:1.55, whiteSpace:'pre-wrap', boxShadow:'0 1px 6px rgba(0,0,0,0.3)' };
  const bubbleErr  = { ...bubbleBot, borderLeft:`3px solid ${T.gold}`, color:T.gold };

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', background:T.bg }}>
      {/* Chips */}
      <div style={{ display:'flex', gap:8, padding:'10px 12px', borderBottom:`1px solid ${T.border}`, overflowX:'auto', flexShrink:0, background:T.panel }}>
        {chips.map((c, i) => (
          <button key={i} onClick={() => send(c)} disabled={loading}
            style={{ background:T.raised, border:`1px solid ${T.borderHi}`, color:T.text, borderRadius:7, padding:'7px 12px', fontSize:12.5, fontWeight:600, cursor: loading ? 'default' : 'pointer', whiteSpace:'nowrap', opacity: loading ? 0.45 : 1, flexShrink:0, letterSpacing:'0.2px' }}>
            {c}
          </button>
        ))}
      </div>

      {/* Messages */}
      <div style={{ flexGrow:1, overflowY:'auto', padding:14, display:'flex', flexDirection:'column', gap:11 }}>
        {messages.length === 0 && !loading && (
          <div style={{ margin:'auto', textAlign:'center', color:T.faint, fontSize:13.5, maxWidth:260, lineHeight:1.6 }}>
            {intro}
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} className="msg-in" style={m.role === 'user' ? bubbleUser : m.role === 'error' ? bubbleErr : bubbleBot}>
            {m.content}
          </div>
        ))}
        {loading && (
          <div style={bubbleBot}>
            <span className="ld" /><span className="ld" /><span className="ld" />
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div style={{ display:'flex', gap:8, padding:'10px 12px', borderTop:`1px solid ${T.border}`, background:T.panel, flexShrink:0 }}>
        <textarea
          ref={taRef} rows={1} value={input}
          onChange={e => setInput(e.target.value)}
          onInput={autoResize}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
          placeholder={placeholder}
          style={{ flex:1, background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:9, padding:'11px 12px', fontSize:15, resize:'none', outline:'none', lineHeight:1.4 }}
        />
        <button onClick={() => send()} disabled={loading || !input.trim()}
          style={{ background: loading || !input.trim() ? T.raised : `linear-gradient(135deg, ${T.red}, ${T.redDk})`, color: loading || !input.trim() ? T.faint : '#fff', border:'none', borderRadius:9, padding:'0 18px', fontWeight:700, fontSize:13, letterSpacing:'0.5px', textTransform:'uppercase', cursor: loading || !input.trim() ? 'default' : 'pointer', alignSelf:'stretch', flexShrink:0, fontFamily:FONT_HEAD }}>
          Send
        </button>
      </div>
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// STATS TAB
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function StatsTab() {
  const systemPrompt = `You are the league statistician for the Borehamwood Plancy League. Answer ONLY from the loaded history and stats data provided — all-time and per-season records, head-to-heads, champions by season, highest/lowest weeks, points trends across 2023-2025. Cite exact figures. NEVER invent or estimate a number; if it isn't in the provided data, say so plainly. Minimal banter — this is the record book.

LEAGUE DATA:
${JSON.stringify(HISTORY_DATA)}

STATS DATA:
${JSON.stringify(STATS_DATA)}`;

  return (
    <ChatTab
      systemPrompt={systemPrompt}
      chips={['Most titles 2023-2025?', 'AlastairL vs dpol H2H', 'Highest score ever?', 'Biggest improver?']}
      placeholder="Ask about league stats…"
      errorMsg="Something went wrong — please try again."
      intro="The record book is open. Ask about champions, head-to-heads, high scores, or season trends."
    />
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// BANTER TAB
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const LEAGUE_FACTS = `Borehamwood Plancy League. 1-QB redraft, WR/RB/TE flex, half-PPR, 8 teams. History covers 2023-2025.
2025 champion: Fourth and Golda Meir (@AlastairL), 11-5, first-round bye Wk15, beat @dpol 143.96-118.58 in the final.
@dpol (Plancey Neutral) won Wk3 2025 by just 0.02 points, then lost the final by 25.
@GSac (This One Really Hurts) posted a monstrous 202.36 in Wk12 2025 and still didn't make the final.
@sanfbe (J'Allen Plancey z'l) is AlastairL's bogey team — beat him twice in 2025 regular season.
Managers: AlastairL/Fourth and Golda Meir; dpol/Plancey Neutral; GSac/This One Really Hurts; sanfbe/J'Allen Plancey z'l; saulgoat/Love Thy Naber; drjkay/A Rookie Error; benjlev/Team Benjlev; joshjr11/Denver Brochos.`;

function BanterTab() {
  const systemPrompt = `You are the resident wind-up merchant of the Borehamwood Plancy League. Voice: bone-dry British banter, treating this low-stakes hobby with the utmost mock-gravity. Roast everyone, the champion most of all. Never cruel, always funny. Use the LORE and history for material. Be loose and playful, but do not fabricate hard stats — if you cite a number, it must be real.

${LEAGUE_FACTS}

LEAGUE LORE (nicknames, running jokes, personal history):
${LORE}

FULL HISTORY:
${JSON.stringify(HISTORY_DATA)}`;

  return (
    <ChatTab
      systemPrompt={systemPrompt}
      chips={['Roast the 2025 champion', 'Unluckiest manager ever?', "This week's smack bulletin"]}
      placeholder="Start some trouble…"
      errorMsg="Blimey, something went wrong — give it another go."
      intro="Pull up a chair. Ask for a roast, a smack-talk bulletin, or just stir the pot."
    />
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TRADE GRADER — module-level helpers (hoisted to prevent remount)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function TradePanel({ label, side, team, setTeam, text, setText, teamOpts }) {
  const accent = side === 'A' ? T.blue : T.red;
  return (
    <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderTop:`3px solid ${accent}`, borderRadius:'4px 4px 10px 10px', padding:12, flex:1, minWidth:0 }}>
      <div style={{ display:'flex', alignItems:'center', gap:7, marginBottom:9 }}>
        <span style={{ background:accent, color:'#fff', fontFamily:FONT_HEAD, fontWeight:700, fontSize:12, width:20, height:20, borderRadius:4, display:'flex', alignItems:'center', justifyContent:'center' }}>{side}</span>
        <span style={{ color:T.dim, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.06em', fontFamily:FONT_HEAD }}>{label}</span>
      </div>
      <select value={team} onChange={e => setTeam(e.target.value)}
        style={{ background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:7, padding:9, width:'100%', marginBottom:8, fontSize:13.5 }}>
        {teamOpts}
      </select>
      <textarea value={text} onChange={e => setText(e.target.value)} placeholder={"One player per line\ne.g. Ja'Marr Chase"}
        style={{ background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:7, padding:10, width:'100%', minHeight:96, fontSize:13.5, resize:'vertical', boxSizing:'border-box', lineHeight:1.5 }} />
    </div>
  );
}

function PlayerRow({ p }) {
  return (
    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'5px 0', borderBottom:`1px solid ${T.border}`, fontSize:13.5 }}>
      <span style={{ color: p.found ? T.text : T.gold }}>{p.found ? p.officialName : `${p.input} ⚠`}</span>
      <span style={{ color: p.found ? T.dim : T.gold, fontSize:12.5, marginLeft:8, fontFamily:FONT_HEAD, fontWeight:600 }}>{p.found ? p.value.toLocaleString() : 'no match'}</span>
    </div>
  );
}

function normalizeName(str) {
  return str.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}

function TradeGrader() {
  const rostersData = ROSTERS_DATA;
  const tradeValues = TRADE_VALUES;
  const teamKeys = useMemo(() => Object.keys(rostersData || {}), [rostersData]);

  const [teamA, setTeamA] = useState(teamKeys[0] || '');
  const [teamB, setTeamB] = useState(teamKeys[1] || '');
  const [sideAText, setSideAText] = useState('');
  const [sideBText, setSideBText] = useState('');
  const [result, setResult] = useState(null);
  const [verdict, setVerdict] = useState(null);
  const [verdictLoading, setVerdictLoading] = useState(false);
  const [verdictError, setVerdictError] = useState(false);

  // Inject spin keyframe once
  useEffect(() => {
    if (document.getElementById('tg-spin')) return;
    const s = document.createElement('style');
    s.id = 'tg-spin';
    s.textContent = '@keyframes tg-spin { to { transform: rotate(360deg); } }';
    document.head.appendChild(s);
  }, []);

  const { idMap, nameMap } = useMemo(() => {
    const id = new Map(), nm = new Map();
    for (const { player, redraftValue } of (tradeValues || [])) {
      const val = redraftValue || 0;
      if (player.sleeperId) id.set(player.sleeperId, { value: val, officialName: player.name });
      nm.set(normalizeName(player.name), { value: val, sleeperId: player.sleeperId, officialName: player.name });
    }
    return { idMap: id, nameMap: nm };
  }, [tradeValues]);

  function lookupPlayer(inputText) {
    const n = normalizeName(inputText);
    if (nameMap.has(n)) { const e = nameMap.get(n); return { found:true, value:e.value, officialName:e.officialName, sleeperId:e.sleeperId }; }
    for (const [key, e] of nameMap) { if (key.includes(n) || n.includes(key)) return { found:true, value:e.value, officialName:e.officialName, sleeperId:e.sleeperId }; }
    return { found:false, value:0, officialName:inputText };
  }

  function gradeTrade() {
    const parse = txt => txt.split('\n').map(l => l.trim()).filter(Boolean).map(line => ({ input:line, ...lookupPlayer(line) }));
    const sA = parse(sideAText), sB = parse(sideBText);
    const tA = sA.reduce((s,p) => s+p.value, 0), tB = sB.reduce((s,p) => s+p.value, 0);
    const gap = Math.abs(tA - tB), gapPct = (gap / Math.max(tA, tB, 1)) * 100;
    const winner = gapPct < 5 ? 'even' : tA > tB ? 'A' : 'B';
    const tier = gapPct < 5 ? 'DEAD EVEN' : gapPct < 12 ? 'SLIGHT EDGE' : gapPct < 25 ? 'CLEAR WINNER' : 'LOPSIDED';
    const tierIcon = gapPct < 5 ? '⚖️' : gapPct < 12 ? '📊' : gapPct < 25 ? '🏆' : '🚨';
    let addOns = [];
    if (winner !== 'even' && rostersData) {
      const wTeam = winner === 'A' ? teamA : teamB;
      const wSide = winner === 'A' ? sA : sB;
      const exclude = new Set(wSide.map(p => p.officialName));
      addOns = (rostersData[wTeam] || [])
        .map(rp => ({ name: idMap.get(rp.id)?.officialName || rp.name, value: idMap.get(rp.id)?.value || 0, id: rp.id }))
        .filter(rp => !exclude.has(rp.name) && rp.value > 0)
        .sort((a,b) => Math.abs(a.value - gap) - Math.abs(b.value - gap))
        .slice(0, 3);
    }
    setResult({ sA, sB, tA, tB, winner, tier, tierIcon, gap, gapPct, addOns });
    setVerdict(null); setVerdictError(false);
  }

  async function getVerdict() {
    if (!result) return;
    setVerdictLoading(true); setVerdictError(false); setVerdict(null);
    const { sA, sB, tA, tB, winner, tier, gap, gapPct, addOns } = result;
    const sys = "You are the wind-up merchant of the Borehamwood Plancy League. Give a quick, funny verdict on this trade in the Commissioner's voice — bone-dry British football banter, mock gravity. The numbers are computed for you — do NOT recalculate. Just react with wit. Keep it to 2-4 sentences.";
    const msg = `Trade grade:
Side A (${teamA}) gives up: ${sA.map(p=>`${p.officialName} (${p.value})`).join(', ')} — Total: ${tA}
Side B (${teamB}) gives up: ${sB.map(p=>`${p.officialName} (${p.value})`).join(', ')} — Total: ${tB}
Verdict: ${tier}. ${winner==='even'?'Dead even.':`Side ${winner} wins by ${gap.toFixed(0)} pts (${gapPct.toFixed(1)}%).`}${addOns.length?`\nSuggested add-on: ${addOns.map(a=>`${a.name} (${a.value})`).join(' or ')}`:''}
Give your verdict.`;
    try {
      const r = await claudeCall([{ role:'user', content:msg }], sys);
      setVerdict(r);
    } catch(e) { setVerdictError(true); }
    finally { setVerdictLoading(false); }
  }

  const teamOpts = teamKeys.map(k => <option key={k} value={k}>{k}</option>);
  const winA = result?.winner === 'A', winB = result?.winner === 'B';

  return (
    <div style={{ background:T.bg, color:T.text, padding:14, overflowY:'auto', height:'100%', boxSizing:'border-box' }}>
      {/* Inputs */}
      <div style={{ display:'flex', flexWrap:'wrap', gap:10, alignItems:'stretch' }}>
        <TradePanel side="A" label="Side A gives up" team={teamA} setTeam={setTeamA} text={sideAText} setText={setSideAText} teamOpts={teamOpts} />
        <TradePanel side="B" label="Side B gives up" team={teamB} setTeam={setTeamB} text={sideBText} setText={setSideBText} teamOpts={teamOpts} />
      </div>

      <button onClick={gradeTrade} disabled={!sideAText.trim() && !sideBText.trim()}
        style={{ width:'100%', background:(!sideAText.trim()&&!sideBText.trim()) ? T.raised : `linear-gradient(135deg, ${T.red}, ${T.redDk})`, color:(!sideAText.trim()&&!sideBText.trim()) ? T.faint : '#fff', border:'none', borderRadius:10, padding:14, fontSize:15, fontWeight:700, letterSpacing:'1px', textTransform:'uppercase', fontFamily:FONT_HEAD, cursor:(!sideAText.trim()&&!sideBText.trim())?'default':'pointer', marginTop:11, boxShadow:(!sideAText.trim()&&!sideBText.trim())?'none':'0 3px 14px rgba(232,17,45,0.3)' }}>
        Grade This Trade
      </button>

      {result && (
        <div className="msg-in" style={{ marginTop:16 }}>
          {/* Scoreboard */}
          <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderRadius:12, overflow:'hidden', marginBottom:12 }}>
            <div style={{ display:'flex', alignItems:'stretch' }}>
              <div style={{ flex:1, padding:'14px 10px', textAlign:'center', background: winA ? 'rgba(40,208,123,0.08)' : 'transparent', borderRight:`1px solid ${T.border}` }}>
                <div style={{ fontSize:10, color:T.faint, textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:4, fontFamily:FONT_HEAD }}>Side A</div>
                <div style={{ fontFamily:FONT_HEAD, fontWeight:700, fontSize:28, color: winA ? T.green : T.text, lineHeight:1 }}>{result.tA.toLocaleString()}</div>
                {winA && <div style={{ fontSize:10, color:T.green, fontWeight:700, marginTop:3, textTransform:'uppercase', letterSpacing:'0.05em' }}>▲ Winner</div>}
              </div>
              <div style={{ display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', padding:'0 14px', minWidth:96 }}>
                <div style={{ fontSize:20 }}>{result.tierIcon}</div>
                <div style={{ fontFamily:FONT_HEAD, fontWeight:700, fontSize:13, color:T.gold, letterSpacing:'0.04em', textAlign:'center', lineHeight:1.1, marginTop:2 }}>{result.tier}</div>
                {result.winner !== 'even' && (
                  <div style={{ fontSize:10.5, color:T.dim, marginTop:3 }}>by {result.gap.toLocaleString()} ({result.gapPct.toFixed(0)}%)</div>
                )}
              </div>
              <div style={{ flex:1, padding:'14px 10px', textAlign:'center', background: winB ? 'rgba(40,208,123,0.08)' : 'transparent', borderLeft:`1px solid ${T.border}` }}>
                <div style={{ fontSize:10, color:T.faint, textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:4, fontFamily:FONT_HEAD }}>Side B</div>
                <div style={{ fontFamily:FONT_HEAD, fontWeight:700, fontSize:28, color: winB ? T.green : T.text, lineHeight:1 }}>{result.tB.toLocaleString()}</div>
                {winB && <div style={{ fontSize:10, color:T.green, fontWeight:700, marginTop:3, textTransform:'uppercase', letterSpacing:'0.05em' }}>▲ Winner</div>}
              </div>
            </div>
          </div>

          {/* Player breakdown */}
          <div style={{ display:'flex', flexWrap:'wrap', gap:10, marginBottom:12 }}>
            <div style={{ flex:1, minWidth:140, background:T.panel, border:`1px solid ${T.border}`, borderRadius:10, padding:'10px 12px' }}>
              <div style={{ color:T.blue, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em', marginBottom:6, fontFamily:FONT_HEAD }}>{teamA || 'Side A'}</div>
              {result.sA.length ? result.sA.map((p,i) => <PlayerRow key={i} p={p} />) : <div style={{ color:T.faint, fontSize:12.5 }}>—</div>}
            </div>
            <div style={{ flex:1, minWidth:140, background:T.panel, border:`1px solid ${T.border}`, borderRadius:10, padding:'10px 12px' }}>
              <div style={{ color:T.red, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em', marginBottom:6, fontFamily:FONT_HEAD }}>{teamB || 'Side B'}</div>
              {result.sB.length ? result.sB.map((p,i) => <PlayerRow key={i} p={p} />) : <div style={{ color:T.faint, fontSize:12.5 }}>—</div>}
            </div>
          </div>

          {/* Add-ons */}
          {result.winner !== 'even' && result.addOns.length > 0 && (
            <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderLeft:`3px solid ${T.gold}`, borderRadius:'4px 10px 10px 4px', padding:'10px 12px', marginBottom:12 }}>
              <div style={{ color:T.gold, fontSize:11, marginBottom:6, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.04em', fontFamily:FONT_HEAD }}>To even it up, {result.winner==='A' ? teamA : teamB} could add</div>
              {result.addOns.map((a,i) => (
                <div key={i} style={{ display:'flex', justifyContent:'space-between', fontSize:13.5, padding:'3px 0' }}>
                  <span>{a.name}</span><span style={{ color:T.dim, fontFamily:FONT_HEAD, fontWeight:600 }}>{a.value.toLocaleString()}</span>
                </div>
              ))}
            </div>
          )}

          {/* Verdict button */}
          <button onClick={getVerdict} disabled={verdictLoading}
            style={{ width:'100%', background:T.panel, border:`1px solid ${T.gold}`, color:T.gold, borderRadius:10, padding:'13px 20px', fontSize:13.5, fontWeight:700, letterSpacing:'0.5px', textTransform:'uppercase', fontFamily:FONT_HEAD, cursor: verdictLoading ? 'default' : 'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:9, opacity: verdictLoading ? 0.7 : 1 }}>
            {verdictLoading && <span style={{ width:14, height:14, border:`2px solid ${T.gold}`, borderTopColor:'transparent', borderRadius:'50%', display:'inline-block', animation:'tg-spin 0.8s linear infinite' }} />}
            🎙 The Commissioner's Verdict
          </button>

          {/* Verdict / error */}
          {(verdict || verdictError) && (
            <div className="msg-in" style={{ background:T.panel2, border:`1px solid ${verdictError ? T.gold : T.border}`, borderLeft:`3px solid ${verdictError ? T.gold : T.red}`, borderRadius:'4px 12px 12px 4px', padding:14, color: verdictError ? T.gold : T.text, whiteSpace:'pre-wrap', marginTop:10, fontSize:14, lineHeight:1.6 }}>
              {verdictError ? 'The Commissioner is unavailable — give it another go.' : verdict}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// APP SHELL
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const GLOBAL_CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&display=swap');
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #080b11; -webkit-font-smoothing: antialiased; }
  ::-webkit-scrollbar { width: 4px; height: 4px; }
  ::-webkit-scrollbar-thumb { background: #26313f; border-radius: 2px; }
  ::-webkit-scrollbar-track { background: transparent; }
  @keyframes ld-pulse { 0%,80%,100%{opacity:.2;transform:scale(.7)} 40%{opacity:1;transform:scale(1)} }
  .ld { display:inline-block; width:7px; height:7px; background:#e8112d; border-radius:50%; margin:0 2px; animation:ld-pulse 1.4s infinite ease-in-out both; }
  .ld:nth-child(2){animation-delay:.2s} .ld:nth-child(3){animation-delay:.4s}
  @keyframes fadeUp { from { opacity:0; transform:translateY(6px); } to { opacity:1; transform:none; } }
  .msg-in { animation: fadeUp .25s ease both; }
  button { font-family: inherit; }
  textarea, select, input { font-family: inherit; }
  textarea:focus, select:focus, input:focus { border-color:#36465a; }
  select option { background: #161e2a; color: #eef3f9; }
`;

const TABS = [
  { id:'stats',  icon:'📊', label:'Stats'  },
  { id:'banter', icon:'🎙', label:'Banter' },
  { id:'trade',  icon:'⚖️', label:'Trades' },
];

export default function App() {
  const [tab, setTab] = useState('stats');

  useEffect(() => {
    if (document.getElementById('commissioner-css')) return;
    const el = document.createElement('style');
    el.id = 'commissioner-css';
    el.textContent = GLOBAL_CSS;
    document.head.appendChild(el);
  }, []);

  const appStyle = {
    display:'flex', flexDirection:'column',
    height:'100dvh', maxWidth:480, margin:'0 auto',
    background:T.bg, color:T.text,
    fontFamily:FONT_BODY,
    overflow:'hidden',
    boxShadow:'0 0 60px rgba(0,0,0,0.6)',
  };

  const Tab = ({ id, icon, label }) => {
    const active = tab === id;
    return (
      <button onClick={() => setTab(id)} style={{
        flex:1, padding:'11px 4px 9px', background: active ? T.panel2 : 'transparent', border:'none',
        borderBottom: active ? `3px solid ${T.red}` : '3px solid transparent',
        color: active ? T.text : T.faint,
        cursor:'pointer', transition:'all 0.15s',
        display:'flex', flexDirection:'column', alignItems:'center', gap:3,
      }}>
        <span style={{ fontSize:16, filter: active ? 'none' : 'grayscale(0.6) opacity(0.7)' }}>{icon}</span>
        <span style={{ fontSize:11.5, fontWeight:700, letterSpacing:'0.06em', textTransform:'uppercase', fontFamily:FONT_HEAD }}>{label}</span>
      </button>
    );
  };

  return (
    <div style={appStyle}>
      {/* Top accent stripe */}
      <div style={{ height:3, background:`linear-gradient(90deg, ${T.red} 0%, ${T.gold} 50%, ${T.red} 100%)`, flexShrink:0 }} />

      {/* Header */}
      <div style={{ display:'flex', alignItems:'center', gap:11, padding:'12px 16px', background:`linear-gradient(180deg, ${T.panel} 0%, ${T.bg} 100%)`, borderBottom:`1px solid ${T.border}`, flexShrink:0 }}>
        <div style={{ width:38, height:38, borderRadius:9, background:`linear-gradient(135deg, ${T.red}, ${T.redDk})`, display:'flex', alignItems:'center', justifyContent:'center', fontFamily:FONT_HEAD, fontWeight:700, fontSize:22, color:'#fff', boxShadow:'0 2px 10px rgba(232,17,45,0.35)', borderBottom:`2px solid ${T.gold}` }}>C</div>
        <div style={{ flex:1, minWidth:0 }}>
          <div style={{ fontFamily:FONT_HEAD, fontSize:21, fontWeight:700, color:T.text, letterSpacing:'0.04em', lineHeight:1, textTransform:'uppercase' }}>
            The Commissioner
          </div>
          <div style={{ fontSize:10, color:T.dim, marginTop:3, letterSpacing:'0.14em', textTransform:'uppercase', fontFamily:FONT_HEAD, fontWeight:500 }}>
            Borehamwood Plancy League
          </div>
        </div>
        <div style={{ fontFamily:FONT_HEAD, fontWeight:700, fontSize:11, color:T.gold, border:`1px solid ${T.borderHi}`, borderRadius:5, padding:'4px 8px', letterSpacing:'0.05em', whiteSpace:'nowrap' }}>
          ’25 SZN
        </div>
      </div>

      {/* Tab bar */}
      <div style={{ display:'flex', background:T.panel, borderBottom:`1px solid ${T.border}`, flexShrink:0 }}>
        {TABS.map(t => <Tab key={t.id} {...t} />)}
      </div>

      {/* Content */}
      <div style={{ flex:1, overflow:'hidden', display:'flex', flexDirection:'column' }}>
        {tab === 'stats'  && <StatsTab />}
        {tab === 'banter' && <BanterTab />}
        {tab === 'trade'  && <TradeGrader />}
      </div>
    </div>
  );
}
