// ╔══════════════════════════════════════════════════════════════╗
// ║  PlAIncy — Borehamwood Plancy League                         ║
// ║  Generated by scripts/build-artifact.js — all data inlined  ║
// ║  Edit commissioner.template.jsx, then run build-artifact.js  ║
// ╚══════════════════════════════════════════════════════════════╝

const { useState, useEffect, useRef, useMemo } = React;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// LORE ← FILL THIS IN BEFORE SHARING
// Fed directly to the Banter tab system prompt.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const LORE = `
(Replace this block with your league lore before publishing.)

Suggestions:
- AlastairL won the 2025 title despite sanfbe beating him twice in the regular season.
- dpol won a game in Week 3 by 0.02 points and never lets anyone forget it.
- GSac put up 202.36 in Wk12 2025 — the highest score in league history — and still didn't make the final.
- benjlev went 0-14 in 2024. A perfect record of futility. The Borehamwood Spiral.
- Add your own: nicknames, draft regrets, waiver crimes, feuds, superstitions...
`;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// INLINED DATA — baked-in snapshot, always works.
// On load we also attempt a live fetch from JSDelivr / GitHub Pages.
// If the live fetch succeeds the data silently upgrades and the header
// shows a green LIVE badge. If blocked, the cached snapshot is used.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const HISTORY_DATA = __HISTORY__;
const STATS_DATA   = __STATS__;
const ROSTERS_DATA = __ROSTERS__;
const TRADE_VALUES = __TRADES__;

// Candidate CDN/Pages URLs tried in order — first success wins
const REPO = 'alastairlivingston-sudo/sleeper-league-app-3';
const DATA_SOURCES = [
  // JSDelivr: global CDN, serves any public GitHub file with CORS headers
  {
    history: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/public/data/history.json',
    stats:   'https://cdn.jsdelivr.net/gh/' + REPO + '@main/public/data/stats.json',
    rosters: 'https://cdn.jsdelivr.net/gh/' + REPO + '@main/public/data/rosters.json',
    trades:  'https://cdn.jsdelivr.net/gh/' + REPO + '@main/public/data/fc-values.json',
  },
  // GitHub Pages (enabled via workflow)
  {
    history: 'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1] + '/public/data/history.json',
    stats:   'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1] + '/public/data/stats.json',
    rosters: 'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1] + '/public/data/rosters.json',
    trades:  'https://alastairlivingston-sudo.github.io/' + REPO.split('/')[1] + '/public/data/fc-values.json',
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// THEME — deep navy / red energy / gold prestige / green for wins
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const T = {
  bg:       '#07090f',
  panel:    '#0f1520',
  panel2:   '#141d2b',
  raised:   '#1a2334',
  border:   '#232f3e',
  borderHi: '#304050',
  text:     '#eef3f9',
  dim:      '#7a8fa6',
  faint:    '#4a5a6a',
  red:      '#e8112d',
  redDk:    '#b00a23',
  green:    '#22c96f',
  gold:     '#ffbe2e',
  blue:     '#3b9eff',
};
const FH = "'Impact','Arial Black','Helvetica Neue',Arial,sans-serif"; // headings
const FB = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif"; // body

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CLAUDE CALL
// window.claude.complete(prompt:string) → string (artifact runtime)
// No API key — viewer's own Claude.ai session is used.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
async function claudeCall(messages, systemPrompt) {
  const runtime = typeof window !== 'undefined' ? window.claude : null;
  if (!runtime || typeof runtime.complete !== 'function') {
    throw new Error('Open this artifact on Claude.ai to use AI features.');
  }
  const convo = messages.slice(-20)
    .filter(m => m.role === 'user' || m.role === 'assistant')
    .map(m => `${m.role === 'user' ? 'User' : 'Assistant'}: ${m.content}`)
    .join('\n\n');
  const prompt = `${systemPrompt}\n\n${convo}\n\nAssistant:`;
  try {
    const res = await runtime.complete(prompt);
    if (typeof res === 'string') return res;
    if (res?.content?.[0]?.text) return res.content[0].text;
    if (typeof res?.completion === 'string') return res.completion;
    return String(res);
  } catch (e) {
    const msg = String(e?.message || e);
    if (/model/i.test(msg) || /404/.test(msg) || e?.status === 404) throw new Error('MODEL_ERROR');
    throw e;
  }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// LIVE DATA HOOK
// Tries each source in DATA_SOURCES order; falls back to inlined.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function useLeagueData() {
  const [data, setData] = useState({
    history: HISTORY_DATA,
    stats:   STATS_DATA,
    rosters: ROSTERS_DATA,
    trades:  TRADE_VALUES,
    source:  'cached',
  });

  useEffect(() => {
    (async () => {
      for (const urls of DATA_SOURCES) {
        try {
          const [history, stats, rosters, trades] = await Promise.all(
            Object.values(urls).map(url =>
              fetch(url).then(r => { if (!r.ok) throw new Error(r.status); return r.json(); })
            )
          );
          setData({ history, stats, rosters, trades, source: 'live' });
          return; // first success wins
        } catch { /* try next source */ }
      }
      // All sources blocked — keep inlined data, mark cached
      setData(d => ({ ...d, source: 'cached' }));
    })();
  }, []);

  return data;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SHARED CHAT COMPONENT
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function ChatTab({ systemPrompt, chips, placeholder, errorMsg, intro }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput]       = useState('');
  const [loading, setLoading]   = useState(false);
  const bottomRef = useRef(null);
  const taRef     = useRef(null);

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);

  const autoResize = () => {
    const ta = taRef.current; if (!ta) return;
    ta.style.height = 'auto';
    ta.style.height = Math.min(ta.scrollHeight, 120) + 'px';
  };

  const send = async (text) => {
    const t = (text || input).trim();
    if (!t || loading) return;
    const next = [...messages, { role: 'user', content: t }];
    setMessages(next); setInput(''); setLoading(true);
    if (taRef.current) taRef.current.style.height = 'auto';
    try {
      const reply = await claudeCall(
        next.filter(m => m.role === 'user' || m.role === 'assistant'),
        systemPrompt
      );
      setMessages(p => [...p, { role: 'assistant', content: reply }]);
    } catch (e) {
      const txt = e?.message === 'MODEL_ERROR' ? 'Model hiccup — try again.' : errorMsg;
      setMessages(p => [...p, { role: 'error', content: txt }]);
    } finally { setLoading(false); }
  };

  return (
    <div style={{ display:'flex', flexDirection:'column', height:'100%', background:T.bg }}>
      {/* Chips */}
      <div style={{ display:'flex', gap:7, padding:'9px 12px', borderBottom:`1px solid ${T.border}`, overflowX:'auto', flexShrink:0, background:T.panel }}>
        {chips.map((c, i) => (
          <button key={i} className="chip" onClick={() => send(c)} disabled={loading}>
            {c}
          </button>
        ))}
      </div>

      {/* Messages */}
      <div style={{ flexGrow:1, overflowY:'auto', padding:14, display:'flex', flexDirection:'column', gap:11 }}>
        {messages.length === 0 && !loading && (
          <div style={{ margin:'auto', textAlign:'center', color:T.faint, fontSize:13.5, maxWidth:280, lineHeight:1.7, paddingTop:20 }}>
            {intro}
          </div>
        )}
        {messages.map((m, i) => (
          <div key={i} className={`msg-in bubble-${m.role}`}>
            {m.content}
          </div>
        ))}
        {loading && (
          <div className="bubble-assistant">
            <span className="ld" /><span className="ld" /><span className="ld" />
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div style={{ display:'flex', gap:8, padding:'10px 12px', borderTop:`1px solid ${T.border}`, background:T.panel, flexShrink:0 }}>
        <textarea
          ref={taRef} rows={1} value={input}
          onChange={e => setInput(e.target.value)}
          onInput={autoResize}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
          placeholder={placeholder}
          style={{ flex:1, background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:9, padding:'11px 12px', fontSize:15, resize:'none', outline:'none', lineHeight:1.4 }}
        />
        <button onClick={() => send()} disabled={loading || !input.trim()} className="send-btn"
          style={{ opacity: loading || !input.trim() ? 0.4 : 1 }}>
          SEND
        </button>
      </div>
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// STATS TAB
// Schema reference for the AI:
//   history.seasons[].games[]: {week, playoff, a, b, pa, pb,
//     ap:{QB,RB,WR,TE,K,DEF}, bp:{QB,RB,WR,TE,K,DEF}}
//   a/b = manager handle, pa/pb = total team points that week
//   ap/bp = positional breakdown (starters only, non-zero positions)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function StatsTab({ historyData, statsData }) {
  const systemPrompt = `You are the statistician for the Borehamwood Plancy League. Answer ONLY from the data below — never invent numbers.

DATA SCHEMA:
- seasons[].games[]: {week, playoff(bool), a, b, pa, pb, ap, bp}
  - a/b = manager handle. pa/pb = total points. ap/bp = positional breakdown e.g. {QB:18.5, WR:42.3, RB:28.1, TE:9.4, K:11.2, DEF:8}
- seasons[].standings[]: {manager, team, wins, losses, pf, high}

COMPUTING TIPS (you MUST actually compute, do not just describe):
- Closest game: iterate all regular-season games, compute Math.abs(pa-pb), find minimum
- Most WR points: iterate games, sum ap.WR or bp.WR per manager per season, find max
- Winning margin: pa - pb (positive = team A won)
- All-time record: count wins/losses across all seasons for each manager

HISTORY (all seasons):
${JSON.stringify(historyData)}

CURRENT SEASON STATS:
${JSON.stringify(statsData)}`;

  return (
    <ChatTab
      systemPrompt={systemPrompt}
      chips={['Closest game ever?', 'Most WR pts in a season?', 'Best H2H record?', 'Biggest blowout?']}
      placeholder="Ask about records, H2H, stats…"
      errorMsg="Something went wrong — try again."
      intro="The complete record book. Ask about closest wins, positional stats, H2H records, season comparisons."
    />
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// BANTER TAB
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const LEAGUE_FACTS = `Borehamwood Plancy League. 1-QB redraft, WR/RB/TE flex, half-PPR, 8 teams. 2023–2025 complete.
2025 champion: Fourth and Goalda Meir (@AlastairL), beat @dpol 143.96-118.58 in the final.
@dpol won Wk3 2025 by 0.02 pts — the most celebrated marginal win in league history — then lost the final by 25.
@GSac posted 202.36 in Wk12 2025 (league all-time high) and still didn't make the final.
@sanfbe is AlastairL's bogey team — beat him twice in 2025 regular season.
Managers: AlastairL/Fourth and Goalda Meir; dpol/Plancey Neutral; GSac/Jewish Mccaffrey; sanfbe/J'Allen Plancey z'l; saulgoat/Love Thy Naber; drjkay/A rookie error; benjlev/benjlev; joshjr11/Denver Brochos.`;

function BanterTab({ historyData }) {
  const systemPrompt = `You are the resident wind-up merchant of the Borehamwood Plancy League. Voice: bone-dry British banter, mock gravity, never cruel. Use the LORE and history for material. Keep replies punchy (3-5 sentences max). Never invent a statistic.

${LEAGUE_FACTS}

LORE:
${LORE}

HISTORY:
${JSON.stringify(historyData)}`;

  return (
    <ChatTab
      systemPrompt={systemPrompt}
      chips={['Roast the 2025 champion', 'Most cursed manager?', "This week's smack bulletin"]}
      placeholder="Start some trouble…"
      errorMsg="Blimey — give it another go."
      intro="Pull up a chair. Ask for a roast, a smack-talk bulletin, or just stir the pot."
    />
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TRADE GRADER — module-level helpers (hoisted to prevent remount)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function TradePanel({ side, label, team, setTeam, text, setText, teamOpts }) {
  const accent = side === 'A' ? T.blue : T.red;
  return (
    <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderTop:`3px solid ${accent}`, borderRadius:'4px 4px 10px 10px', padding:12, flex:1, minWidth:0 }}>
      <div style={{ display:'flex', alignItems:'center', gap:7, marginBottom:9 }}>
        <span style={{ background:accent, color:'#fff', fontFamily:FH, fontWeight:700, fontSize:12, width:20, height:20, borderRadius:4, display:'flex', alignItems:'center', justifyContent:'center' }}>{side}</span>
        <span style={{ color:T.dim, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.07em' }}>{label}</span>
      </div>
      <select value={team} onChange={e => setTeam(e.target.value)}
        style={{ background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:7, padding:9, width:'100%', marginBottom:8, fontSize:13.5 }}>
        {teamOpts}
      </select>
      <textarea value={text} onChange={e => setText(e.target.value)}
        placeholder={"One player per line\ne.g. Ja'Marr Chase"}
        style={{ background:T.raised, color:T.text, border:`1px solid ${T.borderHi}`, borderRadius:7, padding:10, width:'100%', minHeight:90, fontSize:13.5, resize:'vertical', boxSizing:'border-box', lineHeight:1.5 }} />
    </div>
  );
}

function PlayerRow({ p }) {
  return (
    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'5px 0', borderBottom:`1px solid ${T.border}`, fontSize:13.5 }}>
      <span style={{ color: p.found ? T.text : T.gold }}>{p.found ? p.officialName : `${p.input} ⚠`}</span>
      <span style={{ color: p.found ? T.dim : T.gold, fontSize:12.5, marginLeft:8, fontFamily:FH, fontWeight:700 }}>
        {p.found ? p.value.toLocaleString() : 'no match'}
      </span>
    </div>
  );
}

function normalizeName(str) {
  return str.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TRADE GRADER
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function TradeGrader({ rostersData, tradeValues }) {
  const teamKeys = useMemo(() => Object.keys(rostersData || {}), [rostersData]);

  const [teamA, setTeamA]           = useState(teamKeys[0] || '');
  const [teamB, setTeamB]           = useState(teamKeys[1] || '');
  const [sideAText, setSideAText]   = useState('');
  const [sideBText, setSideBText]   = useState('');
  const [result, setResult]         = useState(null);
  const [verdict, setVerdict]       = useState(null);
  const [verdictLoading, setVL]     = useState(false);
  const [verdictError, setVE]       = useState(false);
  const [showWaiver, setShowWaiver] = useState(true);

  useEffect(() => {
    if (document.getElementById('tg-spin')) return;
    const s = document.createElement('style');
    s.id = 'tg-spin';
    s.textContent = '@keyframes tg-spin{to{transform:rotate(360deg)}}';
    document.head.appendChild(s);
  }, []);

  const { idMap, nameMap } = useMemo(() => {
    const id = new Map(), nm = new Map();
    for (const { player, redraftValue } of (tradeValues || [])) {
      const val = redraftValue || 0;
      if (player.sleeperId) id.set(player.sleeperId, { value: val, officialName: player.name, position: player.position });
      nm.set(normalizeName(player.name), { value: val, sleeperId: player.sleeperId, officialName: player.name, position: player.position });
    }
    return { idMap: id, nameMap: nm };
  }, []);

  // Available (unrostered) players from tradeValues × rostersData
  const waiverByPos = useMemo(() => {
    const rostered = new Set(
      Object.values(rostersData || {}).flatMap(team => team.map(p => p.id))
    );
    const avail = (tradeValues || []).filter(x => x.player.sleeperId && !rostered.has(x.player.sleeperId));
    const byPos = {};
    for (const p of avail) {
      const pos = p.player.position;
      if (!byPos[pos]) byPos[pos] = [];
      if (byPos[pos].length < 5) byPos[pos].push(p);
    }
    return byPos;
  }, []);

  function lookupPlayer(inputText) {
    const n = normalizeName(inputText);
    if (nameMap.has(n)) { const e = nameMap.get(n); return { found:true, value:e.value, officialName:e.officialName, position:e.position, sleeperId:e.sleeperId }; }
    for (const [key, e] of nameMap) {
      if (key.includes(n) || n.includes(key)) return { found:true, value:e.value, officialName:e.officialName, position:e.position, sleeperId:e.sleeperId };
    }
    return { found:false, value:0, officialName:inputText, position:null };
  }

  function gradeTrade() {
    const parse = txt => txt.split('\n').map(l => l.trim()).filter(Boolean).map(line => ({ input:line, ...lookupPlayer(line) }));
    const sA = parse(sideAText), sB = parse(sideBText);
    const tA = sA.reduce((s,p) => s+p.value, 0), tB = sB.reduce((s,p) => s+p.value, 0);
    const gap = Math.abs(tA - tB), gapPct = (gap / Math.max(tA, tB, 1)) * 100;
    const winner = gapPct < 5 ? 'even' : tA > tB ? 'A' : 'B';
    const tier   = gapPct < 5 ? 'DEAD EVEN' : gapPct < 12 ? 'SLIGHT EDGE' : gapPct < 25 ? 'CLEAR WINNER' : 'LOPSIDED';
    const icon   = gapPct < 5 ? '⚖️' : gapPct < 12 ? '📊' : gapPct < 25 ? '🏆' : '🚨';

    // Add-ons from losing team's roster
    let addOns = [];
    if (winner !== 'even') {
      const wTeam  = winner === 'A' ? teamA : teamB;
      const wSide  = winner === 'A' ? sA : sB;
      const exclude = new Set(wSide.map(p => p.officialName));
      addOns = ((rostersData || {})[wTeam] || [])
        .map(rp => ({ name: idMap.get(rp.id)?.officialName || rp.name, value: idMap.get(rp.id)?.value || 0, id: rp.id }))
        .filter(rp => !exclude.has(rp.name) && rp.value > 0)
        .sort((a,b) => Math.abs(a.value - gap) - Math.abs(b.value - gap))
        .slice(0, 3);
    }

    // Waiver context: top available at each position involved in this trade
    const positions = new Set([...sA, ...sB].map(p => p.position).filter(Boolean));
    const waiverContext = {};
    for (const pos of positions) {
      waiverContext[pos] = (waiverByPos[pos] || []).slice(0, 3);
    }

    setResult({ sA, sB, tA, tB, winner, tier, icon, gap, gapPct, addOns, waiverContext });
    setVerdict(null); setVE(false);
  }

  async function getVerdict() {
    if (!result) return;
    setVL(true); setVE(false); setVerdict(null);
    const { sA, sB, tA, tB, winner, tier, gap, gapPct, addOns } = result;
    const sys = "You are the wind-up merchant of the Borehamwood Plancy League. Quick, funny verdict in 2-4 sentences. Bone-dry British banter, mock gravity. Numbers are computed — do NOT recalculate.";
    const marginStr = winner === 'even' ? 'Even.' : ('Side ' + winner + ' wins by ' + gap.toFixed(0) + ' (' + gapPct.toFixed(0) + '%).');
    const addOnStr  = addOns.length ? ' Suggested add-on: ' + addOns.map(a => a.name).join(' or ') + '.' : '';
    const sideAStr  = sA.map(p => p.officialName + '(' + p.value + ')').join(', ');
    const sideBStr  = sB.map(p => p.officialName + '(' + p.value + ')').join(', ');
    const msg = 'Trade:\nSide A (' + teamA + ') gives: ' + sideAStr + ' — Total ' + tA +
                '\nSide B (' + teamB + ') gives: ' + sideBStr + ' — Total ' + tB +
                '\nVerdict: ' + tier + '. ' + marginStr + addOnStr;
    try {
      const r = await claudeCall([{ role:'user', content:msg }], sys);
      setVerdict(r);
    } catch { setVE(true); }
    finally { setVL(false); }
  }

  const teamOpts = teamKeys.map(k => <option key={k} value={k}>{k}</option>);
  const winA = result?.winner === 'A', winB = result?.winner === 'B';
  const POSColors = { QB: '#e87c0d', RB: '#1a9e6b', WR: '#2e7fcf', TE: '#9b4fc4', K: '#888', DEF: '#c44' };

  const spin = { width:14, height:14, border:`2px solid ${T.gold}`, borderTopColor:'transparent', borderRadius:'50%', display:'inline-block', animation:'tg-spin 0.8s linear infinite' };

  return (
    <div style={{ background:T.bg, color:T.text, overflowY:'auto', height:'100%', boxSizing:'border-box' }}>

      {/* Waiver Wire Snapshot — always visible, collapsible */}
      <div style={{ borderBottom:`1px solid ${T.border}`, background:T.panel }}>
        <button onClick={() => setShowWaiver(v => !v)}
          style={{ width:'100%', display:'flex', alignItems:'center', justifyContent:'space-between', padding:'10px 14px', background:'none', border:'none', color:T.dim, cursor:'pointer', fontSize:12.5, fontWeight:700, letterSpacing:'0.07em', textTransform:'uppercase' }}>
          <span>📋  Waiver Wire Snapshot  <span style={{ color:T.faint, fontSize:11, fontWeight:400 }}>(top available by position)</span></span>
          <span style={{ fontSize:10, color:T.faint }}>{showWaiver ? '▲ hide' : '▼ show'}</span>
        </button>
        {showWaiver && (
          <div style={{ padding:'0 12px 12px', display:'flex', flexWrap:'wrap', gap:8 }}>
            {['QB','RB','WR','TE'].map(pos => {
              const players = waiverByPos[pos] || [];
              if (!players.length) return null;
              return (
                <div key={pos} style={{ background:T.raised, border:`1px solid ${T.border}`, borderTop:`2px solid ${POSColors[pos]||T.border}`, borderRadius:'3px 3px 8px 8px', padding:'8px 10px', minWidth:120, flex:'1 1 120px', maxWidth:160 }}>
                  <div style={{ color:POSColors[pos]||T.dim, fontSize:10.5, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.07em', marginBottom:5 }}>{pos}</div>
                  {players.map((p,i) => (
                    <div key={i} style={{ display:'flex', justifyContent:'space-between', fontSize:12.5, padding:'2px 0', borderBottom: i<players.length-1 ? `1px solid ${T.border}` : 'none' }}>
                      <span style={{ color:T.text }}>{p.player.name}</span>
                      <span style={{ color:T.dim, fontFamily:FH, fontSize:11.5 }}>{p.redraftValue.toLocaleString()}</span>
                    </div>
                  ))}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Trade inputs */}
      <div style={{ padding:14 }}>
        <div style={{ display:'flex', flexWrap:'wrap', gap:10 }}>
          <TradePanel side="A" label="Side A gives up" team={teamA} setTeam={setTeamA} text={sideAText} setText={setSideAText} teamOpts={teamOpts} />
          <TradePanel side="B" label="Side B gives up" team={teamB} setTeam={setTeamB} text={sideBText} setText={setSideBText} teamOpts={teamOpts} />
        </div>

        <button onClick={gradeTrade} disabled={!sideAText.trim() && !sideBText.trim()}
          style={{ width:'100%', background:(!sideAText.trim()&&!sideBText.trim()) ? T.raised : `linear-gradient(135deg,${T.red},${T.redDk})`, color:(!sideAText.trim()&&!sideBText.trim()) ? T.faint : '#fff', border:'none', borderRadius:10, padding:14, fontSize:15, fontWeight:700, letterSpacing:'1.5px', textTransform:'uppercase', fontFamily:FH, cursor:(!sideAText.trim()&&!sideBText.trim())?'default':'pointer', marginTop:11, boxShadow:(!sideAText.trim()&&!sideBText.trim())?'none':'0 3px 14px rgba(232,17,45,0.28)' }}>
          Grade This Trade
        </button>

        {result && (
          <div className="msg-in" style={{ marginTop:16 }}>
            {/* Scoreboard */}
            <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderRadius:12, overflow:'hidden', marginBottom:12 }}>
              <div style={{ display:'flex', alignItems:'stretch' }}>
                <div style={{ flex:1, padding:'14px 10px', textAlign:'center', background: winA ? 'rgba(34,201,111,0.07)' : 'transparent', borderRight:`1px solid ${T.border}` }}>
                  <div style={{ fontSize:10, color:T.faint, textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:4, fontFamily:FH }}>SIDE A</div>
                  <div style={{ fontFamily:FH, fontWeight:700, fontSize:30, color: winA ? T.green : T.text, lineHeight:1 }}>{result.tA.toLocaleString()}</div>
                  {winA && <div style={{ fontSize:10, color:T.green, fontWeight:700, marginTop:3, textTransform:'uppercase', letterSpacing:'0.05em' }}>▲ WINS</div>}
                </div>
                <div style={{ display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', padding:'0 12px', minWidth:90 }}>
                  <div style={{ fontSize:22 }}>{result.icon}</div>
                  <div style={{ fontFamily:FH, fontWeight:700, fontSize:12.5, color:T.gold, letterSpacing:'0.04em', textAlign:'center', lineHeight:1.1, marginTop:3 }}>{result.tier}</div>
                  {result.winner !== 'even' && <div style={{ fontSize:10.5, color:T.dim, marginTop:3 }}>by {result.gap.toLocaleString()} ({result.gapPct.toFixed(0)}%)</div>}
                </div>
                <div style={{ flex:1, padding:'14px 10px', textAlign:'center', background: winB ? 'rgba(34,201,111,0.07)' : 'transparent', borderLeft:`1px solid ${T.border}` }}>
                  <div style={{ fontSize:10, color:T.faint, textTransform:'uppercase', letterSpacing:'0.08em', marginBottom:4, fontFamily:FH }}>SIDE B</div>
                  <div style={{ fontFamily:FH, fontWeight:700, fontSize:30, color: winB ? T.green : T.text, lineHeight:1 }}>{result.tB.toLocaleString()}</div>
                  {winB && <div style={{ fontSize:10, color:T.green, fontWeight:700, marginTop:3, textTransform:'uppercase', letterSpacing:'0.05em' }}>▲ WINS</div>}
                </div>
              </div>
            </div>

            {/* Player breakdown */}
            <div style={{ display:'flex', flexWrap:'wrap', gap:10, marginBottom:12 }}>
              {[{ side:'A', players:result.sA, team:teamA, accent:T.blue }, { side:'B', players:result.sB, team:teamB, accent:T.red }].map(({ side, players, team, accent }) => (
                <div key={side} style={{ flex:1, minWidth:140, background:T.panel, border:`1px solid ${T.border}`, borderRadius:10, padding:'10px 12px' }}>
                  <div style={{ color:accent, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em', marginBottom:6, fontFamily:FH }}>{team || `Side ${side}`} gives</div>
                  {players.length ? players.map((p,i) => <PlayerRow key={i} p={p} />) : <div style={{ color:T.faint, fontSize:12 }}>—</div>}
                </div>
              ))}
            </div>

            {/* Add-ons */}
            {result.winner !== 'even' && result.addOns.length > 0 && (
              <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderLeft:`3px solid ${T.gold}`, borderRadius:'4px 10px 10px 4px', padding:'10px 12px', marginBottom:12 }}>
                <div style={{ color:T.gold, fontSize:11, marginBottom:6, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em', fontFamily:FH }}>To balance, {result.winner==='A' ? teamA : teamB} could add</div>
                {result.addOns.map((a,i) => (
                  <div key={i} style={{ display:'flex', justifyContent:'space-between', fontSize:13.5, padding:'3px 0' }}>
                    <span>{a.name}</span><span style={{ color:T.dim, fontFamily:FH }}>{a.value.toLocaleString()}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Waiver context for traded positions */}
            {Object.keys(result.waiverContext).length > 0 && (
              <div style={{ background:T.panel, border:`1px solid ${T.border}`, borderRadius:10, padding:'10px 12px', marginBottom:12 }}>
                <div style={{ color:T.dim, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:8, fontFamily:FH }}>Waiver alternatives for traded positions</div>
                {Object.entries(result.waiverContext).map(([pos, players]) => (
                  <div key={pos} style={{ marginBottom:8 }}>
                    <span style={{ color:POSColors[pos]||T.dim, fontSize:11, fontWeight:700, textTransform:'uppercase', fontFamily:FH }}>{pos}: </span>
                    {players.map((p,i) => (
                      <span key={i} style={{ fontSize:13, color:T.text }}>
                        {p.player.name} <span style={{ color:T.dim, fontFamily:FH, fontSize:12 }}>({p.redraftValue.toLocaleString()})</span>
                        {i < players.length - 1 ? <span style={{ color:T.faint }}> · </span> : ''}
                      </span>
                    ))}
                  </div>
                ))}
              </div>
            )}

            {/* Commissioner's Verdict button */}
            <button onClick={getVerdict} disabled={verdictLoading}
              style={{ width:'100%', background:T.panel, border:`1px solid ${T.gold}`, color:T.gold, borderRadius:10, padding:'13px 20px', fontSize:13.5, fontWeight:700, letterSpacing:'0.5px', textTransform:'uppercase', fontFamily:FH, cursor: verdictLoading ? 'default' : 'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:9, opacity: verdictLoading ? 0.7 : 1 }}>
              {verdictLoading ? <span style={spin} /> : '🎙'}
              The Commissioner's Verdict
            </button>

            {(verdict || verdictError) && (
              <div className="msg-in" style={{ background:T.panel2, border:`1px solid ${verdictError ? T.gold : T.border}`, borderLeft:`3px solid ${verdictError ? T.gold : T.red}`, borderRadius:'4px 12px 12px 4px', padding:14, color: verdictError ? T.gold : T.text, whiteSpace:'pre-wrap', marginTop:10, fontSize:14, lineHeight:1.6 }}>
                {verdictError ? 'The Commissioner is unavailable — give it another go.' : verdict}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GLOBAL CSS + APP SHELL
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #07090f; -webkit-font-smoothing: antialiased; }

  ::-webkit-scrollbar { width: 4px; height: 4px; }
  ::-webkit-scrollbar-thumb { background: #232f3e; border-radius: 2px; }

  @keyframes ld-pulse { 0%,80%,100%{opacity:.2;transform:scale(.7)} 40%{opacity:1;transform:scale(1)} }
  .ld { display:inline-block; width:7px; height:7px; background:#e8112d; border-radius:50%; margin:0 2px; animation:ld-pulse 1.4s infinite ease-in-out both; }
  .ld:nth-child(2){animation-delay:.2s} .ld:nth-child(3){animation-delay:.4s}

  @keyframes fadeUp { from{opacity:0;transform:translateY(5px)} to{opacity:1;transform:none} }
  .msg-in { animation: fadeUp .22s ease both; }

  .bubble-user {
    align-self:flex-end;
    background:linear-gradient(135deg,#e8112d,#b00a23);
    color:#fff;
    border-radius:14px 14px 3px 14px;
    padding:10px 14px;
    max-width:80%;
    font-size:14.5px;
    line-height:1.5;
    white-space:pre-wrap;
    box-shadow:0 2px 10px rgba(232,17,45,0.22);
  }
  .bubble-assistant {
    align-self:flex-start;
    background:#141d2b;
    color:#eef3f9;
    border-left:3px solid #e8112d;
    border-radius:4px 14px 14px 14px;
    padding:10px 14px;
    max-width:80%;
    font-size:14.5px;
    line-height:1.55;
    white-space:pre-wrap;
    box-shadow:0 1px 6px rgba(0,0,0,0.3);
  }
  .bubble-error {
    align-self:flex-start;
    background:#141d2b;
    color:#ffbe2e;
    border-left:3px solid #ffbe2e;
    border-radius:4px 14px 14px 14px;
    padding:10px 14px;
    max-width:80%;
    font-size:14.5px;
    white-space:pre-wrap;
  }

  .chip {
    background:#1a2334;
    border:1px solid #304050;
    color:#eef3f9;
    border-radius:7px;
    padding:7px 12px;
    font-size:12.5px;
    font-weight:600;
    cursor:pointer;
    white-space:nowrap;
    flex-shrink:0;
    letter-spacing:0.2px;
    transition:border-color 0.12s;
  }
  .chip:hover:not(:disabled) { border-color:#e8112d; }
  .chip:disabled { opacity:0.4; cursor:default; }

  .send-btn {
    background:linear-gradient(135deg,#e8112d,#b00a23);
    color:#fff;
    border:none;
    border-radius:9px;
    padding:0 18px;
    font-weight:700;
    font-size:12.5px;
    letter-spacing:1px;
    text-transform:uppercase;
    cursor:pointer;
    align-self:stretch;
    flex-shrink:0;
    font-family:Impact,'Arial Black',Arial,sans-serif;
    transition:opacity 0.1s;
  }
  .send-btn:disabled { background:#1a2334; color:#4a5a6a; cursor:default; }

  .plaincy-app {
    display:flex;
    flex-direction:column;
    height:100dvh;
    width:100%;
    max-width:520px;
    margin:0 auto;
    background:#07090f;
    overflow:hidden;
    box-shadow:0 0 80px rgba(0,0,0,0.7);
  }
  @media(min-width:640px) {
    .plaincy-app { max-width:720px; }
    .bubble-user, .bubble-assistant, .bubble-error { max-width:72%; }
  }

  button { font-family:inherit; }
  textarea, select, input { font-family:inherit; }
  textarea:focus, select:focus { border-color:#304050; outline:none; }
  select option { background:#141d2b; color:#eef3f9; }
`;

const TABS = [
  { id:'stats',  icon:'📊', label:'STATS'  },
  { id:'banter', icon:'🎙', label:'BANTER' },
  { id:'trade',  icon:'⚖️', label:'TRADES' },
];

export default function App() {
  const [tab, setTab] = useState('stats');
  const { history, stats, rosters, trades, source } = useLeagueData();

  useEffect(() => {
    if (document.getElementById('plaincy-css')) return;
    const el = document.createElement('style');
    el.id = 'plaincy-css';
    el.textContent = CSS;
    document.head.appendChild(el);
  }, []);

  const Tab = ({ id, icon, label }) => {
    const active = tab === id;
    return (
      <button onClick={() => setTab(id)} style={{
        flex:1, padding:'10px 4px 8px', background: active ? T.panel2 : 'transparent', border:'none',
        borderBottom: active ? `3px solid ${T.red}` : '3px solid transparent',
        color: active ? T.text : T.faint, cursor:'pointer',
        display:'flex', flexDirection:'column', alignItems:'center', gap:3,
        transition:'color 0.12s',
      }}>
        <span style={{ fontSize:16, filter: active ? 'none' : 'grayscale(0.5) opacity(0.6)' }}>{icon}</span>
        <span style={{ fontSize:11, fontWeight:700, letterSpacing:'0.08em', fontFamily:FH }}>{label}</span>
      </button>
    );
  };

  const isLive = source === 'live';

  return (
    <div className="plaincy-app">
      {/* Top accent stripe */}
      <div style={{ height:3, background:`linear-gradient(90deg,${T.red} 0%,${T.gold} 50%,${T.red} 100%)`, flexShrink:0 }} />

      {/* Header */}
      <div style={{ display:'flex', alignItems:'center', gap:12, padding:'11px 16px', background:`linear-gradient(180deg,${T.panel} 0%,${T.bg} 100%)`, borderBottom:`1px solid ${T.border}`, flexShrink:0 }}>
        <div style={{ width:40, height:40, borderRadius:10, background:`linear-gradient(135deg,${T.red},${T.redDk})`, display:'flex', alignItems:'center', justifyContent:'center', fontFamily:FH, fontWeight:700, fontSize:24, color:'#fff', boxShadow:'0 2px 12px rgba(232,17,45,0.35)', border:`1px solid ${T.gold}`, borderBottom:`3px solid ${T.gold}`, flexShrink:0 }}>P</div>
        <div style={{ flex:1, minWidth:0 }}>
          <div style={{ fontFamily:FH, fontSize:22, fontWeight:700, color:T.text, letterSpacing:'0.02em', lineHeight:1, textTransform:'uppercase' }}>
            Pl<span style={{ color:T.red }}>AI</span>ncy
          </div>
          <div style={{ fontSize:10.5, color:T.dim, marginTop:3, letterSpacing:'0.12em', textTransform:'uppercase', fontFamily:FH, fontWeight:600 }}>
            Borehamwood Plancy League
          </div>
        </div>
        {/* Data freshness badge — green LIVE if CDN reachable, amber CACHED if not */}
        <div style={{ fontFamily:FH, fontWeight:700, fontSize:10.5, color: isLive ? T.green : T.gold, border:`1px solid ${isLive ? T.green : T.borderHi}`, borderRadius:5, padding:'4px 9px', letterSpacing:'0.05em', whiteSpace:'nowrap', flexShrink:0, display:'flex', alignItems:'center', gap:4 }}>
          <span style={{ width:6, height:6, borderRadius:'50%', background: isLive ? T.green : T.gold, display:'inline-block' }} />
          {isLive ? 'LIVE' : 'CACHED'}
        </div>
      </div>

      {/* Tab bar */}
      <div style={{ display:'flex', background:T.panel, borderBottom:`1px solid ${T.border}`, flexShrink:0 }}>
        {TABS.map(t => <Tab key={t.id} {...t} />)}
      </div>

      {/* Content — data passed as props so all tabs use the same source */}
      <div style={{ flex:1, overflow:'hidden', display:'flex', flexDirection:'column' }}>
        {tab === 'stats'  && <StatsTab  historyData={history} statsData={stats} />}
        {tab === 'banter' && <BanterTab historyData={history} />}
        {tab === 'trade'  && <TradeGrader rostersData={rosters} tradeValues={trades} />}
      </div>
    </div>
  );
}
